package com.sacco.mvp.accounting.policy.model;

public enum AccountRole {
    CASH_BANK, LOAN_PRINCIPAL, INTEREST_RECEIVABLE, INTEREST_INCOME,
    FEE_RECEIVABLE, FEE_INCOME, CUSTOMER_ADVANCE, SUSPENSE, PAYABLE, EXPENSE,
    FUNDING_PRINCIPAL, FUNDING_INTEREST, CAPITAL, ALLOWANCE, IMPAIRMENT_EXPENSE,
    ASSET, DEPRECIATION, ACCUMULATED_DEPRECIATION, TAX_PAYABLE, INTERNAL_TRANSFER,
    RETAINED_EARNINGS, RECOVERY_INCOME, PREPAYMENT, EXPENSE_ACCRUAL
}
