package com.sacco.mvp.accounting.policy.model;

/** Evidence-backed human decisions; text is never executable financial logic. */
public enum PolicyDecision {
    REPORTING_FRAMEWORK, FINANCIAL_YEAR, CHART_OF_ACCOUNTS, OPENING_BALANCES,
    ROUNDING, INTEREST_RECOGNITION, FEES_AND_TAXES, IMPAIRMENT,
    NON_PERFORMING_INTEREST, EARLY_SETTLEMENT, APPROVAL_MATRIX, CLOSING_AND_BACKDATING,
    BRANCH_ALLOCATION, AUDIT_RETENTION_AND_RECOVERY, REGULATORY_REVIEW
}
