<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ include file="../../fragments/header.jspf" %>
<%@ include file="../../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/reconciliation.css' />" />
<main class="reconciliation-workspace">
<div class="erp-page-header" data-aws-page-header><h1 class="erp-page-title"><spring:message code="reconciliation.title" /></h1></div>
<p><spring:message code="reconciliation.evidenceOnly" /></p>
<section class="erp-table-wrap" data-aws-table-region><h2><spring:message code="reconciliation.statements" /></h2><div class="erp-table-scroll" data-view-position-key="reconciliation-statements"><table class="erp-table"><thead><tr><th><spring:message code="reconciliation.account" /></th><th><spring:message code="reconciliation.period" /></th><th><spring:message code="reconciliation.filename" /></th><th><spring:message code="reconciliation.closingTZS" /></th><th><spring:message code="common.actions" /></th></tr></thead><tbody>
<c:forEach items="${statements.rows}" var="s"><tr><td><c:out value="${s.accountCode}" /></td><td><c:out value="${s.from} – ${s.through}" /></td><td><c:out value="${s.filename}" /></td><td class="money"><c:out value="${s.closing}" /></td><td><a class="app-btn btn-neutral" href="<c:url value='/finance/reconciliation/statements/${s.id}' />"><spring:message code="reconciliation.review" /></a></td></tr></c:forEach>
<c:if test="${empty statements.rows}"><tr><td colspan="5"><spring:message code="reconciliation.empty" /></td></tr></c:if></tbody></table></div></section>
<section class="reconciliation-form"><h2><spring:message code="reconciliation.formats" /></h2>
<c:forEach items="${formats}" var="f"><p><c:out value="${f.name}" /> — <spring:message code="reconciliation.state.${empty f.checker ? 'DRAFT' : 'APPROVED'}" /></p>
<sec:authorize access="@access.has(principal,'ACCOUNTING_RECONCILIATION_APPROVE')"><c:if test="${empty f.checker}"><form method="post" action="<c:url value='/finance/reconciliation/formats/${f.id}/approve' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="reconciliation.reviewEvidence" /><input name="evidence" class="aws-control" maxlength="500" required /></label><button class="app-btn btn-neutral"><spring:message code="reconciliation.approve" /></button></form></c:if></sec:authorize></c:forEach>
<sec:authorize access="@access.has(principal,'ACCOUNTING_RECONCILIATION_CREATE')"><form method="post" action="<c:url value='/finance/reconciliation/formats' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><div class="reconciliation-grid"><label><spring:message code="reconciliation.formatName" /><input name="name" class="aws-control" maxlength="120" required /></label><label><spring:message code="reconciliation.evidence" /><input name="evidence" class="aws-control" maxlength="500" required /></label></div><p><spring:message code="reconciliation.formatHelp" /></p><button class="app-btn btn-neutral"><spring:message code="reconciliation.proposeFormat" /></button></form></sec:authorize></section>
<sec:authorize access="@access.has(principal,'ACCOUNTING_RECONCILIATION_CREATE')"><section class="reconciliation-form"><h2><spring:message code="reconciliation.import" /></h2>
<form method="post" enctype="multipart/form-data" data-statement-import action="<c:url value='/finance/reconciliation/import' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="requestKey" value="<c:out value='${requestKey}' />" /><div class="reconciliation-grid">
<label><spring:message code="reconciliation.account" /><select name="account" class="aws-control" required><c:forEach items="${balances.rows}" var="a"><c:if test="${a.purpose=='BANK' or a.purpose=='MOBILE_MONEY'}"><option value="${a.id}" ${draft.account==a.id?'selected':''}><c:out value="${a.code} ${a.name}" /></option></c:if></c:forEach></select></label>
<label><spring:message code="reconciliation.format" /><select name="format" class="aws-control" required><c:forEach items="${formats}" var="f"><c:if test="${not empty f.checker}"><option value="${f.id}" ${draft.format==f.id?'selected':''}><c:out value="${f.name}" /></option></c:if></c:forEach></select></label>
<label><spring:message code="reconciliation.from" /><input name="from" type="date" value="${draft.from}" class="aws-control" required /></label><label><spring:message code="reconciliation.through" /><input name="through" type="date" value="${draft.through}" class="aws-control" required /></label>
<label><spring:message code="reconciliation.openingTZS" /><input name="opening" value="${draft.opening}" inputmode="decimal" class="aws-control" required /></label><label><spring:message code="reconciliation.closingTZS" /><input name="closing" value="${draft.closing}" inputmode="decimal" class="aws-control" required /></label>
<label><spring:message code="reconciliation.filename" /><input name="filename" value="<c:out value='${draft.filename}' />" maxlength="160" class="aws-control" /></label><label><spring:message code="reconciliation.evidence" /><input name="evidence" value="<c:out value='${draft.evidence}' />" maxlength="500" class="aws-control" required /></label></div>
<label><spring:message code="reconciliation.uploadFile" /><input type="file" name="statementFile" accept=".csv,text/csv" class="aws-control" /></label><p><spring:message code="reconciliation.uploadHelp" /></p><c:if test="${uploadedPreview}"><p role="status"><spring:message code="reconciliation.reselectFile" /></p></c:if>
<label><spring:message code="reconciliation.csv" /><textarea name="content" class="aws-control" maxlength="1000000" placeholder="date,reference,amount,kind"><c:out value="${draft.content}" /></textarea></label><div class="reconciliation-actions"><button name="action" value="preview" class="app-btn btn-neutral"><spring:message code="reconciliation.preview" /></button><button name="action" value="import" class="app-btn btn-primary"><spring:message code="reconciliation.import" /></button></div></form>
<c:if test="${previewReady}"><p role="status"><spring:message code="reconciliation.previewPassed" /> <c:out value="${preview.size()}" /></p></c:if></section></sec:authorize>
<section class="erp-table-wrap" data-aws-table-region><h2><spring:message code="reconciliation.matches" /></h2><div class="erp-table-scroll" data-view-position-key="reconciliation-matches"><table class="erp-table"><thead><tr><th><spring:message code="reconciliation.kind" /></th><th><spring:message code="reconciliation.state" /></th><th><spring:message code="reconciliation.evidence" /></th><th><spring:message code="common.actions" /></th></tr></thead><tbody>
<c:forEach items="${matches.rows}" var="r"><tr><td><spring:message code="reconciliation.kind.${r.kind}" /></td><td><spring:message code="reconciliation.state.${r.state}" /></td><td><c:out value="${r.evidence}" /></td><td>
<sec:authorize access="@access.has(principal,'ACCOUNTING_RECONCILIATION_APPROVE')"><c:if test="${r.state=='DRAFT'}"><form method="post" action="<c:url value='/finance/reconciliation/matches/${r.id}/review' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="reconciliation.reviewEvidence" /><input name="evidence" maxlength="500" class="aws-control" required /></label><button name="approved" value="true" class="app-btn btn-primary"><spring:message code="reconciliation.approve" /></button><button name="approved" value="false" class="app-btn btn-neutral"><spring:message code="reconciliation.reject" /></button></form></c:if></sec:authorize>
<sec:authorize access="@access.has(principal,'ACCOUNTING_RECONCILIATION_CREATE')"><c:if test="${r.state=='APPROVED' and empty r.reverses}"><form method="post" action="<c:url value='/finance/reconciliation/matches/${r.id}/reverse' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="reconciliation.reason" /><input name="evidence" maxlength="500" class="aws-control" required /></label><button class="app-btn btn-neutral"><spring:message code="reconciliation.reverseMatch" /></button></form></c:if></sec:authorize></td></tr></c:forEach>
<c:if test="${empty matches.rows}"><tr><td colspan="4"><spring:message code="reconciliation.empty" /></td></tr></c:if></tbody></table></div></section>
<section class="erp-table-wrap" data-aws-table-region><h2><spring:message code="reconciliation.exceptions" /></h2><p><spring:message code="reconciliation.differenceRetained" /></p><div class="erp-table-scroll" data-view-position-key="reconciliation-exceptions"><table class="erp-table"><thead><tr><th><spring:message code="reconciliation.kind" /></th><th><spring:message code="reconciliation.state" /></th><th><spring:message code="reconciliation.evidence" /></th><th><spring:message code="common.actions" /></th></tr></thead><tbody>
<c:forEach items="${exceptions.rows}" var="r"><tr><td><spring:message code="reconciliation.kind.${r.kind}" /></td><td><spring:message code="reconciliation.state.${r.state}" /></td><td><c:out value="${r.evidence}" /><c:if test="${not empty r.timing}"><p><spring:message code="reconciliation.timingSource" />: <c:out value="${r.timing.reference} (${r.timing.journalDate}) ${r.timing.amount}" /></p><p><spring:message code="reconciliation.statementDate" />: <c:out value="${r.timing.statementReference} (${r.timing.statementDate}) ${r.timing.statementAmount}" /></p></c:if></td><td><sec:authorize access="@access.has(principal,'ACCOUNTING_RECONCILIATION_APPROVE')"><c:if test="${r.state=='OPEN'}"><form method="post" action="<c:url value='/finance/reconciliation/exceptions/${r.id}/review' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="reconciliation.reviewEvidence" /><input name="evidence" maxlength="500" class="aws-control" required /></label><button class="app-btn btn-neutral"><spring:message code="reconciliation.reviewDifference" /></button></form></c:if></sec:authorize></td></tr></c:forEach><c:if test="${empty exceptions.rows}"><tr><td colspan="4"><spring:message code="reconciliation.empty" /></td></tr></c:if></tbody></table></div></section>
<section class="erp-table-wrap" data-aws-table-region><h2><spring:message code="reconciliation.balances" /></h2><form method="get" class="reconciliation-actions" data-aws-filter-toolbar><label><spring:message code="reconciliation.asOf" /><input type="date" name="asOf" value="${asOf}" required /></label><button class="app-btn btn-neutral"><spring:message code="reconciliation.refresh" /></button></form><div class="erp-table-scroll" data-view-position-key="reconciliation-balances"><table class="erp-table"><thead><tr><th><spring:message code="reconciliation.account" /></th><th><spring:message code="reconciliation.ledgerTZS" /></th></tr></thead><tbody><c:forEach items="${balances.rows}" var="a"><tr><td><c:out value="${a.code} ${a.name}" /></td><td class="money"><c:out value="${a.balance}" /></td></tr></c:forEach><c:if test="${empty balances.rows}"><tr><td colspan="2"><spring:message code="reconciliation.empty" /></td></tr></c:if></tbody></table></div></section>
<sec:authorize access="@access.has(principal,'ACCOUNTING_RECONCILIATION_CREATE')"><section class="reconciliation-form"><h2><spring:message code="reconciliation.certificate" /></h2><form method="post" action="<c:url value='/finance/reconciliation/certificates' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><div class="reconciliation-grid"><label><spring:message code="reconciliation.account" /><select name="account" class="aws-control"><c:forEach items="${balances.rows}" var="a"><option value="${a.id}"><c:out value="${a.code} ${a.name}" /></option></c:forEach></select></label><label><spring:message code="reconciliation.asOf" /><input name="asOf" type="date" value="${asOf}" class="aws-control" required /></label><label><spring:message code="reconciliation.kind" /><select name="kind" class="aws-control"><c:forEach items="${['PHYSICAL_CASH','STATEMENT','CLEARING','LOAN_CONTROL','SUPPLIER','FUNDING','OPENING']}" var="kind"><option value="${kind}"><spring:message code="reconciliation.kind.${kind}" /></option></c:forEach></select></label><label><spring:message code="reconciliation.sourceTZS" /><input name="source" inputmode="decimal" class="aws-control" required /></label><label><spring:message code="reconciliation.evidence" /><input name="evidence" maxlength="500" class="aws-control" required /></label></div><button class="app-btn btn-primary"><spring:message code="reconciliation.proposeCertificate" /></button></form></section></sec:authorize>
<section class="erp-table-wrap" data-aws-table-region><h2><spring:message code="reconciliation.certificates" /></h2><div class="erp-table-scroll" data-view-position-key="reconciliation-certificates"><table class="erp-table"><thead><tr><th><spring:message code="reconciliation.account" /></th><th><spring:message code="reconciliation.asOf" /></th><th><spring:message code="reconciliation.sourceTZS" /></th><th><spring:message code="reconciliation.ledgerTZS" /></th><th><spring:message code="reconciliation.differenceTZS" /></th><th><spring:message code="reconciliation.state" /></th><th><spring:message code="common.actions" /></th></tr></thead><tbody><c:forEach items="${certificates.rows}" var="r"><tr><td><c:out value="${r.code}" /></td><td><c:out value="${r.asOf}" /></td><td class="money"><c:out value="${r.sourceBalance}" /></td><td class="money"><c:out value="${r.ledgerBalance}" /></td><td class="money"><c:out value="${r.difference}" /></td><td><spring:message code="reconciliation.state.${r.state}" /></td><td><c:if test="${not empty r.sourceStatement}"><a class="app-btn btn-neutral" href="<c:url value='/finance/reconciliation/statements/${r.sourceStatement}/evidence' />"><spring:message code="reconciliation.fileEvidence" /></a><details><summary><c:out value="${r.sourceFilename}" /></summary><c:out value="${r.sourceChecksum}" /></details></c:if><sec:authorize access="@access.has(principal,'ACCOUNTING_RECONCILIATION_APPROVE')"><c:if test="${empty r.checker}"><form method="post" action="<c:url value='/finance/reconciliation/certificates/${r.id}/review' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="reconciliation.reviewEvidence" /><input name="evidence" maxlength="500" class="aws-control" required /></label><button class="app-btn btn-neutral"><spring:message code="reconciliation.reviewDifference" /></button></form></c:if></sec:authorize></td></tr></c:forEach><c:if test="${empty certificates.rows}"><tr><td colspan="7"><spring:message code="reconciliation.empty" /></td></tr></c:if></tbody></table></div></section>
<div class="reconciliation-actions"><c:if test="${page>0}"><a class="app-btn btn-neutral" href="<c:url value='/finance/reconciliation?page=${page-1}&asOf=${asOf}' />"><spring:message code="common.previous" /></a></c:if><c:if test="${statements.hasNext or matches.hasNext or exceptions.hasNext or certificates.hasNext or balances.hasNext}"><a class="app-btn btn-neutral" href="<c:url value='/finance/reconciliation?page=${page+1}&asOf=${asOf}' />"><spring:message code="common.next" /></a></c:if></div>
</main><script src="<c:url value='/js/reconciliation.js' />" defer></script><%@ include file="../../fragments/footer.jspf" %>
