package com.sacco.mvp.accounting.statements;

import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import tools.jackson.databind.ObjectMapper;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.*;
import java.util.*;

@Repository @RequiredArgsConstructor
public class StatementRepository {
    private final JdbcTemplate jdbc;
    private final ObjectMapper mapper;
    public record Version(UUID id,UUID template,int version,String state,UUID maker,UUID checker,String evidence,String reviewEvidence,StatementDefinition definition) { }
    public record Balance(StatementDefinition.Account account,BigDecimal opening,BigDecimal debit,BigDecimal credit,BigDecimal closing) { }
    public record StoredResult(UUID id,String institution,String branch,String json,String checksum) { }
    public record OfficialFormat(UUID id,String authority,String key,String version,String json,String checksum,String reference) { }
    public record Submission(UUID id,UUID format,UUID result,LocalDate from,LocalDate through,LocalDate deadline,String file,String fileChecksum,String evidence,UUID corrects,UUID maker,UUID checker,String reviewEvidence) { }
    public List<StatementDefinition.Account> accounts(String institution) {
        return jdbc.query("select id,code,name,type,purpose from gl_account where sacco_id=? and kind<>'HEADING' order by code,id limit 1001",(r,n)->new StatementDefinition.Account(r.getObject("id",UUID.class),r.getString("code"),r.getString("name"),r.getString("type"),r.getString("purpose")),institution);
    }
    public boolean openingAvailable(String institution,String branch,LocalDate through,OffsetDateTime cutoff){return Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from gl_cutover_coverage c join gl_journal j on j.id=c.opening_journal_id where c.sacco_id=? and c.station_id=? and c.complete and c.recorded_at<=? and j.state='POSTED' and j.effective_date<=? and j.posted_at<=?)",Boolean.class,institution,branch,cutoff,through,cutoff));}
    public List<Balance> balances(String institution,String branch,LocalDate from,LocalDate through,OffsetDateTime cutoff) {
        return jdbc.query("""
            select a.id,a.code,a.name,a.type,a.purpose,
            coalesce(sum(b.debit-b.credit) filter(where b.effective_date<? or b.source_type='OPENING'),0) opening,
            coalesce(sum(b.debit) filter(where b.effective_date>=? and b.source_type<>'OPENING'),0) debit,
            coalesce(sum(b.credit) filter(where b.effective_date>=? and b.source_type<>'OPENING'),0) credit,
            coalesce(sum(b.debit-b.credit),0) closing
            from gl_account a left join (select l.account_id,l.debit,l.credit,j.effective_date,j.source_type from gl_journal_line l join gl_journal j on j.id=l.journal_id and j.sacco_id=l.sacco_id
            where j.sacco_id=? and j.station_id=? and j.state='POSTED' and j.effective_date<=? and j.posted_at<=?) b on b.account_id=a.id
            where a.sacco_id=? and a.kind<>'HEADING'
            group by a.id order by a.code,a.id limit 1001
            """,(r,n)->new Balance(new StatementDefinition.Account(r.getObject("id",UUID.class),r.getString("code"),r.getString("name"),r.getString("type"),r.getString("purpose")),r.getBigDecimal("opening"),r.getBigDecimal("debit"),r.getBigDecimal("credit"),r.getBigDecimal("closing")),from,from,from,institution,branch,through,cutoff,institution);
    }
    public UUID save(String institution,UUID actor,UUID template,StatementDefinition definition,String evidence,OffsetDateTime now) {
        int version=1;
        if(template==null){template=UUID.randomUUID();jdbc.update("insert into financial_statement_templates(id,sacco_id,made_by,made_at) values(?,?,?,?)",template,institution,actor,now);}
        else {var owners=jdbc.queryForList("select made_by from financial_statement_templates where id=? and sacco_id=? for update",UUID.class,template,institution);if(owners.size()!=1 || !owners.getFirst().equals(actor))throw new org.springframework.security.access.AccessDeniedException("Statement creator required");version=jdbc.queryForObject("select coalesce(max(version),0)+1 from financial_statement_versions where template_id=?",Integer.class,template);}
        UUID id=UUID.randomUUID();jdbc.update("insert into financial_statement_versions(id,template_id,sacco_id,version,definition,made_by,made_at,evidence) values(?,?,?,?,?,?,?,?)",id,template,institution,version,mapper.writeValueAsString(definition),actor,now,evidence);return id;
    }
    public List<Version> versions(String institution,int page){return jdbc.query("select * from financial_statement_versions where sacco_id=? order by made_at desc,id limit 26 offset ?",(r,n)->version(r),institution,page*25);}
    public List<com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.Period> institutionPeriods(String institution,int page){return jdbc.query("select id,starts_on,ends_on,state from accounting_period where sacco_id=? and state='CLOSED' order by ends_on desc,id limit 26 offset ?",(r,n)->new com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.Period(r.getObject("id",UUID.class),r.getObject("starts_on",LocalDate.class),r.getObject("ends_on",LocalDate.class),r.getString("state")),institution,page*25);}
    public Version version(String institution,UUID id,boolean lock){var rows=jdbc.query("select * from financial_statement_versions where sacco_id=? and id=?"+(lock?" for update":""),(r,n)->version(r),institution,id);if(rows.size()!=1)throw new org.springframework.security.access.AccessDeniedException("Statement unavailable");return rows.getFirst();}
    public Version versionForPublication(String institution,UUID id){var rows=jdbc.query("select * from financial_statement_versions where sacco_id=? and id=? for share",(r,n)->version(r),institution,id);if(rows.size()!=1)throw new org.springframework.security.access.AccessDeniedException("Statement unavailable");return rows.getFirst();}
    public String definitionChecksum(String institution,UUID id){return jdbc.queryForObject("select encode(sha256(convert_to(definition,'UTF8')),'hex') from financial_statement_versions where sacco_id=? and id=?",String.class,institution,id);}
    public void approve(String institution,UUID id,UUID checker,String evidence,OffsetDateTime now){jdbc.update("update financial_statement_versions set state='APPROVED',checked_by=?,checked_at=?,review_evidence=? where sacco_id=? and id=? and state='DRAFT'",checker,now,evidence,institution,id);}
    public void retire(String institution,UUID id){jdbc.update("update financial_statement_versions set state='RETIRED' where sacco_id=? and id=? and state='APPROVED'",institution,id);}
    public UUID freeze(String institution,String branch,UUID version,UUID close,UUID comparison,UUID priorResult,String json,String checksum,UUID actor,OffsetDateTime now){
        jdbc.queryForList("select pg_advisory_xact_lock(hashtextextended(?,0))","STATEMENT/"+institution+"/"+branch+"/"+version+"/"+close+"/"+comparison);
        var prior=jdbc.queryForList("select id,prior_result_id from financial_statement_results where sacco_id=? and station_id=? and version_id=? and close_review_id=? and comparison_close_id is not distinct from ?",institution,branch,version,close,comparison);if(!prior.isEmpty()){StatementDefinition.require(Objects.equals(prior.getFirst().get("prior_result_id"),priorResult),"changedRetry");return (UUID)prior.getFirst().get("id");}
        UUID id=UUID.randomUUID();jdbc.update("insert into financial_statement_results(id,sacco_id,station_id,version_id,close_review_id,comparison_close_id,prior_result_id,result_json,checksum,made_by,made_at) values(?,?,?,?,?,?,?,?,?,?,?)",id,institution,branch,version,close,comparison,priorResult,json,checksum,actor,now);return id;
    }
    public StoredResult stored(String institution,String branch,UUID id){var rows=jdbc.query("select * from financial_statement_results where sacco_id=? and (station_id=? or dimension='INSTITUTION') and id=?",(r,n)->new StoredResult(r.getObject("id",UUID.class),r.getString("sacco_id"),r.getString("station_id"),r.getString("result_json"),r.getString("checksum")),institution,branch,id);if(rows.size()!=1)throw new org.springframework.security.access.AccessDeniedException("Statement result unavailable");return rows.getFirst();}
    public UUID retainInstitutionSource(String institution,UUID period,String json,String checksum,String branches,UUID actor,OffsetDateTime now){UUID id=UUID.randomUUID();jdbc.update("insert into financial_statement_institution_sources(id,sacco_id,period_id,source_json,checksum,branches_json,made_by,made_at) values(?,?,?,?,?,?,?,?) on conflict(sacco_id,period_id,checksum) do nothing",id,institution,period,json,checksum,branches,actor,now);return jdbc.queryForObject("select id from financial_statement_institution_sources where sacco_id=? and period_id=? and checksum=?",UUID.class,institution,period,checksum);}
    public String institutionSource(String institution,UUID period,String checksum){return jdbc.queryForObject("select source_json from financial_statement_institution_sources where sacco_id=? and period_id=? and checksum=?",String.class,institution,period,checksum);}
    public boolean hasEarlierInstitutionResult(String institution,UUID template,UUID period,String checksum){return Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from financial_statement_results r join financial_statement_versions v on v.id=r.version_id join financial_statement_institution_sources s on s.id=r.institution_source_id where r.sacco_id=? and v.template_id=? and s.period_id=? and s.checksum<>?)",Boolean.class,institution,template,period,checksum));}
    public UUID freezeInstitution(String institution,String issuer,UUID version,UUID source,UUID comparison,UUID priorResult,String json,String checksum,UUID actor,OffsetDateTime now){jdbc.queryForList("select pg_advisory_xact_lock(hashtextextended(?,0))","STATEMENT/"+institution+"/INSTITUTION/"+version+"/"+source+"/"+comparison);var prior=jdbc.queryForList("select id,prior_result_id from financial_statement_results where sacco_id=? and dimension='INSTITUTION' and version_id=? and institution_source_id=? and comparison_institution_source_id is not distinct from ?",institution,version,source,comparison);if(!prior.isEmpty()){StatementDefinition.require(Objects.equals(prior.getFirst().get("prior_result_id"),priorResult),"changedRetry");return (UUID)prior.getFirst().get("id");}UUID id=UUID.randomUUID();jdbc.update("insert into financial_statement_results(id,sacco_id,station_id,version_id,dimension,institution_source_id,comparison_institution_source_id,prior_result_id,result_json,checksum,made_by,made_at) values(?,?,?,?,'INSTITUTION',?,?,?,?,?,?,?)",id,institution,issuer,version,source,comparison,priorResult,json,checksum,actor,now);return id;}
    public boolean hasEarlierResult(String institution,String branch,UUID template,LocalDate from,LocalDate through,UUID close){return Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from financial_statement_results r join financial_statement_versions v on v.id=r.version_id where r.sacco_id=? and r.station_id=? and v.template_id=? and r.close_review_id<>? and r.result_json::jsonb->>'from'=? and r.result_json::jsonb->>'through'=?)",Boolean.class,institution,branch,template,close,from.toString(),through.toString()));}
    public List<OfficialFormat> formats(){return jdbc.query("select * from regulatory_statement_formats order by format_key,version limit 101",(r,n)->format(r));}
    public OfficialFormat format(UUID id){var rows=jdbc.query("select * from regulatory_statement_formats where id=?",(r,n)->format(r),id);if(rows.size()!=1)throw new IllegalArgumentException("statement.error.officialUnavailable");return rows.getFirst();}
    public void installOfficial(UUID id,String authority,String key,String version,String json,String checksum,String reference,String evidence,OffsetDateTime now){
        var existing=jdbc.queryForList("select checksum from regulatory_statement_formats where format_key=? and version=?",String.class,key,version);
        if(!existing.isEmpty()){StatementDefinition.require(existing.getFirst().equals(checksum),"officialVersion");return;}
        jdbc.update("insert into regulatory_statement_formats(id,authority,format_key,version,format_json,checksum,official_reference,applicability_evidence,registered_at) values(?,?,?,?,?,?,?,?,?)",id,authority,key,version,json,checksum,reference,evidence,now);
    }
    public UUID submit(String institution,String branch,UUID format,UUID result,LocalDate from,LocalDate through,LocalDate deadline,String file,String checksum,byte[] bytes,String evidence,UUID corrects,UUID maker,OffsetDateTime now){UUID id=UUID.randomUUID();jdbc.update("insert into regulatory_statement_submissions(id,sacco_id,station_id,format_id,result_id,period_from,period_through,deadline,file_reference,file_checksum,file_bytes,validation_evidence,corrections_id,made_by,made_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,institution,branch,format,result,from,through,deadline,file,checksum,bytes,evidence,corrects,maker,now);return id;}
    public byte[] submissionFile(String institution,String branch,UUID id){return jdbc.queryForObject("select file_bytes from regulatory_statement_submissions where sacco_id=? and station_id=? and id=?",byte[].class,institution,branch,id);}
    public Submission submission(String institution,String branch,UUID id,boolean lock){var rows=jdbc.query("select s.*,r.checker_id,r.evidence review_evidence from regulatory_statement_submissions s left join regulatory_statement_reviews r on r.submission_id=s.id where s.sacco_id=? and s.station_id=? and s.id=?"+(lock?" for update of s":""),(r,n)->submission(r),institution,branch,id);if(rows.size()!=1)throw new org.springframework.security.access.AccessDeniedException("Submission unavailable");return rows.getFirst();}
    public List<Submission> submissions(String institution,String branch,int page){return jdbc.query("select s.*,r.checker_id,r.evidence review_evidence from regulatory_statement_submissions s left join regulatory_statement_reviews r on r.submission_id=s.id where s.sacco_id=? and s.station_id=? order by s.made_at desc,s.id limit 26 offset ?",(r,n)->submission(r),institution,branch,page*25);}
    public void reviewSubmission(String institution,UUID id,UUID checker,String evidence,OffsetDateTime now){jdbc.update("insert into regulatory_statement_reviews(submission_id,sacco_id,checker_id,evidence,decided_at) values(?,?,?,?,?)",id,institution,checker,evidence,now);}
    public boolean hasInstitutionHistory(String institution){return Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from financial_statement_templates where sacco_id=?) or exists(select 1 from regulatory_statement_submissions where sacco_id=?)",Boolean.class,institution,institution));}
    public boolean hasMemberHistory(UUID id){return Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from financial_statement_versions where made_by=? or checked_by=?) or exists(select 1 from financial_statement_results where made_by=?) or exists(select 1 from regulatory_statement_submissions where made_by=?) or exists(select 1 from regulatory_statement_reviews where checker_id=?)",Boolean.class,id,id,id,id,id));}
    private Version version(ResultSet r)throws SQLException{return new Version(r.getObject("id",UUID.class),r.getObject("template_id",UUID.class),r.getInt("version"),r.getString("state"),r.getObject("made_by",UUID.class),r.getObject("checked_by",UUID.class),r.getString("evidence"),r.getString("review_evidence"),mapper.readValue(r.getString("definition"),StatementDefinition.class));}
    private OfficialFormat format(ResultSet r)throws SQLException{return new OfficialFormat(r.getObject("id",UUID.class),r.getString("authority"),r.getString("format_key"),r.getString("version"),r.getString("format_json"),r.getString("checksum"),r.getString("official_reference"));}
    private Submission submission(ResultSet r)throws SQLException{return new Submission(r.getObject("id",UUID.class),r.getObject("format_id",UUID.class),r.getObject("result_id",UUID.class),r.getObject("period_from",LocalDate.class),r.getObject("period_through",LocalDate.class),r.getObject("deadline",LocalDate.class),r.getString("file_reference"),r.getString("file_checksum"),r.getString("validation_evidence"),r.getObject("corrections_id",UUID.class),r.getObject("made_by",UUID.class),r.getObject("checker_id",UUID.class),r.getString("review_evidence"));}
}
