package com.sacco.mvp.accounting.statements;

import com.sacco.mvp.accounting.policy.AccountingPolicyService;
import com.sacco.mvp.accounting.service.GeneralLedgerService;
import com.sacco.mvp.accounting.reconciliation.ReconciliationService;
import com.sacco.mvp.domain.*;
import com.sacco.mvp.security.AppUserPrincipal;
import com.sacco.mvp.service.*;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.*;
import tools.jackson.databind.ObjectMapper;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.*;
import java.util.*;
import static com.sacco.mvp.accounting.statements.StatementDefinition.*;
import static com.sacco.mvp.accounting.statements.StatementRepository.*;

@Service @RequiredArgsConstructor
public class StatementDesignerService {
    private final StatementRepository repository;
    private final AccountingPolicyService policies;
    private final GeneralLedgerService ledger;
    private final ReconciliationService closing;
    private final RegulatoryFormatCatalog official;
    private final AccessControlService access;
    private final MemberDirectoryService members;
    private final UserClaimService claims;
    private final SaccoRegistryService institutions;
    private final ApplicationClock clock;
    private final AuditService audit;
    private final ObjectMapper mapper;
    private final List<StatementMappingChangeListener> mappingChangeListeners;
    public record RowValue(String id,String labelEn,String labelSw,RowKind kind,Unit unit,BigDecimal current,
            BigDecimal comparison,String status,String comparisonStatus,boolean visible,boolean collapsed,boolean mandatory,String noteEn,String noteSw) { }
    public record BranchSource(String branch,UUID reviewId,int version,OffsetDateTime recordedCutoff,String checksum,UUID reviewer) { }
    public record Result(UUID id,UUID versionId,UUID templateId,int mappingVersion,int calculationVersion,StatementDefinition definition,
            String institution,String branch,LocalDate from,LocalDate through,LocalDate comparisonFrom,LocalDate comparisonThrough,
            OffsetDateTime recordedCutoff,OffsetDateTime comparisonCutoff,UUID policyId,int policyVersion,UUID closeReviewId,
            String closeChecksum,UUID comparisonCloseId,String comparisonCloseChecksum,String coverage,String status,
            List<RowValue> rows,Map<String,BigDecimal> reconciliations,List<String> disclosures,UUID mappingReviewer,String mappingApprovalEvidence,OffsetDateTime generatedAt,UUID priorResultId,
            RegulatoryFormatCatalog.Scope dimension,List<BranchSource> currentBranchSources,List<BranchSource> comparisonBranchSources,
            UUID institutionPeriodId,UUID comparisonInstitutionPeriodId,String institutionSourceChecksum,String comparisonInstitutionSourceChecksum) {
        public Result { rows=List.copyOf(rows);reconciliations=Collections.unmodifiableMap(new LinkedHashMap<>(reconciliations));disclosures=List.copyOf(disclosures);dimension=dimension==null?RegulatoryFormatCatalog.Scope.BRANCH:dimension;currentBranchSources=currentBranchSources==null?List.of():List.copyOf(currentBranchSources);comparisonBranchSources=comparisonBranchSources==null?List.of():List.copyOf(comparisonBranchSources); }
        public Result(UUID id,UUID versionId,UUID templateId,int mappingVersion,int calculationVersion,StatementDefinition definition,String institution,String branch,LocalDate from,LocalDate through,LocalDate comparisonFrom,LocalDate comparisonThrough,OffsetDateTime recordedCutoff,OffsetDateTime comparisonCutoff,UUID policyId,int policyVersion,UUID closeReviewId,String closeChecksum,UUID comparisonCloseId,String comparisonCloseChecksum,String coverage,String status,List<RowValue> rows,Map<String,BigDecimal> reconciliations,List<String> disclosures,UUID mappingReviewer,String mappingApprovalEvidence,OffsetDateTime generatedAt,UUID priorResultId){this(id,versionId,templateId,mappingVersion,calculationVersion,definition,institution,branch,from,through,comparisonFrom,comparisonThrough,recordedCutoff,comparisonCutoff,policyId,policyVersion,closeReviewId,closeChecksum,comparisonCloseId,comparisonCloseChecksum,coverage,status,rows,reconciliations,disclosures,mappingReviewer,mappingApprovalEvidence,generatedAt,priorResultId,RegulatoryFormatCatalog.Scope.BRANCH,List.of(),List.of(),null,null,null,null);}
        @com.fasterxml.jackson.annotation.JsonIgnore public List<RowValue> getVisibleRows(){return rows.stream().filter(r->r.visible() || r.mandatory()).toList();}
        Result withId(UUID id){return copy(id,priorResultId);}
        Result withHistory(UUID prior){return copy(id,prior);}
        private Result copy(UUID id,UUID prior){return new Result(id,versionId,templateId,mappingVersion,calculationVersion,definition,institution,branch,from,through,comparisonFrom,comparisonThrough,recordedCutoff,comparisonCutoff,policyId,policyVersion,closeReviewId,closeChecksum,comparisonCloseId,comparisonCloseChecksum,coverage,status,rows,reconciliations,disclosures,mappingReviewer,mappingApprovalEvidence,generatedAt,prior,dimension,currentBranchSources,comparisonBranchSources,institutionPeriodId,comparisonInstitutionPeriodId,institutionSourceChecksum,comparisonInstitutionSourceChecksum);}
        Result institutionSource(UUID period,String checksum,List<BranchSource> current,UUID comparePeriod,String compareChecksum,List<BranchSource> compare){var requiredRows=new ArrayList<RowValue>(rows);requiredRows.add(new RowValue("INSTITUTION_SOURCE","Institution source","Chanzo cha taasisi",RowKind.NOTE,Unit.NONE,null,null,"TEXT","TEXT",true,false,true,period+"; SHA256="+checksum,period+"; SHA256="+checksum));sourceRows(requiredRows,current,"CURRENT");sourceRows(requiredRows,compare,"COMPARISON");return new Result(id,versionId,templateId,mappingVersion,calculationVersion,definition,institution,branch,from,through,comparisonFrom,comparisonThrough,recordedCutoff,comparisonCutoff,policyId,policyVersion,null,null,null,null,coverage,status,requiredRows,reconciliations,disclosures,mappingReviewer,mappingApprovalEvidence,generatedAt,priorResultId,RegulatoryFormatCatalog.Scope.INSTITUTION,current,compare,period,comparePeriod,checksum,compareChecksum);}
        private static void sourceRows(List<RowValue> rows,List<BranchSource> sources,String kind){for(var b:sources){String evidence=b.branch()+"; close="+b.reviewId()+"; version="+b.version()+"; recordedCutoff="+b.recordedCutoff()+"; reviewer="+b.reviewer()+"; SHA256="+b.checksum();rows.add(new RowValue("BRANCH_SOURCE_"+kind+"_"+b.reviewId(),kind.equals("CURRENT")?"Current branch source":"Comparative branch source",kind.equals("CURRENT")?"Chanzo cha tawi cha sasa":"Chanzo cha tawi cha ulinganisho",RowKind.NOTE,Unit.NONE,null,null,"TEXT","TEXT",true,false,true,evidence,evidence));}}
    }
    private record Source(LocalDate from,LocalDate through,OffsetDateTime cutoff,UUID closeId,String checksum,
            UUID policyId,int policyVersion,List<Balance> balances,List<Map<String,Object>> cashMovements,Map<String,Object> cashTransfers,List<String> disclosures,String reportingFramework,Map<String,Object> frozen) { }
    public record MappingApproval(UUID id,UUID templateId,int version,UUID reviewer,String evidence,String state,String definitionChecksum) { }

    @Transactional public UUID save(AppUserPrincipal actor,UUID template,StatementDefinition definition,String evidence){
        actor=authorize(actor,UserClaim.STATEMENT_DESIGN);text(evidence,1000);require(definition.kind()!=Kind.CASH_FLOW || definition.calculationVersion()==2,"cashVersion");definition.validateMappings(catalog(actor));
        UUID id=repository.save(actor.getSaccoId(),actor.getMemberId(),template,definition,evidence,clock.now());event(actor,id,"DESIGNED");return id;
    }
    @Transactional public void approve(AppUserPrincipal actor,UUID id,String evidence){
        actor=authorize(actor,UserClaim.STATEMENT_APPROVE);text(evidence,1000);Version v=repository.version(actor.getSaccoId(),id,true);
        require(!v.maker().equals(actor.getMemberId()),"checker");require(v.state().equals("DRAFT"),"state");require(v.definition().kind()!=Kind.CASH_FLOW || v.definition().calculationVersion()==2,"cashVersion");v.definition().validateMappings(catalog(actor));
        repository.approve(actor.getSaccoId(),id,actor.getMemberId(),evidence,clock.now());event(actor,id,"MAPPING_APPROVED");
        for(var listener:mappingChangeListeners)listener.mappingChanged(actor,v.template(),id,"MAPPING_APPROVED");
    }
    @Transactional public void retire(AppUserPrincipal actor,UUID id){actor=authorize(actor,UserClaim.STATEMENT_APPROVE);Version v=repository.version(actor.getSaccoId(),id,true);require(v.state().equals("APPROVED"),"state");repository.retire(actor.getSaccoId(),id);event(actor,id,"RETIRED");for(var listener:mappingChangeListeners)listener.mappingChanged(actor,v.template(),id,"RETIRED");}
    @Transactional(readOnly=true) public List<Version> versions(AppUserPrincipal actor,int page){actor=authorizeAny(actor,UserClaim.STATEMENT_VIEW,UserClaim.STATEMENT_DESIGN,UserClaim.STATEMENT_APPROVE);page(page);return repository.versions(actor.getSaccoId(),page);}
    @Transactional(readOnly=true) public Version version(AppUserPrincipal actor,UUID id){actor=authorizeAny(actor,UserClaim.STATEMENT_VIEW,UserClaim.STATEMENT_DESIGN,UserClaim.STATEMENT_APPROVE);return repository.version(actor.getSaccoId(),id,false);}
    @Transactional(readOnly=true) public List<Account> catalog(AppUserPrincipal actor){authorizeAny(actor,UserClaim.STATEMENT_VIEW,UserClaim.STATEMENT_DESIGN,UserClaim.STATEMENT_APPROVE);var accounts=repository.accounts(actor.getSaccoId());require(accounts.size()<=1000,"size");return accounts;}

    @Transactional(isolation=Isolation.REPEATABLE_READ,timeout=20)
    public Result preview(AppUserPrincipal actor,UUID id,LocalDate from,LocalDate through,LocalDate compareFrom,LocalDate compareThrough,OffsetDateTime cutoff){
        actor=authorize(actor,UserClaim.STATEMENT_VIEW);dates(from,through);require(cutoff!=null && !cutoff.isAfter(clock.now()),"dates");Version v=repository.version(actor.getSaccoId(),id,false);
        var policy=policies.requireApprovedLocalPolicy(actor.getSaccoId(),through);require(!from.isBefore(policy.openingDate()) && policy.approvedAt()!=null && !policy.approvedAt().isAfter(cutoff),"policy");var coverage=ledger.coverage(actor);
        var balances=repository.balances(actor.getSaccoId(),actor.getStationId(),from,through,cutoff);require(balances.size()<=1000,"size");
        String coverageStatus=coverage.reviewedOpening() && repository.openingAvailable(actor.getSaccoId(),actor.getStationId(),through,cutoff)?coverage.status():"INCOMPLETE_NOT_AUTHORITATIVE";
        Source current=new Source(from,through,cutoff,null,null,policy.id(),policy.version(),balances,List.of(),Map.of(),List.of(coverageStatus),policy.decisions().get(com.sacco.mvp.accounting.policy.PolicyDecision.REPORTING_FRAMEWORK),Map.of());Source comparison=null;
        if(v.definition().comparison()){dates(compareFrom,compareThrough);var comparisonPolicy=policies.requireApprovedLocalPolicy(actor.getSaccoId(),compareThrough);require(compareThrough.isBefore(from) && !compareFrom.isBefore(comparisonPolicy.openingDate()) && comparisonPolicy.approvedAt()!=null && !comparisonPolicy.approvedAt().isAfter(cutoff),"dates");String comparisonCoverage=repository.openingAvailable(actor.getSaccoId(),actor.getStationId(),compareThrough,cutoff)?coverage.status():"INCOMPLETE_NOT_AUTHORITATIVE";comparison=new Source(compareFrom,compareThrough,cutoff,null,null,comparisonPolicy.id(),comparisonPolicy.version(),repository.balances(actor.getSaccoId(),actor.getStationId(),compareFrom,compareThrough,cutoff),List.of(),Map.of(),List.of(comparisonCoverage),comparisonPolicy.decisions().get(com.sacco.mvp.accounting.policy.PolicyDecision.REPORTING_FRAMEWORK),Map.of());}
        Result result=render(v,actor,current,comparison,false);event(actor,id,"PREVIEWED");return result;
    }
    // Sources are immutable reviewed close snapshots; READ_COMMITTED makes a waiting duplicate observe the first retained result.
    @Transactional(timeout=30)
    public UUID finalize(AppUserPrincipal actor,UUID versionId,UUID closeReviewId,UUID comparisonCloseId){
        return finalize(actor,versionId,closeReviewId,comparisonCloseId,null);
    }
    @Transactional(timeout=30)
    public UUID finalize(AppUserPrincipal actor,UUID versionId,UUID closeReviewId,UUID comparisonCloseId,UUID priorResultId){
        actor=authorize(actor,UserClaim.STATEMENT_FINALIZE);verifiedVersionForPublication(actor,versionId);Version v=repository.version(actor.getSaccoId(),versionId,false);
        Source current=closed(actor,closeReviewId);Source comparison=null;
        if(v.definition().comparison()){require(comparisonCloseId!=null,"comparison");comparison=closed(actor,comparisonCloseId);require(comparison.through().isBefore(current.from()),"dates");require(!comparison.cutoff().isAfter(current.cutoff()),"comparisonEvidence");}
        else require(comparisonCloseId==null,"comparison");
        if(current.disclosures().contains("RESTATEMENT") && repository.hasEarlierResult(actor.getSaccoId(),actor.getStationId(),v.template(),current.from(),current.through(),current.closeId()))require(priorResultId!=null,"restatement");
        if(priorResultId!=null){Result prior=verifiedResult(actor,priorResultId);require(prior.dimension()==RegulatoryFormatCatalog.Scope.BRANCH && current.disclosures().contains("RESTATEMENT") && prior.templateId().equals(v.template()) && prior.definition().kind()==v.definition().kind() && prior.from().equals(current.from()) && prior.through().equals(current.through()) && !prior.closeReviewId().equals(current.closeId()),"restatement");}
        Result result=render(v,actor,current,comparison,true).withHistory(priorResultId);String json=mapper.writeValueAsString(result);require(json.length()<=1000000,"size");
        UUID id=repository.freeze(actor.getSaccoId(),actor.getStationId(),versionId,closeReviewId,comparisonCloseId,priorResultId,json,sha(json.getBytes(StandardCharsets.UTF_8)),actor.getMemberId(),clock.now());event(actor,id,"FINALIZED");return id;
    }
    @Transactional(timeout=30)
    public UUID finalizeInstitution(AppUserPrincipal actor,UUID versionId,UUID periodId,UUID comparisonPeriodId,UUID priorResultId){
        actor=authorizeInstitution(authorize(actor,UserClaim.STATEMENT_FINALIZE));verifiedVersionForPublication(actor,versionId);Version v=repository.version(actor.getSaccoId(),versionId,false);
        var current=closing.finalizedInstitutionSnapshotForPublication(actor,periodId);var currentSource=institutionSource(actor,current);
        com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.InstitutionSnapshot comparison=null;Source priorSource=null;
        if(v.definition().comparison()){require(comparisonPeriodId!=null,"comparison");comparison=closing.finalizedInstitutionSnapshotForPublication(actor,comparisonPeriodId);priorSource=institutionSource(actor,comparison);require(comparison.through().isBefore(current.from()),"dates");require(!latest(comparison.branches()).isAfter(earliest(current.branches())),"comparisonEvidence");}else require(comparisonPeriodId==null,"comparison");
        if(current.restated() && repository.hasEarlierInstitutionResult(actor.getSaccoId(),v.template(),periodId,current.checksum()))require(priorResultId!=null,"restatement");
        if(priorResultId!=null){Result prior=verifiedResult(actor,priorResultId);require(current.restated() && prior.dimension()==RegulatoryFormatCatalog.Scope.INSTITUTION && prior.templateId().equals(v.template()) && prior.definition().kind()==v.definition().kind() && periodId.equals(prior.institutionPeriodId()) && !current.checksum().equals(prior.institutionSourceChecksum()),"restatement");}
        var currentLineage=lineage(current.branches());var compareLineage=comparison==null?List.<BranchSource>of():lineage(comparison.branches());
        Result result=render(v,actor,currentSource,priorSource,true).withHistory(priorResultId).institutionSource(periodId,current.checksum(),currentLineage,comparisonPeriodId,comparison==null?null:comparison.checksum(),compareLineage);
        String json=mapper.writeValueAsString(result);require(json.length()<=1000000,"size");UUID source=repository.retainInstitutionSource(actor.getSaccoId(),periodId,current.snapshot(),current.checksum(),mapper.writeValueAsString(currentLineage),actor.getMemberId(),clock.now());UUID comparisonSource=comparison==null?null:repository.retainInstitutionSource(actor.getSaccoId(),comparisonPeriodId,comparison.snapshot(),comparison.checksum(),mapper.writeValueAsString(compareLineage),actor.getMemberId(),clock.now());
        UUID id=repository.freezeInstitution(actor.getSaccoId(),actor.getStationId(),versionId,source,comparisonSource,priorResultId,json,sha(json.getBytes(StandardCharsets.UTF_8)),actor.getMemberId(),clock.now());event(actor,id,"FINALIZED_INSTITUTION");return id;
    }
    /** H captures only this immutable authoritative result; it never accepts submitted amounts or coverage flags. */
    @Transactional public Result verifiedResult(AppUserPrincipal actor,UUID id){
        actor=authorize(actor,UserClaim.STATEMENT_VIEW);StoredResult stored=repository.stored(actor.getSaccoId(),actor.getStationId(),id);require(sha(stored.json().getBytes(StandardCharsets.UTF_8)).equals(stored.checksum()),"checksum");
        Result result=mapper.readValue(stored.json(),Result.class);require(result.status().equals("FINAL"),"unapproved");require(result.institution().equals(actor.getSaccoId()),"scope");
        if(result.dimension()==RegulatoryFormatCatalog.Scope.INSTITUTION){authorizeInstitution(actor);require(result.closeReviewId()==null && result.comparisonCloseId()==null && result.institutionPeriodId()!=null && result.institutionSourceChecksum()!=null && !result.currentBranchSources().isEmpty(),"source");String source=repository.institutionSource(actor.getSaccoId(),result.institutionPeriodId(),result.institutionSourceChecksum());require(sha(source.getBytes(StandardCharsets.UTF_8)).equals(result.institutionSourceChecksum()),"checksum");if(result.comparisonInstitutionPeriodId()!=null){String prior=repository.institutionSource(actor.getSaccoId(),result.comparisonInstitutionPeriodId(),result.comparisonInstitutionSourceChecksum());require(sha(prior.getBytes(StandardCharsets.UTF_8)).equals(result.comparisonInstitutionSourceChecksum()),"checksum");}}
        else require(result.closeReviewId()!=null && result.closeChecksum()!=null && result.branch().equals(actor.getStationId()),"scope");event(actor,id,"VIEWED_FINAL");return result.withId(id);
    }
    @Transactional public String verifiedResultDigest(AppUserPrincipal actor,UUID id){verifiedResult(actor,id);return repository.stored(actor.getSaccoId(),actor.getStationId(),id).checksum();}
    public AppUserPrincipal authorizeExport(AppUserPrincipal actor){AppUserPrincipal current=authorize(actor,UserClaim.STATEMENT_VIEW);return authorize(current,UserClaim.STATEMENT_EXPORT);}
    @Transactional(propagation=Propagation.MANDATORY)
    public MappingApproval verifiedVersionForPublication(AppUserPrincipal actor,UUID versionId){actor=authorize(actor,UserClaim.STATEMENT_VIEW);Version v=repository.versionForPublication(actor.getSaccoId(),versionId);require(v.state().equals("APPROVED") && v.checker()!=null && !v.checker().equals(v.maker()) && v.reviewEvidence()!=null && !v.reviewEvidence().isBlank(),"unapproved");v.definition().validate();require(v.definition().kind()!=Kind.CASH_FLOW || v.definition().calculationVersion()==2,"cashVersion");return new MappingApproval(v.id(),v.template(),v.version(),v.checker(),v.reviewEvidence(),v.state(),repository.definitionChecksum(actor.getSaccoId(),versionId));}
    /** Revalidates current D evidence and pins mapping/period locks for H publication. */
    @Transactional(propagation=Propagation.MANDATORY)
    public Result verifiedResultForPublication(AppUserPrincipal actor,UUID id){Result result=verifiedResult(actor,id);requireCurrentPublication(actor,result);return result;}
    public AppUserPrincipal authorizeInstitution(AppUserPrincipal actor){actor=authorize(actor,UserClaim.FINANCIAL_REPORTS_INSTITUTION);return authorize(actor,UserClaim.FINANCIAL_REPORTS_VIEW);}
    private static List<BranchSource> lineage(List<com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.BranchCloseSource> rows){return rows.stream().map(b->new BranchSource(b.branch(),b.reviewId(),b.version(),b.recordedCutoff(),b.checksum(),b.reviewer())).toList();}
    private static OffsetDateTime latest(List<com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.BranchCloseSource> rows){require(!rows.isEmpty(),"source");return rows.stream().map(com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.BranchCloseSource::recordedCutoff).max(OffsetDateTime.timeLineOrder()).orElseThrow();}
    private static OffsetDateTime earliest(List<com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.BranchCloseSource> rows){require(!rows.isEmpty(),"source");return rows.stream().map(com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.BranchCloseSource::recordedCutoff).min(OffsetDateTime.timeLineOrder()).orElseThrow();}
    @SuppressWarnings("unchecked") private Source institutionSource(AppUserPrincipal actor,com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.InstitutionSnapshot source){
        require(source.periodClosed() && source.dimension().equals("INSTITUTION") && source.institution().equals(actor.getSaccoId()) && source.checksum().equals(sha(source.snapshot().getBytes(StandardCharsets.UTF_8))),"source");
        Map<String,Object> data=mapper.readerFor(Map.class).with(tools.jackson.databind.DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS).readValue(source.snapshot());require(source.branches().size()<=1000 && !source.branches().isEmpty(),"size");var accounts=(List<Map<String,Object>>)data.get("accounts");require(accounts!=null && accounts.size()<=1000,"source");var balances=new ArrayList<Balance>();for(var a:accounts)balances.add(new Balance(new Account(UUID.fromString(a.get("id").toString()),a.get("code").toString(),a.get("code").toString(),a.get("type").toString(),a.get("purpose").toString()),decimal(a.get("opening")),decimal(a.get("period_debit")),decimal(a.get("period_credit")),decimal(a.get("closing"))));
        var p=(Map<String,Object>)data.get("accountingPolicy");require(p!=null && p.get("id")!=null && p.get("effective_from")!=null,"policy");var policy=policies.requireApprovedLocalPolicy(actor.getSaccoId(),LocalDate.parse(p.get("effective_from").toString()));require(policy.id().toString().equals(p.get("id").toString()) && policy.version()==Integer.parseInt(p.get("policy_version").toString()),"policy");
        var disclosures=new ArrayList<String>();disclosures.add(data.get("coverage").toString());if(source.restated())disclosures.add("RESTATEMENT");
        return new Source(source.from(),source.through(),latest(source.branches()),null,source.checksum(),policy.id(),policy.version(),List.copyOf(balances),List.of(),(Map<String,Object>)data.get("cashTransfers"),List.copyOf(disclosures),policy.decisions().get(com.sacco.mvp.accounting.policy.PolicyDecision.REPORTING_FRAMEWORK),data);
    }
    @SuppressWarnings("unchecked") private Source closed(AppUserPrincipal actor,UUID id){
        require(id!=null,"close");var close=closing.finalizedSnapshotForPublication(actor,id);require(close.periodClosed(),"close");require(close.checksum().equals(sha(close.snapshot().getBytes(StandardCharsets.UTF_8))),"checksum");
        Map<String,Object> snapshot=mapper.readerFor(Map.class).with(tools.jackson.databind.DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS).readValue(close.snapshot());var accountRows=(List<Map<String,Object>>)snapshot.get("accounts");require(accountRows!=null && accountRows.size()<=1000,"source");var balances=new ArrayList<Balance>();
        for(var a:accountRows){require(a.get("id")!=null && a.get("type")!=null && a.get("closing")!=null && a.get("opening")!=null && a.get("period_debit")!=null && a.get("period_credit")!=null,"source");balances.add(new Balance(new Account(UUID.fromString(a.get("id").toString()),a.get("code").toString(),a.get("code").toString(),a.get("type").toString(),a.get("purpose").toString()),decimal(a.get("opening")),decimal(a.get("period_debit")),decimal(a.get("period_credit")),decimal(a.get("closing"))));}
        var policy=(Map<String,Object>)snapshot.get("accountingPolicy");require(policy!=null && policy.get("id")!=null && policy.get("policy_version")!=null && policy.get("effective_from")!=null,"source");
        var applicable=policies.requireApprovedLocalPolicy(actor.getSaccoId(),LocalDate.parse(policy.get("effective_from").toString()));require(applicable.id().toString().equals(policy.get("id").toString()) && applicable.version()==Integer.parseInt(policy.get("policy_version").toString()),"policy");
        var disclosures=new ArrayList<String>();disclosures.add(close.coverage());if(close.restatement())disclosures.add("RESTATEMENT");
        var differences=(List<Map<String,Object>>)snapshot.get("retainedDifferences");if(differences!=null)for(var d:differences)disclosures.add("REVIEWED_DIFFERENCE: "+d.get("kind")+"; "+d.get("review_evidence"));
        return new Source(LocalDate.parse(snapshot.get("from").toString()),close.asOf(),close.recordedCutoff(),close.id(),close.checksum(),applicable.id(),applicable.version(),List.copyOf(balances),(List<Map<String,Object>>)snapshot.getOrDefault("cashMovements",List.of()),(Map<String,Object>)snapshot.getOrDefault("cashTransfers",Map.of()),List.copyOf(disclosures),applicable.decisions().get(com.sacco.mvp.accounting.policy.PolicyDecision.REPORTING_FRAMEWORK),snapshot);
    }
    private Result render(Version version,AppUserPrincipal actor,Source current,Source comparison,boolean finalRequested){
        StatementDefinition d=version.definition();d.validateMappings(current.balances().stream().map(Balance::account).toList());if(comparison!=null)d.validateMappings(comparison.balances().stream().map(Balance::account).toList());
        boolean cashV2=d.kind()==Kind.CASH_FLOW && d.calculationVersion()==2;var cash=cashV2 && finalRequested?cash(d,current):null;var priorCash=cashV2 && finalRequested && comparison!=null?cash(d,comparison):null;
        var source=cashV2?cashAccounts(current,cash):values(d,current,finalRequested);var compare=comparison==null?Map.<UUID,BigDecimal>of():cashV2?cashAccounts(comparison,priorCash):values(d,comparison,finalRequested);var calculated=cashV2?d.calculateCashRows(cash==null?Map.of():cash.rows()):d.calculate(source);var other=comparison==null?Map.<String,Value>of():cashV2?d.calculateCashRows(priorCash==null?Map.of():priorCash.rows()):d.calculate(compare);
        var rows=new ArrayList<RowValue>();for(var r:d.rows()){Value a=calculated.get(r.id()),b=other.get(r.id());rows.add(new RowValue(r.id(),r.labelEn(),r.labelSw(),r.memo()?RowKind.NOTE:r.kind(),r.unit(),a.amount(),b==null?null:b.amount(),a.status(),b==null?"NOT_REQUESTED":b.status(),r.visible(),r.memo()?false:r.collapsed(),r.memo(),r.memo()?memoNote(r.noteEn(),r.exceptionEvidence()):r.noteEn(),r.memo()?memoNote(r.noteSw(),r.exceptionEvidence()):r.noteSw()));}
        var totals=mandatory(d,current);var compareTotals=comparison==null?Map.<String,BigDecimal>of():mandatory(d,comparison);if(cashV2){cashTotals(d,totals,cash);if(comparison!=null)cashTotals(d,compareTotals,priorCash);}
        totals.forEach((key,value)->rows.add(new RowValue("REQUIRED_"+key,key,key,RowKind.SUBTOTAL,Unit.TZS,value,compareTotals.get(key),value==null?"UNAVAILABLE":"KNOWN",comparison==null?"NOT_REQUESTED":compareTotals.get(key)==null?"UNAVAILABLE":"KNOWN",true,false,true,null,null)));
        for(var x:d.exclusions()){Account account=current.balances().stream().map(Balance::account).filter(a->a.id().equals(x.account())).findFirst().orElseThrow();rows.add(new RowValue("EXCLUDED_"+account.code(),account.code()+": "+x.treatmentEn(),account.code()+": "+x.treatmentSw(),RowKind.NOTE,Unit.TZS,source.get(x.account()),compare.get(x.account()),source.get(x.account())==null?"UNAVAILABLE":"KNOWN",comparison==null?"NOT_REQUESTED":"KNOWN",true,false,true,x.evidence(),x.evidence()));}
        if(finalRequested){require(rows.stream().filter(r->r.unit()==Unit.TZS).noneMatch(r->r.current()==null || comparison!=null && r.comparison()==null),"unknown");require(totals.get("RECONCILIATION_DIFFERENCE").signum()==0,"reconciliation");
            if(d.kind()==Kind.CASH_FLOW){BigDecimal classified=cashV2?cash.total():current.cashMovements().stream().map(m->decimal(m.get("counterpart_movement")).negate()).reduce(BigDecimal.ZERO,BigDecimal::add);require(classified.compareTo(totals.get("CASH_MOVEMENT"))==0,"reconciliation");if(priorCash!=null)require(priorCash.total().compareTo(compareTotals.get("CASH_MOVEMENT"))==0,"reconciliation");}}
        if(cashV2){for(var r:d.rows())if(!r.memo() && r.exceptionEvidence()!=null && !r.exceptionEvidence().isBlank())rows.add(new RowValue("CASH_MAPPING_"+r.id(),r.labelEn(),r.labelSw(),RowKind.NOTE,Unit.NONE,null,null,"TEXT","TEXT",true,false,true,r.section()+"; "+r.exceptionEvidence(),r.section()+"; "+r.exceptionEvidence()));if(cash!=null)cashEvidence(rows,cash,"CURRENT");if(priorCash!=null)cashEvidence(rows,priorCash,"COMPARISON");}
        institutionDifference(rows,current,"CURRENT");if(comparison!=null)institutionDifference(rows,comparison,"COMPARISON");
        var disclosures=new ArrayList<String>(current.disclosures());disclosures.add("TZS; POSTED_ENTRIES; EFFECTIVE_DATE; RECORDED_CUTOFF; NOT_AN_AUDIT_OPINION");disclosures.add("ACCOUNTING_BASIS: "+current.reportingFramework());if(comparison!=null)disclosures.add("COMPARISON_POLICY: "+comparison.policyId()+" / "+comparison.policyVersion()+"; "+comparison.reportingFramework());if(d.rows().stream().anyMatch(Row::memo))disclosures.add("MEMO_DISCLOSURES_EXCLUDED_FROM_CALCULATIONS");
        return new Result(null,version.id(),version.template(),version.version(),d.calculationVersion(),d,actor.getSaccoId(),actor.getStationId(),current.from(),current.through(),comparison==null?null:comparison.from(),comparison==null?null:comparison.through(),current.cutoff(),comparison==null?null:comparison.cutoff(),current.policyId(),current.policyVersion(),current.closeId(),current.checksum(),comparison==null?null:comparison.closeId(),comparison==null?null:comparison.checksum(),current.disclosures().getFirst(),finalRequested?"FINAL":"DRAFT",List.copyOf(rows),totals,List.copyOf(disclosures),version.checker(),version.reviewEvidence(),clock.now(),null);
    }
    @SuppressWarnings("unchecked") private StatementCashFlow.Resolved cash(StatementDefinition d,Source s){require(s.frozen().containsKey("automaticCashMovements") && s.frozen().containsKey("cashFlowAllocations"),"cashSource");com.sacco.mvp.accounting.reports.CashFlowAllocation.Coverage coverage=mapper.readerFor(com.sacco.mvp.accounting.reports.CashFlowAllocation.Coverage.class).with(tools.jackson.databind.DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS).readValue(mapper.writeValueAsString(s.frozen().get("cashFlowAllocations")));return StatementCashFlow.resolve(d,(List<Map<String,Object>>)s.frozen().get("automaticCashMovements"),coverage,s.cutoff());}
    private static Map<UUID,BigDecimal> cashAccounts(Source s,StatementCashFlow.Resolved cash){var result=new HashMap<UUID,BigDecimal>();for(var b:s.balances())result.put(b.account().id(),cash==null?null:cash.accounts().getOrDefault(b.account().id(),BigDecimal.ZERO));return result;}
    private static void cashTotals(StatementDefinition d,Map<String,BigDecimal> totals,StatementCashFlow.Resolved cash){for(var activity:List.of(Section.OPERATING,Section.INVESTING,Section.FINANCING))totals.put("CASH_FLOW_"+activity,cash==null?null:d.rows().stream().filter(r->r.kind()==RowKind.ACCOUNT_GROUP && !r.memo() && r.section()==activity).map(r->cash.rows().get(r.id())).reduce(BigDecimal.ZERO,BigDecimal::add));}
    private static void cashEvidence(List<RowValue> rows,StatementCashFlow.Resolved cash,String period){for(var v:cash.versions()){String evidence=period+"; "+v.id()+" / "+v.version()+"; "+v.journalId()+"; "+v.checker()+"; "+v.reviewedAt()+"; "+v.sourceChecksum()+"; "+v.definitionChecksum()+"; INTERNAL_TRANSFER=0.00; "+v.evidence()+"; "+v.reviewEvidence()+"; "+Objects.toString(v.noncashEvidence(),"");rows.add(new RowValue("CASH_ALLOCATION_"+period+"_"+v.id(),"Reviewed cash-flow allocation","Mgao wa mtiririko wa fedha uliopitiwa",RowKind.NOTE,Unit.NONE,null,null,"TEXT","TEXT",true,false,true,evidence,evidence));}}
    private Map<UUID,BigDecimal> values(StatementDefinition d,Source s,boolean finalRequested){
        var values=new HashMap<UUID,BigDecimal>();for(Balance b:s.balances())values.put(b.account().id(),!reviewedSource(s)?null:d.kind()==Kind.PROFIT_AND_LOSS || d.kind()==Kind.CHANGES_IN_EQUITY?b.debit().subtract(b.credit()):b.closing());
        if(d.kind()==Kind.CASH_FLOW){values.clear();for(Balance b:s.balances())values.put(b.account().id(),finalRequested?BigDecimal.ZERO:null);
            if(finalRequested){require(!s.cashTransfers().isEmpty() && s.cashTransfers().containsKey("ambiguous_journals"),"source");require(decimal(s.cashTransfers().get("ambiguous_journals")).signum()==0 && decimal(s.cashTransfers().getOrDefault("net_cash_movement",BigDecimal.ZERO)).signum()==0,"cashAmbiguous");for(var m:s.cashMovements()){require(Integer.parseInt(m.get("money_lines").toString())==1,"cashAmbiguous");UUID account=UUID.fromString(m.get("account_id").toString());values.merge(account,decimal(m.get("counterpart_movement")).negate(),BigDecimal::add);}}}
        return values;
    }
    private Map<String,BigDecimal> mandatory(StatementDefinition d,Source s){
        var totals=new LinkedHashMap<String,BigDecimal>();var purposes=new HashMap<String,BigDecimal>();BigDecimal assets=BigDecimal.ZERO,liabilities=BigDecimal.ZERO,equity=BigDecimal.ZERO,income=BigDecimal.ZERO,expenses=BigDecimal.ZERO,openingEquity=BigDecimal.ZERO,cashOpening=BigDecimal.ZERO,cashClosing=BigDecimal.ZERO;
        for(Balance b:s.balances()) {switch(b.account().type()){case "ASSET"->assets=assets.add(b.closing());case "LIABILITY"->liabilities=liabilities.subtract(b.closing());case "EQUITY"->{equity=equity.subtract(b.closing());openingEquity=openingEquity.subtract(b.opening());}case "INCOME"->{income=income.add(b.credit().subtract(b.debit()));equity=equity.subtract(b.closing());openingEquity=openingEquity.subtract(b.opening());}case "EXPENSE"->{expenses=expenses.add(b.debit().subtract(b.credit()));equity=equity.subtract(b.closing());openingEquity=openingEquity.subtract(b.opening());}default->throw new IllegalArgumentException("statement.error.source");}
            purposes.merge(b.account().purpose(),b.closing(),BigDecimal::add);
            if(Set.of("CASH","BANK","MOBILE_MONEY").contains(b.account().purpose())){cashOpening=cashOpening.add(b.opening());cashClosing=cashClosing.add(b.closing());}}
        totals.put("ASSETS",assets);totals.put("LIABILITIES",liabilities);totals.put("EQUITY",equity);totals.put("INCOME",income);totals.put("EXPENSES",expenses);totals.put("PROFIT",income.subtract(expenses));totals.put("OPENING_EQUITY",openingEquity);totals.put("EQUITY_MOVEMENT",equity.subtract(openingEquity));totals.put("CASH_OPENING",cashOpening);totals.put("CASH_CLOSING",cashClosing);totals.put("CASH_MOVEMENT",cashClosing.subtract(cashOpening));totals.put("RECONCILIATION_DIFFERENCE",assets.subtract(liabilities).subtract(equity));
        for(String key:List.of("LOAN_PRINCIPAL","INTEREST_RECEIVABLE","FEE_RECEIVABLE","CASH","BANK","MOBILE_MONEY"))totals.put(key,purposes.getOrDefault(key,BigDecimal.ZERO));
        for(String key:List.of("ALLOWANCE","PAYABLE","FUNDING","CAPITAL"))totals.put(key,purposes.getOrDefault(key,BigDecimal.ZERO).negate());
        totals.put("NET_LOANS",totals.get("LOAN_PRINCIPAL").add(totals.get("INTEREST_RECEIVABLE")).add(totals.get("FEE_RECEIVABLE")).subtract(totals.get("ALLOWANCE")));
        if(!reviewedSource(s))totals.replaceAll((key,value)->null);return totals;
    }
    private static boolean reviewedSource(Source source){return source.closeId()!=null || "INSTITUTION".equals(source.frozen().get("dimension")) || source.disclosures().getFirst().equals("REVIEWED_COVERAGE");}
    @Transactional(readOnly=true) public com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.Page<com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.Period> institutionPeriods(AppUserPrincipal actor,int page){actor=authorizeInstitution(authorize(actor,UserClaim.STATEMENT_FINALIZE));page(page);var rows=repository.institutionPeriods(actor.getSaccoId(),page);return new com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.Page<>(rows.size()>25?rows.subList(0,25):rows,page,rows.size()>25);}
    @Transactional(readOnly=true) public List<OfficialFormat> formats(AppUserPrincipal actor){authorizeAny(actor,UserClaim.REGULATORY_SUBMISSION_VIEW,UserClaim.REGULATORY_SUBMISSION_CREATE,UserClaim.REGULATORY_SUBMISSION_APPROVE);var result=repository.formats();require(result.size()<=100,"size");return result;}
    @Transactional public UUID submit(AppUserPrincipal actor,UUID formatId,UUID resultId,String file,byte[] bytes,String evidence,UUID corrects){
        actor=authorize(actor,UserClaim.REGULATORY_SUBMISSION_CREATE);text(file,200);text(evidence,1000);require(file.chars().noneMatch(c->c=='/' || c=='\\') && bytes!=null && bytes.length>0 && bytes.length<=2000000,"officialFile");String checksum=sha(bytes);Result result=verifiedResult(actor,resultId);requireCurrentPublication(actor,result);var format=official.get(formatId);require(format.kind()==result.definition().kind(),"officialKind");validateOfficial(format,result);LocalDate deadline=format.deadline(result.from(),result.through());
        require(file.toLowerCase(Locale.ROOT).endsWith("."+format.fileFormat().name().toLowerCase(Locale.ROOT)),"officialFile");SubmissionFileValidation.validate(bytes,format.fileFormat());if(corrects!=null){Submission prior=repository.submission(actor.getSaccoId(),actor.getStationId(),corrects,false);require(prior.format().equals(formatId) && prior.from().equals(result.from()) && prior.through().equals(result.through()) && prior.checker()!=null,"correction");}
        UUID id=repository.submit(actor.getSaccoId(),actor.getStationId(),formatId,resultId,result.from(),result.through(),deadline,file,checksum,bytes,evidence,corrects,actor.getMemberId(),clock.now());event(actor,id,"SUBMISSION_PREPARED");return id;
    }
    @Transactional public void reviewSubmission(AppUserPrincipal actor,UUID id,String evidence){actor=authorize(actor,UserClaim.REGULATORY_SUBMISSION_APPROVE);text(evidence,1000);Submission s=repository.submission(actor.getSaccoId(),actor.getStationId(),id,true);require(s.checker()==null && !s.maker().equals(actor.getMemberId()),"checker");Result result=verifiedResult(actor,s.result());requireCurrentPublication(actor,result);validateOfficial(official.get(s.format()),result);repository.reviewSubmission(actor.getSaccoId(),id,actor.getMemberId(),evidence,clock.now());event(actor,id,"SUBMISSION_REVIEWED");}
    private void requireCurrentPublication(AppUserPrincipal actor,Result result){verifiedVersionForPublication(actor,result.versionId());if(result.dimension()==RegulatoryFormatCatalog.Scope.INSTITUTION){actor=authorizeInstitution(actor);var current=closing.finalizedInstitutionSnapshotForPublication(actor,result.institutionPeriodId());require(current.checksum().equals(result.institutionSourceChecksum()) && lineage(current.branches()).equals(result.currentBranchSources()),"source");if(result.comparisonInstitutionPeriodId()!=null){var comparison=closing.finalizedInstitutionSnapshotForPublication(actor,result.comparisonInstitutionPeriodId());require(comparison.checksum().equals(result.comparisonInstitutionSourceChecksum()) && lineage(comparison.branches()).equals(result.comparisonBranchSources()) && !latest(comparison.branches()).isAfter(earliest(current.branches())),"comparisonEvidence");}}else{var current=closing.finalizedSnapshotForPublication(actor,result.closeReviewId());require(current.checksum().equals(result.closeChecksum()),"source");if(result.comparisonCloseId()!=null){var comparison=closing.finalizedSnapshotForPublication(actor,result.comparisonCloseId());require(comparison.checksum().equals(result.comparisonCloseChecksum()) && !comparison.recordedCutoff().isAfter(current.recordedCutoff()),"comparisonEvidence");}}}
    private void validateOfficial(RegulatoryFormatCatalog.Format format,Result result){
        format.requireScope(result.dimension());var rows=new ArrayList<Row>();var values=new HashMap<UUID,BigDecimal>();
        for(var source:result.rows())if(source.mandatory() && source.id().startsWith("REQUIRED_")){UUID key=UUID.nameUUIDFromBytes(source.id().getBytes(StandardCharsets.UTF_8));values.put(key,source.current());rows.add(new Row(source.id(),source.id(),source.id(),RowKind.ACCOUNT_GROUP,Section.NOTES,source.unit(),List.of(key),Sign.DEBIT_POSITIVE,null,null,null,true,false,false,null));}
        for(var c:format.calculations())rows.add(new Row(c.key(),c.key(),c.key(),c.unit()==Unit.RATIO?RowKind.RATIO:RowKind.SUBTOTAL,Section.NOTES,c.unit(),List.of(),null,c.expression(),null,null,true,false,false,null));
        var protectedDefinition=new StatementDefinition(1,1,Kind.NOTES,"Official calculations","Mahesabu rasmi",rows,List.of(),false);var calculated=protectedDefinition.calculate(values);
        for(var field:format.fields()){Value value=calculated.get(field.sourceLine());require(value!=null && value.amount()!=null && value.status().equals("KNOWN"),"officialField");}
    }
    @Transactional(readOnly=true) public List<Submission> submissions(AppUserPrincipal actor,int page){actor=authorizeAny(actor,UserClaim.REGULATORY_SUBMISSION_VIEW,UserClaim.REGULATORY_SUBMISSION_CREATE,UserClaim.REGULATORY_SUBMISSION_APPROVE);page(page);return repository.submissions(actor.getSaccoId(),actor.getStationId(),page);}
    @Transactional public byte[] submissionFile(AppUserPrincipal actor,UUID id){actor=authorize(actor,UserClaim.REGULATORY_SUBMISSION_VIEW);Submission s=repository.submission(actor.getSaccoId(),actor.getStationId(),id,false);verifiedResult(actor,s.result());byte[] bytes=repository.submissionFile(actor.getSaccoId(),actor.getStationId(),id);require(sha(bytes).equals(s.fileChecksum()),"checksum");event(actor,id,"SUBMISSION_FILE_DOWNLOADED");return bytes;}
    @Transactional(readOnly=true) public boolean hasInstitutionHistory(String id){return id!=null && repository.hasInstitutionHistory(id);}
    @Transactional(readOnly=true) public boolean hasMemberHistory(UUID id){return id!=null && repository.hasMemberHistory(id);}
    public AppUserPrincipal authorize(AppUserPrincipal actor,UserClaim claim){return authorizeAny(actor,claim);}
    private AppUserPrincipal authorizeAny(AppUserPrincipal actor,UserClaim...required){
        if(actor==null || !actor.isStaffSession() || actor.isPlatformIdentity() || actor.getMemberId()==null || actor.getSaccoId()==null || actor.getStationId()==null || actor.getSaccoId().isBlank() || actor.getStationId().isBlank())denied();
        Member member=members.find(actor.getMemberId()).orElseThrow(()->new AccessDeniedException("Statement access unavailable"));
        if(member.getStatus()!=MemberStatus.ACTIVE || !member.isStaffAccessActive() || member.getActiveStaffRolesResolved().contains(Position.ADMIN) || !Objects.equals(member.getSaccoId(),actor.getSaccoId()) || !Objects.equals(member.getStationId(),actor.getStationId()) || institutions.findActiveSacco(actor.getSaccoId()).isEmpty()
            || institutions.findStation(actor.getSaccoId(),actor.getStationId()).filter(SaccoStation::isActive).filter(s->s.getAccessStatus()==SaccoAccessStatus.ACTIVE).isEmpty())denied();
        AppUserPrincipal current=new AppUserPrincipal(member,claims.effectiveClaims(member.getId(),member.getActiveStaffRolesResolved(),member.isMemberAccess()),true);if(!access.hasAny(current,required))denied();return current;
    }
    private void dates(LocalDate from,LocalDate through){require(from!=null && through!=null && !from.isAfter(through) && !through.isAfter(clock.today()) && java.time.temporal.ChronoUnit.DAYS.between(from,through)<=366,"dates");}
    private static void institutionDifference(List<RowValue> rows,Source source,String kind){if("INSTITUTION".equals(source.frozen().get("dimension"))){String proof=kind+"; count="+source.frozen().get("retainedDifferenceCount")+"; SHA256="+source.checksum();rows.add(new RowValue("INSTITUTION_DIFFERENCES_"+kind,"Reviewed differences retained","Tofauti zilizohakikiwa zimehifadhiwa",RowKind.NOTE,Unit.NONE,null,null,"TEXT","TEXT",true,false,true,proof,proof));}}
    private static BigDecimal decimal(Object value){require(value!=null,"unknown");try{return new BigDecimal(value.toString()).setScale(2,java.math.RoundingMode.UNNECESSARY);}catch(NumberFormatException|ArithmeticException e){throw new IllegalArgumentException("statement.error.source");}}
    private static String memoNote(String note,String evidence){return note==null || note.isBlank()?evidence:note+"\n"+evidence;}
    private static void page(int page){require(page>=0 && page<=10000,"size");}
    private static void denied(){throw new AccessDeniedException("Statement permission and active branch required");}
    private void event(AppUserPrincipal actor,UUID id,String action){audit.log("FINANCIAL_STATEMENT",id,action,actor.getMemberId(),null,Map.of("saccoId",actor.getSaccoId(),"stationId",actor.getStationId()));}
    public static String sha(byte[] bytes){try{return HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(bytes));}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
