package com.sacco.mvp.accounting.policy;

/** Required reviewed decisions. Text records policy evidence; it is never executable code. */
public enum PolicyDecision {
    REPORTING_FRAMEWORK, FINANCIAL_YEAR, CHART_OF_ACCOUNTS, ACCOUNT_MAPPINGS,
    ROUNDING, INTEREST_RECOGNITION, CONTRACTUAL_INTEREST, FEES_AND_TAXES,
    IMPAIRMENT, NON_PERFORMING_INTEREST, EARLY_SETTLEMENT, CLOSING_AND_REOPENING,
    AUTHORIZATION_MATRIX, CUTOVER_AND_BACKOUT, AUDIT_RETENTION_AND_RECOVERY,
    EXTERNAL_INTEGRATION_BOUNDARY
}
