package com.sacco.mvp.accounting.policy;

public enum PostingEvent {
    OPENING_BALANCE, DISBURSEMENT, REPAYMENT, INTEREST_ACCRUAL, FEE,
    REFUND, ADVANCE, SETTLEMENT, TOP_UP, EXPENSE, FUNDING, CAPITAL,
    PROVISION, WRITE_OFF, RECOVERY, REVERSAL, MANUAL_JOURNAL, OPERATIONAL_BRIDGE
}
