<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ include file="../../fragments/header.jspf" %>
<%@ include file="../../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/accounting-ledger.css' />" />
<link rel="stylesheet" href="<c:url value='/css/accounting-vouchers.css' />" />

<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<spring:htmlEscape defaultHtmlEscape="true" />
<nav class="erp-page-path" aria-label="<spring:message code='common.breadcrumb' />"><a class="erp-page-path__item erp-page-path__link" href="<c:url value='${base}' />"><spring:message code="voucher.register.${voucherType}" /></a><span aria-hidden="true">›</span><span class="erp-page-path__item" aria-current="page"><spring:message code="voucher.create.${voucherType}" /></span></nav>
<div class="erp-page-header" data-aws-page-header><h1 class="erp-page-title"><spring:message code="voucher.create.${voucherType}" /></h1></div>
<div class="accounting-workspace accounting-create-workspace">
<c:url value="${base}" var="postUrl" />
<spring:message code="voucher.limit" var="voucherLimit" />
<spring:message code="voucher.chooseAccount" var="voucherChooseAccount" />
<form:form modelAttribute="voucherForm" method="post" action="${postUrl}" cssClass="accounting-create-form voucher-form" data-voucher-form="true" data-kind="${voucherType}" data-base="${postUrl}" data-limit="${voucherLimit}" data-choose-account="${voucherChooseAccount}">
<form:hidden path="requestKey" />
<div class="accounting-error-summary" role="alert" tabindex="-1"><form:errors path="*" element="p" cssClass="coa-error" /></div>
<section class="accounting-form accounting-create-card"><h2><spring:message code="voucher.information" /></h2><p class="voucher-help"><spring:message code="voucher.directHelp" /></p>
<div class="accounting-grid">
<label><spring:message code="voucher.date" /><input name="effectiveDate" type="date" class="aws-control" value="<c:out value='${voucherForm.effectiveDate}' />" required /><form:errors path="effectiveDate" cssClass="coa-error" /></label>
<label><spring:message code="${voucherType=='RECEIPT'?'voucher.receivedFrom':voucherType=='PAYMENT'?'voucher.paidTo':'voucher.party'}" /><form:input path="party" cssClass="aws-control" maxlength="160" required="required" /><form:errors path="party" cssClass="coa-error" /></label>
<label><spring:message code="voucher.reference" /><form:input path="reference" cssClass="aws-control" maxlength="160" required="required" /><form:errors path="reference" cssClass="coa-error" /></label>
<c:if test="${voucherType!='JOURNAL'}"><div class="voucher-field"><label><spring:message code="voucher.moneyAccount" /></label><div class="voucher-account-choice"><form:hidden path="moneyAccountId" /><span data-account-label><c:choose><c:when test="${not empty selectedAccounts[voucherForm.moneyAccountId]}"><c:out value="${selectedAccounts[voucherForm.moneyAccountId].code}" /> · <c:out value="${selectedAccounts[voucherForm.moneyAccountId].name}" /></c:when><c:otherwise><spring:message code="voucher.chooseAccount" /></c:otherwise></c:choose></span><button type="button" class="app-btn btn-neutral" data-account-for="moneyAccountId" data-money-only aria-label="<spring:message code='voucher.moneyAccount' />"><spring:message code="voucher.choose" /></button></div><form:errors path="moneyAccountId" cssClass="coa-error" /></div></c:if>
</div>
<details class="accounting-additional" ${not empty voucherForm.description or not empty voucherForm.evidence?'open':''}><summary><spring:message code="coa.additionalSettings" /></summary><div class="accounting-grid"><label><spring:message code="voucher.description" /><form:textarea path="description" rows="2" maxlength="500" cssClass="aws-control" /></label><label><spring:message code="voucher.evidence" /><form:input path="evidence" maxlength="500" cssClass="aws-control" /></label></div></details>
</section>
<section class="accounting-form accounting-create-card"><div class="voucher-toolbar"><h2><spring:message code="voucher.transactions" /></h2><button type="button" class="app-btn btn-neutral" data-add-row><spring:message code="voucher.addTransaction" /></button></div><p class="voucher-help"><spring:message code="voucher.rowsHelp" /></p>
<div data-voucher-rows><c:forEach items="${voucherForm.rows}" var="r" varStatus="s"><fieldset class="voucher-row" data-voucher-row><legend><spring:message code="voucher.transaction" /> <span data-row-number>${s.index+1}</span></legend>
<div class="voucher-row-tools"><button class="app-btn btn-neutral" type="button" data-mapping><spring:message code="voucher.chooseTransaction" /></button><button class="app-btn btn-neutral" type="button" data-manual><spring:message code="voucher.manual" /></button><button class="app-btn btn-neutral" type="button" data-remove-row><spring:message code="voucher.remove" /></button></div>
<form:hidden path="rows[${s.index}].transactionId" /><form:hidden path="rows[${s.index}].templateKey" /><form:hidden path="rows[${s.index}].component" />
<p class="voucher-help" data-mapping-label><c:if test="${not empty r.transactionId}"><spring:message code="voucher.mappingSelected" /> · <spring:message code="library.component.${r.component}" /></c:if></p>
<div class="accounting-grid"><label><spring:message code="voucher.description" /><form:input path="rows[${s.index}].description" cssClass="aws-control" maxlength="500" required="required" /><form:errors path="rows[${s.index}].description" cssClass="coa-error" /></label>
<label><spring:message code="voucher.amount" /> (TZS)<form:input path="rows[${s.index}].amount" type="number" min="0.01" max="9999999999999999.99" step="0.01" inputmode="decimal" cssClass="aws-control" required="required" /><form:errors path="rows[${s.index}].amount" cssClass="coa-error" /></label>
<c:forEach items="${['debit','credit']}" var="side"><c:if test="${voucherType=='JOURNAL' or (voucherType=='RECEIPT' and side=='credit') or (voucherType=='PAYMENT' and side=='debit')}"><c:set var="aid" value="${side=='debit'?r.debitAccountId:r.creditAccountId}" /><div class="voucher-field" data-manual-accounts><label><spring:message code="accounting.${side}" /> <spring:message code="voucher.account" /></label><div class="voucher-account-choice"><form:hidden path="rows[${s.index}].${side}AccountId" /><span data-account-label><c:choose><c:when test="${not empty selectedAccounts[aid]}"><c:out value="${selectedAccounts[aid].code}" /> · <c:out value="${selectedAccounts[aid].name}" /></c:when><c:otherwise><spring:message code="voucher.chooseAccount" /></c:otherwise></c:choose></span><button type="button" class="app-btn btn-neutral" data-account-for="rows[${s.index}].${side}AccountId" aria-label="<spring:message code='accounting.${side}' /> <spring:message code='voucher.account' />"><spring:message code="voucher.choose" /></button></div></div></c:if></c:forEach>
</div><form:errors path="rows[${s.index}].transactionId" cssClass="coa-error" />
</fieldset></c:forEach></div>
<p class="voucher-total"><spring:message code="voucher.total" /> (TZS): <output data-live-total>0.00</output></p><p class="voucher-help" data-row-status role="status"></p>
</section>
<c:if test="${not empty preview}"><section class="accounting-form accounting-create-card erp-table-wrap" data-voucher-preview data-aws-table-region><h2><spring:message code="voucher.preview" /></h2><p><spring:message code="voucher.previewHelp" /></p><div class="erp-table-scroll"><table class="erp-table"><thead><tr><th>#</th><th><spring:message code="accounting.debit" /></th><th><spring:message code="accounting.credit" /></th><th><spring:message code="voucher.amount" /> (TZS)</th></tr></thead><tbody><c:forEach items="${preview.rows}" var="r"><tr><td>${r.lineNo}</td><td><c:out value="${r.debit.code}" /> · <c:out value="${r.debit.name}" /></td><td><c:out value="${r.credit.code}" /> · <c:out value="${r.credit.name}" /></td><td><fmt:formatNumber value="${r.amount}" minFractionDigits="2" maxFractionDigits="2" /></td></tr></c:forEach></tbody></table></div></section></c:if>
<div class="accounting-actions accounting-form-actions"><a class="app-btn btn-neutral" href="<c:url value='${base}' />"><spring:message code="common.cancel" /></a><button class="app-btn btn-neutral" name="action" value="preview"><spring:message code="voucher.preview" /></button><button class="app-btn btn-primary" name="action" value="post"><spring:message code="voucher.post.${voucherType}" /></button></div>
</form:form></div>
<div class="app-modal-overlay" id="voucher-picker" hidden><div class="app-modal-panel app-modal-panel--compact" role="dialog" aria-modal="true" aria-labelledby="voucher-picker-title" tabindex="-1"><div class="app-modal-header"><h2 id="voucher-picker-title"><spring:message code="voucher.choose" /></h2><button type="button" class="app-modal-close" data-picker-close aria-label="<spring:message code='common.closeModal' />">×</button></div><div class="app-modal-body"><form data-picker-search><label><spring:message code="voucher.search" /><input class="aws-control" type="search" maxlength="100" name="search" /></label><button class="app-btn btn-neutral"><spring:message code="voucher.filter" /></button></form><p role="status" data-picker-status data-loading="<spring:message code='voucher.loading' />" data-error="<spring:message code='voucher.loadError' />" data-empty="<spring:message code='voucher.noMatches' />"></p><div data-picker-results></div><div class="accounting-actions"><button class="app-btn btn-neutral" type="button" data-picker-prev><spring:message code="common.previous" /></button><button class="app-btn btn-neutral" type="button" data-picker-next><spring:message code="common.next" /></button></div></div></div></div>
<%@ include file="../accounting-form-support.jspf" %>
<script src="<c:url value='/js/accounting-vouchers.js' />" defer></script>
<%@ include file="../../fragments/footer.jspf" %>
