<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ include file="../../fragments/header.jspf" %>
<%@ include file="../../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/accounting-business.css' />" />
<div class="business-workspace">
<div class="erp-page-header"><h1 class="erp-page-title"><spring:message code="finance.business.navigation" /></h1></div>
<p class="business-gate"><spring:message code="finance.business.gate" /></p>
<c:if test="${not empty sourceError}"><div class="business-error" role="alert"><spring:message code="${sourceError}" /></div></c:if>
<section class="business-form"><h2><spring:message code="finance.business.kind.${document.command.kind}"/></h2><dl class="business-grid"><div><dt><spring:message code="finance.business.reference"/></dt><dd><c:out value="${document.id}"/></dd></div><div><dt><spring:message code="finance.business.status"/></dt><dd><spring:message code="finance.business.state.${document.state}"/></dd></div><div><dt><spring:message code="finance.business.date"/></dt><dd><c:out value="${document.command.effectiveDate}"/></dd></div><div><dt><spring:message code="finance.business.amount"/> (TZS)</dt><dd><c:out value="${document.command.amount}"/></dd></div><div><dt><spring:message code="finance.business.evidenceReference"/></dt><dd><c:out value="${document.command.evidenceReference}"/></dd></div><div><dt><spring:message code="finance.business.description"/></dt><dd><c:out value="${document.command.description}"/></dd></div><div><dt><spring:message code="finance.business.principal"/></dt><dd><c:out value="${document.principal}"/></dd></div><div><dt><spring:message code="finance.business.interest"/></dt><dd><c:out value="${document.interest}"/></dd></div></dl>
<c:if test="${document.state=='DRAFT'}"><sec:authorize access="@access.has(principal,'ACCOUNTING_BUSINESS_CREATE')"><form method="post" action="<c:url value='/finance/business/${document.id}/submit'/>"><input type="hidden" name="${_csrf.parameterName}" value="<c:out value='${_csrf.token}' />" /><button class="app-btn btn-primary" type="submit"><spring:message code="finance.business.submit"/></button></form></sec:authorize></c:if>
<c:if test="${document.state=='SUBMITTED'}"><sec:authorize access="@access.has(principal,'ACCOUNTING_BUSINESS_APPROVE')"><form method="post" action="<c:url value='/finance/business/${document.id}/post'/>"><input type="hidden" name="${_csrf.parameterName}" value="<c:out value='${_csrf.token}' />" /><label><spring:message code="finance.business.approvalEvidence"/><input name="approvalEvidence" maxlength="500" required value="<c:out value='${approvalEvidence}'/>"/></label><label class="business-confirm"><input type="checkbox" name="confirmed" value="true" required/><spring:message code="finance.business.confirm"/></label><div class="business-actions"><button class="app-btn btn-primary" type="submit"><spring:message code="finance.business.approvePost"/></button><button class="app-btn btn-neutral" type="submit" formaction="<c:url value='/finance/business/${document.id}/reject'/>" formnovalidate><spring:message code="finance.business.reject"/></button></div></form></sec:authorize></c:if>
<c:if test="${document.state=='POSTED'}"><p><spring:message code="finance.business.postedHelp"/></p><c:if test="${not empty document.journalId}"><a class="app-btn btn-neutral" href="<c:url value='/finance/journals/${document.journalId}'/>"><spring:message code="finance.business.journal"/></a></c:if><c:if test="${not empty document.loanTransactionId}"><a class="app-btn btn-neutral" href="<c:url value='/repayments/loans/${document.command.loanId}/receipts/${document.loanTransactionId}'/>"><spring:message code="finance.business.receipt"/></a></c:if></c:if></section>
</div>
<%@ include file="../../fragments/footer.jspf" %>

