package com.sacco.mvp.reporting.execution;

import com.sacco.mvp.accounting.dto.GeneralLedgerDtos.*;
import com.sacco.mvp.accounting.policy.*;
import com.sacco.mvp.accounting.policy.AccountingPolicyService.*;
import com.sacco.mvp.accounting.repository.GeneralLedgerRepository;
import com.sacco.mvp.accounting.service.GeneralLedgerService;
import com.sacco.mvp.accounting.reconciliation.*;
import com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.Allocation;
import com.sacco.mvp.accounting.reconciliation.ReconciliationDtos.StatementCommand;
import com.sacco.mvp.accounting.statements.*;
import com.sacco.mvp.domain.*;
import com.sacco.mvp.reporting.*;
import com.sacco.mvp.reporting.execution.dto.AccountingReleaseDtos.*;
import com.sacco.mvp.reporting.execution.dto.ReportRunDtos.Request;
import com.sacco.mvp.reporting.execution.dto.StatementOutputDtos.Layout;
import com.sacco.mvp.reporting.execution.repository.*;
import com.sacco.mvp.reporting.execution.service.*;
import com.sacco.mvp.security.AppUserPrincipal;
import com.sacco.mvp.service.*;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.aop.framework.ProxyFactory;
import org.springframework.context.support.ResourceBundleMessageSource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.*;
import org.springframework.transaction.annotation.AnnotationTransactionAttributeSource;
import org.springframework.transaction.interceptor.TransactionInterceptor;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;

/** Actual A/B/D/F/G/H stored sources on a fresh disposable database. Policies are explicit synthetic fixtures. */
@EnabledIfEnvironmentVariable(named="MICROFINANCE_RELEASE_H_DATABASE_URL",matches="jdbc:postgresql://127\\.0\\.0\\.1:[0-9]+/microfinance_accounting_h_release_(test|final_test)")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class AccountingReleasePostgresTest {
 private com.zaxxer.hikari.HikariDataSource ds;
 private JdbcTemplate jdbc;
 private DataSourceTransactionManager manager;
 private TransactionTemplate tx;
 private GeneralLedgerService gl;
 private ReconciliationService closing;
 private StatementDesignerService statements;
 private ReportRunService runs;
 private ReportRunGenerator generator;
 private ReportWorkerControl worker;
 private OperationalReportTemplateService templates;
 private StatementOutputService outputs;
 private AccountingReleaseService releases;
 private AccountingReleaseGateService gate;
 private AccountingReleaseRepository releaseRepository;
 private AccountingPolicyService policies;
 private AuditService audit;
 private UserClaimService claims;
 private MemberDirectoryService directory;
 private SaccoRegistryService institutions;
 private ApplicationClock clock;
 private String institution;
 private AppUserPrincipal maker,checker,accountant,compliance,staff;
 private UUID bank,capital,policy,period,version,result,output,first,second;
 private OffsetDateTime now;
 private static final LocalDate DAY=LocalDate.of(2026,10,1),END=LocalDate.of(2026,10,31);
 @BeforeAll void start()throws Exception{
  var config=new com.zaxxer.hikari.HikariConfig();config.setJdbcUrl(System.getenv("MICROFINANCE_RELEASE_H_DATABASE_URL"));config.setUsername("microfinance_test");config.setPassword("");config.setMaximumPoolSize(6);config.setMinimumIdle(0);config.addDataSourceProperty("sslmode","disable");config.addDataSourceProperty("connectTimeout","10");config.addDataSourceProperty("socketTimeout","30");ds=new com.zaxxer.hikari.HikariDataSource(config);
  // No out-of-order override: the dedicated new database migrates normally in version order.
  Flyway.configure().dataSource(ds).locations("classpath:db/migration").load().migrate();jdbc=new JdbcTemplate(ds);manager=new DataSourceTransactionManager(ds);tx=new TransactionTemplate(manager);
  policies=mock(AccountingPolicyService.class);audit=mock(AuditService.class);claims=mock(UserClaimService.class);directory=mock(MemberDirectoryService.class);institutions=mock(SaccoRegistryService.class);clock=mock(ApplicationClock.class);var access=new AccessControlService();var mapper=JsonMapper.builder().findAndAddModules().build();var logos=mock(SaccoLogoStorageService.class);
  releaseRepository=new AccountingReleaseRepository(jdbc,mapper);gate=proxy(new AccountingReleaseGateService(releaseRepository));
  var periodListener=proxy(new AccountingPeriodReleaseInvalidation(releaseRepository,clock));var mappingListener=proxy(new AccountingMappingReleaseInvalidation(releaseRepository,clock));
  gl=proxy(new GeneralLedgerService(new GeneralLedgerRepository(jdbc),policies,access,audit,clock,claims,directory,institutions));closing=proxy(new ReconciliationService(new ReconciliationRepository(jdbc),policies,access,directory,claims,audit,clock,Optional.empty(),List.of(periodListener)));
  var statementRepo=new StatementRepository(jdbc,mapper);statements=proxy(new StatementDesignerService(statementRepo,policies,gl,closing,new RegulatoryFormatCatalog(statementRepo,mapper,clock),access,directory,claims,institutions,clock,audit,mapper,List.of(mappingListener)));
  var actors=new OperationalReportService(new OperationalReportRepository(new NamedParameterJdbcTemplate(jdbc)),access,clock,directory,claims,institutions,logos);templates=proxy(new OperationalReportTemplateService(new OperationalReportTemplateRepository(jdbc,mapper),actors,access,clock,audit));var runRepo=new ReportRunRepository(jdbc,mapper);var codec=new ReportResultCodec(mapper);runs=proxy(new ReportRunService(runRepo,actors,templates,access,clock,audit,codec));worker=proxy(new ReportWorkerControl(runRepo,clock,actors));var messages=new ResourceBundleMessageSource();messages.setBasename("messages");messages.setDefaultEncoding("UTF-8");messages.setFallbackToSystemLocale(false);generator=proxy(new ReportRunGenerator(runRepo,actors,templates,new OperationalReportExportService(messages),worker,codec,directory,clock,audit));outputs=proxy(new StatementOutputService(new StatementOutputRepository(jdbc,mapper),statements,new StatementTypedExporter(messages),actors,access,logos,new ReportExportLimiter(1),clock,audit,mapper));releases=proxy(new AccountingReleaseService(releaseRepository,outputs,statements,closing,policies,runs,actors,access,clock,audit,mapper));
 }
 @AfterAll void stop(){if(ds!=null)ds.close();}
 @AfterEach void releaseSyntheticJobs(){if(institution!=null)jdbc.update("UPDATE report_runs SET status='CANCELLED',cancel_requested=true,lease_until=NULL WHERE sacco_id=? AND status IN('QUEUED','RUNNING','FAILED')",institution);}
 @BeforeEach void fixture(){
  reset(policies,audit,claims,directory,institutions,clock);now=OffsetDateTime.parse("2026-11-01T10:00:00+03:00");when(clock.now()).thenAnswer(i->now);when(clock.today()).thenReturn(END.plusDays(1));institution="HR-"+UUID.randomUUID();jdbc.update("INSERT INTO registered_saccos(sacco_id,sacco_name,active,created_at,updated_at) VALUES(?,'Synthetic H release institution',true,now(),now())",institution);jdbc.update("INSERT INTO sacco_stations(id,sacco_id,station_id,active,created_at,updated_at,access_status) VALUES(?,?,'B1',true,now(),now(),'ACTIVE')",UUID.randomUUID(),institution);
  when(institutions.findActiveSacco(institution)).thenReturn(Optional.of(RegisteredSacco.builder().saccoId(institution).active(true).build()));when(institutions.findStation(eq(institution),anyString())).thenAnswer(i->Optional.of(SaccoStation.builder().saccoId(institution).stationId(i.getArgument(1)).active(true).accessStatus(SaccoAccessStatus.ACTIVE).build()));when(claims.effectiveClaims(any(),anyCollection(),anyBoolean())).thenReturn(EnumSet.allOf(UserClaim.class));maker=operator("B1");checker=operator("B1");accountant=operator("B1");compliance=operator("B1");staff=operator("B1");
  bank=gl.createAccount(maker,new AccountCommand("BANK","Synthetic bank","ASSET","DEBIT","POSTING","BANK",null));capital=gl.createAccount(maker,new AccountCommand("CAPITAL","Synthetic capital","EQUITY","CREDIT","POSTING","CAPITAL",null));policy=UUID.randomUUID();var decisions=new EnumMap<PolicyDecision,String>(PolicyDecision.class);for(var key:PolicyDecision.values())decisions.put(key,"Synthetic reviewed evidence only");var matrix=new EnumMap<PostingEvent,PostingRule>(PostingEvent.class);for(var key:PostingEvent.values())matrix.put(key,new PostingRule(PostingPermission.ALLOWED,"Synthetic treatment"));var mappings=Map.of("DISBURSEMENT_CLEARING",bank,"REPAYMENT_CLEARING",bank,"OWNER_CAPITAL",capital);var mapper=JsonMapper.builder().findAndAddModules().build();jdbc.update("INSERT INTO accounting_policies(id,sacco_id,policy_version,effective_from,opening_date,authoritative_ledger,decisions_json,posting_matrix_json,account_mappings_json,evidence_reference,maker_id,request_key,created_at) VALUES(?,?,1,?,?,'LOCAL_GL',?,?,?,'Synthetic evidence',?,?,?)",policy,institution,DAY,DAY,mapper.writeValueAsString(decisions),mapper.writeValueAsString(matrix),mapper.writeValueAsString(mappings),maker.getMemberId(),UUID.randomUUID(),now);jdbc.update("INSERT INTO accounting_policy_approvals(policy_id,sacco_id,policy_version,effective_from,checker_id,decision,evidence_reference,reason,decided_at) VALUES(?,?,1,?,?,'APPROVED','Synthetic independent policy evidence','Test only',?)",policy,institution,DAY,checker.getMemberId(),now);when(policies.requireApprovedLocalPolicy(eq(institution),any())).thenReturn(new PolicySnapshot(policy,institution,1,DAY,DAY,AuthoritativeLedger.LOCAL_GL,decisions,matrix,mappings,"Synthetic evidence",maker.getMemberId(),AccountingPolicyService.Decision.APPROVED,checker.getMemberId(),"Synthetic independent review","Test only",now));
  period=gl.createPeriod(maker,DAY,END);UUID opening=post("OPENING","1000.01",true);UUID journal=post("SOURCE","1.01",false);UUID format=closing.proposeFormat(maker,"Synthetic CSV","Synthetic format evidence");closing.approveFormat(checker,format,"Independent synthetic format review");UUID imported=closing.importStatement(maker,new StatementCommand(UUID.randomUUID(),bank,format,DAY.plusDays(1),END,new BigDecimal("1000.01"),new BigDecimal("1001.02"),"synthetic.csv","Synthetic statement evidence","date,reference,amount,kind\n2026-10-02,SOURCE,1.01,RECEIPT"));UUID line=jdbc.queryForObject("SELECT id FROM gl_journal_line WHERE journal_id=? AND account_id=?",UUID.class,journal,bank);UUID match=closing.proposeMatch(maker,"EXACT","Synthetic matching evidence",List.of(new Allocation(closing.rows(maker,imported,0).rows().getFirst().id(),line,new BigDecimal("1.01"))));closing.reviewMatch(checker,match,true,"Independent match review");UUID certificate=closing.certify(maker,bank,END,"STATEMENT",new BigDecimal("1001.02"),"Synthetic verified source");closing.reviewCertificate(checker,certificate,"Independent reconciliation review");UUID close=closing.proposeClose(maker,period,"Synthetic close",false);closing.approveClose(checker,close,"Independent close evidence");closing.completeInstitutionClose(checker,period,"Synthetic all-branch acceptance");
  version=statements.save(maker,null,definition(),"Synthetic statement mapping");statements.approve(checker,version,"Independent mapping review");result=statements.finalize(maker,version,close,null);output=outputs.capture(maker,result,new Layout(1,"en",false,false));outputs.review(checker,output,"Independent synthetic output review");first=sample("en");second=sample("sw");
 }
 private UUID post(String ref,String amount,boolean opening){BigDecimal value=new BigDecimal(amount);var cmd=new JournalCommand(UUID.randomUUID(),ref,opening?DAY:DAY.plusDays(1),"Synthetic verified source",null,List.of(new Line(bank,value,BigDecimal.ZERO),new Line(capital,BigDecimal.ZERO,value)));var journal=opening?gl.importOpening(maker,cmd):gl.draftManual(maker,cmd);gl.approve(checker,journal.id(),"Independent synthetic source review");return gl.post(checker,journal.id(),opening).id();}
 private StatementDefinition definition(){return new StatementDefinition(1,1,StatementDefinition.Kind.BALANCE_SHEET,"Synthetic financial position","Hali ya fedha ya majaribio",List.of(new StatementDefinition.Row("BANK","Bank","Benki",StatementDefinition.RowKind.ACCOUNT_GROUP,StatementDefinition.Section.ASSETS,StatementDefinition.Unit.TZS,List.of(bank),StatementDefinition.Sign.DEBIT_POSITIVE,null,null,null,true,false,false,null),new StatementDefinition.Row("CAPITAL","Capital","Mtaji",StatementDefinition.RowKind.ACCOUNT_GROUP,StatementDefinition.Section.EQUITY,StatementDefinition.Unit.TZS,List.of(capital),StatementDefinition.Sign.CREDIT_POSITIVE,null,null,null,true,false,false,null)),List.of(),false);}
 private UUID sample(String language){return sample(language,DAY,END);}
 private UUID sample(String language,LocalDate from,LocalDate through){var definition=OperationalReportDefinition.standard(OperationalReportDefinition.Dataset.DISBURSEMENTS,language);if(language.equals("sw")){var columns=new ArrayList<>(definition.columns());Collections.reverse(columns);definition=new OperationalReportDefinition(1,definition.dataset(),definition.title(),definition.footer(),language,true,columns,definition.filters(),definition.sorts(),definition.groups(),definition.totals(),false);}UUID template=templates.save(definition,null,true,maker);templates.publish(template,checker);UUID id=runs.request(maker,new Request(UUID.randomUUID(),template,from,through,now,Set.of(OperationalReportExportService.Format.CSV),null,null));generator.generate(worker.claim().orElseThrow());runs.approve(id,"Independent synthetic layout acceptance",checker);return id;}
 private AppUserPrincipal operator(String branch){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO members(id,sacco_id,station_id,member_no,staff_no,full_name,status,position,created_at,is_member,staff_access_status,password_hash) VALUES(?,?,?,?,?,'Synthetic H officer','ACTIVE','MANAGER',now(),false,'ACTIVE','test-only')",id,institution,branch,id.toString(),id.toString());var member=Member.builder().id(id).saccoId(institution).stationId(branch).memberNo(id.toString()).staffNo(id.toString()).fullName("Synthetic H officer").position(Position.MANAGER).status(MemberStatus.ACTIVE).staffAccessStatus(StaffAccessStatus.ACTIVE).build();when(directory.find(id)).thenReturn(Optional.of(member));return new AppUserPrincipal(member,EnumSet.allOf(UserClaim.class),true);}
 private Proposal proposal(){return new Proposal(UUID.randomUUID(),output,first,second,"Synthetic release proposal only");}
 private UUID approvedRelease(){UUID id=releases.propose(maker,proposal());releases.decide(accountant,id,Stage.ACCOUNTANT,true,"Synthetic accountant acceptance");releases.decide(compliance,id,Stage.COMPLIANCE,true,"Synthetic compliance acceptance");releases.decide(staff,id,Stage.STAFF,true,"Synthetic staff acceptance");return id;}
 @Test void finalOutputsRetainSameExactResultAndAllThreeChecksummedFormats(){var capture=outputs.get(maker,output);assertThat(capture.result().reconciliations().get("CASH_CLOSING")).isEqualByComparingTo("1001.02");assertThat(capture.sourceChecksum()).isEqualTo(statements.verifiedResultDigest(maker,result));assertThat(outputs.artifacts(maker,output)).hasSize(3);for(var artifact:outputs.artifacts(maker,output)){var downloaded=outputs.download(maker,output,artifact.id());assertThat(ReportRunService.sha256(downloaded.bytes())).isEqualTo(artifact.checksum());}assertThat(outputs.capture(maker,result,new Layout(1,"en",false,false))).isEqualTo(output);assertThatThrownBy(()->jdbc.update("DELETE FROM statement_output_artifacts WHERE output_id=?",output)).isInstanceOf(org.springframework.dao.DataAccessException.class);}
 @Test void separateIndependentDecisionsGateTheExactPolicyAndScope(){UUID id=releases.propose(maker,proposal());assertThatThrownBy(()->tx.executeWithoutResult(s->gate.requireLiveRelease(maker,policy,1))).hasMessage("accounting.release.error.restricted");assertThatThrownBy(()->releases.decide(maker,id,Stage.ACCOUNTANT,true,"Own acceptance")).hasMessage("accounting.release.error.checker");assertThatThrownBy(()->releases.decide(compliance,id,Stage.COMPLIANCE,true,"Out of sequence")).hasMessage("accounting.release.error.stage");releases.decide(accountant,id,Stage.ACCOUNTANT,true,"Synthetic accountant review");assertThatThrownBy(()->releases.decide(accountant,id,Stage.COMPLIANCE,true,"Repeated reviewer")).hasMessage("accounting.release.error.checker");releases.decide(compliance,id,Stage.COMPLIANCE,true,"Synthetic compliance review");releases.decide(staff,id,Stage.STAFF,true,"Synthetic staff review");assertThat(releases.get(maker,id).getState()).isEqualTo("APPROVED");tx.executeWithoutResult(s->gate.requireLiveRelease(maker,policy,1));assertThatThrownBy(()->tx.executeWithoutResult(s->gate.requireLiveRelease(maker,policy,2))).hasMessage("accounting.release.error.restricted");assertThatThrownBy(()->releases.get(operator("B2"),id)).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);}
 @Test void proposalRetriesAreIdempotentButChangedEvidenceIsRejected(){Proposal proposal=proposal();UUID id=releases.propose(maker,proposal);assertThat(releases.propose(maker,proposal)).isEqualTo(id);assertThatThrownBy(()->releases.propose(maker,new Proposal(proposal.requestKey(),output,first,second,"Changed evidence"))).hasMessage("accounting.release.error.retry");assertThatThrownBy(()->releases.propose(maker,new Proposal(UUID.randomUUID(),output,first,first,"Same layout"))).hasMessage("accounting.release.error.source");}
 @Test void reopeningRevokesReleaseButKeepsEveryFinalArtifactByte(){UUID id=approvedRelease();var artifact=outputs.artifacts(maker,output).getFirst();byte[] before=outputs.download(maker,output,artifact.id()).bytes();now=now.plusMinutes(1);UUID reopen=closing.proposeClose(accountant,period,"Synthetic reviewed correction",true);closing.approveClose(compliance,reopen,"Independent reopening evidence");assertThat(releases.get(maker,id).getState()).isEqualTo("INVALIDATED");assertThatThrownBy(()->tx.executeWithoutResult(s->gate.requireLiveRelease(maker,policy,1))).hasMessage("accounting.release.error.restricted");assertThat(outputs.download(maker,output,artifact.id()).bytes()).isEqualTo(before);assertThatThrownBy(()->releases.propose(maker,proposal())).hasMessage("reconciliation.error.approvalRequired");}
 @Test void retirementRevokesReleaseAndCannotRewriteRetainedEvidence(){UUID id=approvedRelease();String checksum=releases.get(maker,id).checksum();statements.retire(checker,version);assertThat(releases.get(maker,id).getState()).isEqualTo("INVALIDATED");assertThat(releases.get(maker,id).checksum()).isEqualTo(checksum);assertThatThrownBy(()->tx.executeWithoutResult(s->gate.requireLiveRelease(maker,policy,1))).hasMessage("accounting.release.error.restricted");assertThatThrownBy(()->jdbc.update("UPDATE accounting_release_decisions SET approved=false WHERE release_id=?",id)).isInstanceOf(org.springframework.dao.DataAccessException.class);}
 @Test void auditFailureRollsBackReleaseDecisionAndAllowsExactRetry(){UUID id=releases.propose(maker,proposal());doThrow(new IllegalStateException("Synthetic audit failure")).when(audit).log(eq("ACCOUNTING_RELEASE"),eq(id),eq("ACCOUNTANT_APPROVED"),any(),any(),anyMap());assertThatThrownBy(()->releases.decide(accountant,id,Stage.ACCOUNTANT,true,"Synthetic review")).hasMessage("Synthetic audit failure");assertThat(releases.get(maker,id).decisions()).isEmpty();reset(audit);releases.decide(accountant,id,Stage.ACCOUNTANT,true,"Synthetic review");assertThat(releases.get(maker,id).decisions()).hasSize(1);}
 @Test void revokedFinancialDownloadPermissionBlocksCachedArtifact(){var artifact=outputs.artifacts(maker,output).getFirst();var allowed=EnumSet.allOf(UserClaim.class);allowed.remove(UserClaim.STATEMENT_EXPORT);when(claims.effectiveClaims(eq(maker.getMemberId()),anyCollection(),anyBoolean())).thenReturn(allowed);assertThatThrownBy(()->outputs.download(maker,output,artifact.id())).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);assertThat(outputs.get(maker,output).id()).isEqualTo(output);}
 @Test void concurrentAccountantDecisionsRecordExactlyOneReview()throws Exception{UUID id=releases.propose(maker,proposal());try(var pool=Executors.newFixedThreadPool(2)){var a=pool.submit(()->decision(accountant,id));var b=pool.submit(()->decision(operatorForThread(),id));assertThat(List.of(a.get(30,TimeUnit.SECONDS),b.get(30,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);assertThat(releases.get(maker,id).decisions()).hasSize(1);}}
 private AppUserPrincipal operatorForThread(){return checker;}
 private boolean decision(AppUserPrincipal actor,UUID id){try{releases.decide(actor,id,Stage.ACCOUNTANT,true,"Concurrent synthetic reviewer");return true;}catch(IllegalArgumentException ex){return false;}}
 @Test void rejectedReleaseCannotActivateOrAccumulateFurtherApprovals(){UUID id=releases.propose(maker,proposal());releases.decide(accountant,id,Stage.ACCOUNTANT,false,"Synthetic unresolved difference");assertThat(releases.get(maker,id).getState()).isEqualTo("REJECTED");assertThatThrownBy(()->releases.decide(compliance,id,Stage.COMPLIANCE,true,"Invalid followup")).hasMessage("accounting.release.error.state");assertThatThrownBy(()->tx.executeWithoutResult(s->gate.requireLiveRelease(maker,policy,1))).hasMessage("accounting.release.error.restricted");}
 @Test void freshMigrationHistoryIsStrictlySortedAndIncludesReleaseSchema(){var versions=jdbc.queryForList("SELECT version FROM flyway_schema_history WHERE version IS NOT NULL AND success ORDER BY installed_rank",String.class);var order=versions.stream().map(org.flywaydb.core.api.MigrationVersion::fromVersion).toList();assertThat(order).isSorted();assertThat(versions).contains("45.1","46.1","47","49","49.1","49.2");assertThat(jdbc.queryForObject("SELECT count(*) FROM pg_class WHERE relname='accounting_release_decisions'",Long.class)).isEqualTo(1L);System.out.println("H strict sorted fresh migration versions: "+versions);}
 @Test void RenamingAnOtherwiseIdenticalLayoutDoesNotSatisfyTwoLayoutAcceptance(){UUID identical=sample("en");assertThatThrownBy(()->releases.propose(maker,new Proposal(UUID.randomUUID(),output,first,identical,"Synthetic repeated layout"))).hasMessage("accounting.release.error.layouts");}
 @Test void mappingRetirementWaitsForAnAlreadyAuthorizedPostingTransaction()throws Exception{
  UUID id=approvedRelease();var entered=new CountDownLatch(1);var finish=new CountDownLatch(1);
  try(var pool=Executors.newFixedThreadPool(2)){
   var posting=pool.submit(()->tx.executeWithoutResult(s->{gate.requireLiveRelease(maker,policy,1);entered.countDown();try{if(!finish.await(10,TimeUnit.SECONDS))throw new AssertionError("Synthetic posting latch timeout");}catch(InterruptedException ex){Thread.currentThread().interrupt();throw new AssertionError(ex);}}));
   assertThat(entered.await(10,TimeUnit.SECONDS)).isTrue();var retirement=pool.submit(()->statements.retire(checker,version));
   assertThatThrownBy(()->retirement.get(300,TimeUnit.MILLISECONDS)).isInstanceOf(TimeoutException.class);finish.countDown();posting.get(10,TimeUnit.SECONDS);retirement.get(10,TimeUnit.SECONDS);assertThat(releases.get(maker,id).getState()).isEqualTo("INVALIDATED");
  }finally{finish.countDown();}
 }
 @Test void reopeningEarlierPeriodInvalidatesLaterCumulativeReleaseAndRetainsFiles(){
  UUID earlierRelease=approvedRelease();LocalDate from=END.plusDays(1),through=END.plusMonths(1);now=now.plusMonths(1);when(clock.today()).thenReturn(through.plusDays(1));
  UUID laterPeriod=gl.createPeriod(maker,from,through);var value=new BigDecimal("2.00");var command=new JournalCommand(UUID.randomUUID(),"NEXT",from.plusDays(1),"Synthetic later source",null,List.of(new Line(bank,value,BigDecimal.ZERO),new Line(capital,BigDecimal.ZERO,value)));var journal=gl.draftManual(maker,command);gl.approve(checker,journal.id(),"Synthetic later source review");gl.post(checker,journal.id(),false);
  UUID format=closing.proposeFormat(maker,"Later synthetic CSV","Synthetic later format");closing.approveFormat(checker,format,"Independent later format review");UUID imported=closing.importStatement(maker,new StatementCommand(UUID.randomUUID(),bank,format,from,through,new BigDecimal("1001.02"),new BigDecimal("1003.02"),"later.csv","Synthetic later statement","date,reference,amount,kind\n2026-11-02,NEXT,2.00,RECEIPT"));UUID line=jdbc.queryForObject("SELECT id FROM gl_journal_line WHERE journal_id=? AND account_id=?",UUID.class,journal.id(),bank);UUID match=closing.proposeMatch(maker,"EXACT","Synthetic later match",List.of(new Allocation(closing.rows(maker,imported,0).rows().getFirst().id(),line,value)));closing.reviewMatch(checker,match,true,"Independent later match");UUID certificate=closing.certify(maker,bank,through,"STATEMENT",new BigDecimal("1003.02"),"Synthetic later verified source");closing.reviewCertificate(checker,certificate,"Independent later reconciliation");UUID close=closing.proposeClose(maker,laterPeriod,"Synthetic later close",false);closing.approveClose(checker,close,"Independent later close");closing.completeInstitutionClose(checker,laterPeriod,"Synthetic later institution acceptance");
  UUID laterResult=statements.finalize(maker,version,close,null);UUID laterOutput=outputs.capture(maker,laterResult,new Layout(1,"en",false,false));outputs.review(checker,laterOutput,"Independent later output review");UUID a=sample("en",from,through),b=sample("sw",from,through);UUID laterRelease=releases.propose(maker,new Proposal(UUID.randomUUID(),laterOutput,a,b,"Synthetic later release"));releases.decide(accountant,laterRelease,Stage.ACCOUNTANT,true,"Synthetic later accountant");releases.decide(compliance,laterRelease,Stage.COMPLIANCE,true,"Synthetic later compliance");releases.decide(staff,laterRelease,Stage.STAFF,true,"Synthetic later staff");var artifact=outputs.artifacts(maker,laterOutput).getFirst();byte[] before=outputs.download(maker,laterOutput,artifact.id()).bytes();
  now=now.plusMinutes(1);UUID reopen=closing.proposeClose(accountant,period,"Synthetic earlier correction affects later balances",true);closing.approveClose(compliance,reopen,"Independent earlier reopening");assertThat(releases.get(maker,earlierRelease).getState()).isEqualTo("INVALIDATED");assertThat(releases.get(maker,laterRelease).getState()).isEqualTo("INVALIDATED");assertThatThrownBy(()->tx.executeWithoutResult(s->gate.requireLiveRelease(maker,policy,1))).hasMessage("accounting.release.error.restricted");assertThat(outputs.download(maker,laterOutput,artifact.id()).bytes()).isEqualTo(before);
 }
 @Test @EnabledIfEnvironmentVariable(named="MICROFINANCE_RELEASE_H_RESTORE_DATABASE_URL",matches="jdbc:postgresql://127\\.0\\.0\\.1:[0-9]+/microfinance_h_restore_[0-9]+")
 void restoredPostedOpeningAndManualCommandsReplayWithoutNewMoneyOrOutbox(){
  var config=new com.zaxxer.hikari.HikariConfig();config.setJdbcUrl(System.getenv("MICROFINANCE_RELEASE_H_RESTORE_DATABASE_URL"));config.setUsername("microfinance_test");config.setPassword("");config.setMaximumPoolSize(2);config.setMinimumIdle(0);config.addDataSourceProperty("sslmode","disable");
  try(var restored=new com.zaxxer.hikari.HikariDataSource(config)){
   var restoredJdbc=new JdbcTemplate(restored);var restoredManager=new DataSourceTransactionManager(restored);var restoredDirectory=mock(MemberDirectoryService.class);var restoredClaims=mock(UserClaimService.class);var restoredInstitutions=mock(SaccoRegistryService.class);var restoredAudit=mock(AuditService.class);when(restoredClaims.effectiveClaims(any(),anyCollection(),anyBoolean())).thenReturn(EnumSet.allOf(UserClaim.class));var target=new GeneralLedgerService(new GeneralLedgerRepository(restoredJdbc),mock(AccountingPolicyService.class),new AccessControlService(),restoredAudit,clock,restoredClaims,restoredDirectory,restoredInstitutions);var factory=new ProxyFactory(target);factory.setProxyTargetClass(true);factory.addAdvice(new TransactionInterceptor(restoredManager,new AnnotationTransactionAttributeSource()));var service=(GeneralLedgerService)factory.getProxy();
   var sources=restoredJdbc.queryForList("SELECT DISTINCT ON(source_type) id,sacco_id,station_id,checker_id,source_type FROM gl_journal WHERE state='POSTED' AND source_type IN('OPENING','MANUAL') ORDER BY source_type,id");assertThat(sources).hasSize(2);String signature="SELECT encode(sha256(convert_to(COALESCE(string_agg(to_jsonb(t)::text,'|' ORDER BY t.id),''),'UTF8')),'hex') FROM gl_journal t";String before=restoredJdbc.queryForObject(signature,String.class);long lines=restoredJdbc.queryForObject("SELECT count(*) FROM gl_journal_line",Long.class),events=restoredJdbc.queryForObject("SELECT count(*) FROM accounting_outbox",Long.class);
   for(var source:sources){UUID id=(UUID)source.get("id"),reviewer=(UUID)source.get("checker_id");String tenant=source.get("sacco_id").toString(),branch=source.get("station_id").toString();var member=Member.builder().id(reviewer).saccoId(tenant).stationId(branch).memberNo("SYNTHETIC-RESTORED").fullName("Synthetic restored checker").position(Position.MANAGER).status(MemberStatus.ACTIVE).staffAccessStatus(StaffAccessStatus.ACTIVE).build();when(restoredDirectory.find(reviewer)).thenReturn(Optional.of(member));when(restoredInstitutions.findActiveSacco(tenant)).thenReturn(Optional.of(RegisteredSacco.builder().saccoId(tenant).active(true).build()));when(restoredInstitutions.findStation(tenant,branch)).thenReturn(Optional.of(SaccoStation.builder().saccoId(tenant).stationId(branch).active(true).accessStatus(SaccoAccessStatus.ACTIVE).build()));var actor=new AppUserPrincipal(member,EnumSet.allOf(UserClaim.class),true);assertThat(service.post(actor,id,"OPENING".equals(source.get("source_type"))).id()).isEqualTo(id);assertThat(service.post(actor,id,"OPENING".equals(source.get("source_type"))).state()).isEqualTo("POSTED");}
   assertThat(restoredJdbc.queryForObject(signature,String.class)).isEqualTo(before);assertThat(restoredJdbc.queryForObject("SELECT count(*) FROM gl_journal_line",Long.class)).isEqualTo(lines);assertThat(restoredJdbc.queryForObject("SELECT count(*) FROM accounting_outbox",Long.class)).isEqualTo(events);verifyNoInteractions(restoredAudit);
  }
 }
 @SuppressWarnings("unchecked") private <T>T proxy(T target){var factory=new ProxyFactory(target);factory.setProxyTargetClass(true);factory.addAdvice(new TransactionInterceptor(manager,new AnnotationTransactionAttributeSource()));return (T)factory.getProxy();}
}
