<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="support.jspf" %>
<nav class="erp-page-path"><a href="<c:url value='${base}' />"><spring:message code="recording.register.${kind}" /></a><span>&#8250;</span><span aria-current="page"><spring:message code="recording.create.${kind}" /></span></nav>
<div class="erp-page-header"><h1 class="erp-page-title"><spring:message code="recording.create.${kind}" /></h1></div>
<div class="accounting-workspace accounting-create-workspace"><c:url value="${base}" var="postUrl" /><form:form modelAttribute="postForm" action="${postUrl}" method="post" data-loan-form="true" cssClass="accounting-create-form"><form:hidden path="requestKey" /><form:errors path="*" cssClass="loan-error-summary" element="div" role="alert" tabindex="-1" />
<section class="accounting-section"><h2><spring:message code="recording.loan" /></h2><c:choose><c:when test="${not empty detail}"><form:hidden path="loanId" /><p><c:out value="${detail.loan.number}" /> &#183; <c:out value="${detail.loan.client}" /></p><p><spring:message code="recording.outstandingPrincipal" />: TZS ${detail.loan.outstandingPrincipal} &#183; <spring:message code="recording.dueInterest" />: TZS ${detail.loan.dueInterest}</p></c:when><c:otherwise><div data-loan-choice data-category="loans"><label><spring:message code="recording.loan" /><form:select path="loanId" cssClass="aws-control" data-choice-select="true"><form:option value="" label="${chooseLabel}" /></form:select></label><%@ include file="choice-search.jspf" %></div></c:otherwise></c:choose></section>
<section class="accounting-section"><h2><spring:message code="recording.paymentDetails" /></h2><div class="loan-form-grid">
<label><spring:message code="voucher.date" /><form:input path="effectiveDate" type="date" cssClass="aws-control" required="required" /></label>
<label><spring:message code="voucher.amount" /> (TZS)<form:input path="amount" type="number" min="0.01" step="0.01" cssClass="aws-control" required="required" /></label>
<div data-loan-choice data-category="money"><label><spring:message code="recording.moneyAccount" /><form:select path="moneyAccountId" cssClass="aws-control" data-choice-select="true"><form:option value="" label="${chooseLabel}" /><c:if test="${not empty postForm.moneyAccountId}"><form:option value="${postForm.moneyAccountId}" label="${postForm.moneyAccountId}" /></c:if></form:select></label><%@ include file="choice-search.jspf" %></div>
<c:if test="${kind=='DISBURSEMENT'}"><div data-loan-choice data-category="principal"><label><spring:message code="recording.principalAccount" /><form:select path="principalAccountId" cssClass="aws-control" data-choice-select="true"><form:option value="" label="${chooseLabel}" /><c:if test="${not empty postForm.principalAccountId}"><form:option value="${postForm.principalAccountId}" label="${postForm.principalAccountId}" /></c:if></form:select></label><%@ include file="choice-search.jspf" %></div></c:if>
<c:if test="${kind=='PAYMENT'}"><div data-loan-choice data-category="interest"><label><spring:message code="recording.interestAccount" /><form:select path="interestAccountId" cssClass="aws-control" data-choice-select="true"><form:option value="" label="${chooseLabel}" /><c:if test="${not empty postForm.interestAccountId}"><form:option value="${postForm.interestAccountId}" label="${postForm.interestAccountId}" /></c:if></form:select></label><%@ include file="choice-search.jspf" %></div></c:if>
<label><spring:message code="voucher.reference" /><form:input path="reference" cssClass="aws-control" maxlength="100" required="required" /></label>
<label><spring:message code="voucher.evidence" /><form:textarea path="evidence" cssClass="aws-control" maxlength="500" rows="3" /></label>
<label><spring:message code="voucher.description" /><form:textarea path="notes" cssClass="aws-control" maxlength="500" rows="3" /></label>
</div><c:if test="${kind=='PAYMENT'}"><p><spring:message code="recording.allocationHelp" /></p></c:if></section>
<c:if test="${not empty allocationPreview}"><section class="accounting-section" data-allocation-preview><h2><spring:message code="recording.previewPosting" /></h2><dl class="loan-facts"><div><dt><spring:message code="recording.principal" /> (TZS)</dt><dd>${allocationPreview.principal}</dd></div><div><dt><spring:message code="recording.interest" /> (TZS)</dt><dd>${allocationPreview.interest}</dd></div><div><dt><spring:message code="recording.balanceAfter" /> (TZS)</dt><dd>${allocationPreview.principalBalance}</dd></div></dl></section></c:if><div class="accounting-actions loan-form-actions"><a class="app-btn btn-neutral" href="<c:url value='${base}' />"><spring:message code="common.cancel" /></a><button class="app-btn btn-neutral" name="action" value="preview"><spring:message code="recording.previewPosting" /></button><button class="app-btn btn-primary" name="action" value="post"><spring:message code="recording.post.${kind}" /></button></div></form:form></div>
<%@ include file="../accounting-form-support.jspf" %><script src="<c:url value='/js/loan-recording.js' />" defer></script><%@ include file="../../fragments/footer.jspf" %>
