<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="support.jspf" %>
<div class="accounting-workspace"><nav class="erp-page-path"><a href="<c:url value='/finance/loan-records/${posting.loanId}' />"><c:out value="${posting.loanNumber}" /></a><span>›</span><span aria-current="page"><c:out value="${posting.reference}" /></span></nav><div class="erp-page-header"><h1 class="erp-page-title"><spring:message code="recording.document.${posting.kind}" /></h1></div><c:if test="${recordingSaved}"><div class="loan-success" role="status"><spring:message code="recording.saved" /></div></c:if>
<sec:authorize access="@access.has(principal,'LOAN_RECORDING_EXPORT')"><div class="accounting-actions"><a class="app-btn btn-neutral" href="<c:url value='/finance/loan-postings/${posting.id}/pdf' />"><spring:message code="voucher.pdf" /></a><a class="app-btn btn-neutral" href="<c:url value='/finance/loan-postings/${posting.id}/print' />"><spring:message code="voucher.print" /></a></div></sec:authorize>
<section class="accounting-section"><h2><c:out value="${posting.client}" /></h2><p><spring:message code="voucher.status.${not empty posting.reversedBy?'REVERSED':posting.kind=='REVERSAL'?'REVERSAL':'POSTED'}" /></p><dl class="loan-facts">
<div><dt><spring:message code="recording.loan" /></dt><dd><c:out value="${posting.loanNumber}" /></dd></div><div><dt><spring:message code="voucher.date" /></dt><dd>${posting.date}</dd></div><div><dt><spring:message code="voucher.reference" /></dt><dd><c:out value="${posting.reference}" /></dd></div><div><dt><spring:message code="voucher.amount" /> (TZS)</dt><dd>${posting.amount}</dd></div><div><dt><spring:message code="recording.principal" /> (TZS)</dt><dd>${posting.principal}</dd></div><div><dt><spring:message code="recording.interest" /> (TZS)</dt><dd>${posting.interest}</dd></div><div><dt><spring:message code="recording.moneyAccount" /></dt><dd><c:out value="${posting.moneyAccount}" /></dd></div><div><dt><spring:message code="recording.principalAccount" /></dt><dd><c:out value="${posting.principalAccount}" /></dd></div><div><dt><spring:message code="recording.interestAccount" /></dt><dd><c:out value="${posting.interestAccount}" /></dd></div><div><dt><spring:message code="recording.balanceAfter" /> (TZS)</dt><dd>${posting.principalBalance}</dd></div><div><dt><spring:message code="voucher.evidence" /></dt><dd><c:out value="${posting.evidence}" /></dd></div><div><dt><spring:message code="voucher.description" /></dt><dd><c:out value="${posting.notes}" /></dd></div><div><dt><spring:message code="voucher.postedBy" /></dt><dd><c:out value="${posting.actor}" /></dd></div><div><dt><spring:message code="voucher.postedAt" /></dt><dd>${posting.recordedAt}</dd></div></dl>
<c:if test="${not empty posting.reversedBy}"><a href="<c:url value='/finance/loan-postings/${posting.reversedBy}' />"><spring:message code="voucher.reversal" /></a></c:if><c:if test="${not empty posting.reversesId}"><a href="<c:url value='/finance/loan-postings/${posting.reversesId}' />"><spring:message code="recording.original" /></a></c:if></section>
<c:if test="${posting.kind=='PAYMENT' and empty posting.reversedBy}"><sec:authorize access="@access.has(principal,'LOAN_RECORDING_REVERSE')"><section class="accounting-section"><h2><spring:message code="recording.reverse" /></h2><c:if test="${not empty reverseError}"><div class="loan-error-summary" role="alert"><spring:message code="${reverseError}" /></div></c:if>
<form method="post" action="<c:url value='/finance/loan-postings/${posting.id}/reverse' />" data-loan-form><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="requestKey" value="${reverseKey}" /><div class="loan-form-grid"><label><spring:message code="voucher.date" /><input class="aws-control" type="date" name="effectiveDate" value="${today}" required /></label><label><spring:message code="recording.reason" /><input class="aws-control" name="reason" value="<c:out value='${reason}' />" maxlength="500" required /></label></div><p><spring:message code="recording.reverseHelp" /></p><div class="accounting-actions loan-form-actions"><button class="app-btn btn-primary" aria-disabled="${not canReverse}" <c:if test="${not canReverse}">disabled</c:if>><spring:message code="recording.reverse" /></button></div></form></section></sec:authorize></c:if></div>
<script src="<c:url value='/js/loan-recording.js' />" defer></script><%@ include file="../../fragments/footer.jspf" %>
