<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="support.jspf" %>
<div class="accounting-workspace" data-voucher-register data-base="<c:url value='${base}' />"><div class="erp-page-header"><h1 class="erp-page-title"><spring:message code="recording.register.${kind}" /></h1></div>
<section class="erp-table-wrap"><div class="app-table-titlebar voucher-toolbar"><h2 class="erp-panel-title"><spring:message code="voucher.records" /></h2><div class="accounting-actions">
<button class="app-btn btn-neutral" data-selection-action="details" disabled><spring:message code="common.view" /></button>
<sec:authorize access="@access.has(principal,'LOAN_RECORDING_EXPORT')"><button class="app-btn btn-neutral" data-selection-action="pdf" disabled><spring:message code="voucher.pdf" /></button><button class="app-btn btn-neutral" data-selection-action="print" disabled><spring:message code="voucher.print" /></button></sec:authorize>
<sec:authorize access="@access.has(principal,'${createClaim}')"><a class="app-btn btn-primary" href="<c:url value='${base}/new' />"><spring:message code="recording.create.${kind}" /></a></sec:authorize>
</div></div>
<form class="voucher-filters"><label><spring:message code="voucher.search" /><input class="aws-control" name="search" value="<c:out value='${filter.search}' />" maxlength="100" /></label><label><spring:message code="voucher.from" /><input class="aws-control" type="date" name="from" value="${filter.from}" /></label><label><spring:message code="voucher.through" /><input class="aws-control" type="date" name="through" value="${filter.through}" /></label><label><spring:message code="voucher.status" /><select class="aws-control" name="state"><option value=""><spring:message code="voucher.all" /></option><c:forEach items="${kind=='LOAN'?['RECORDED','DISBURSED','PAR','DEFAULTED','PAID']:['POSTED','REVERSED','REVERSAL']}" var="s"><option value="${s}" ${filter.status==s?'selected':''}><spring:message code="${kind=='LOAN'?'recording':'voucher'}.status.${s}" /></option></c:forEach></select></label><label><spring:message code="voucher.sort" /><select class="aws-control" name="sort"><c:forEach items="${['newest','oldest','amount']}" var="s"><option value="${s}" ${filter.sort==s?'selected':''}><spring:message code="voucher.sort.${s}" /></option></c:forEach></select></label><button class="app-btn btn-neutral"><spring:message code="voucher.filter" /></button><a class="app-btn btn-neutral" href="<c:url value='${base}' />"><spring:message code="voucher.clear" /></a></form>
<c:if test="${kind!='LOAN'}"><div class="loan-register-totals"><p><spring:message code="voucher.total" />: TZS <fmt:formatNumber value="${totals.amount}" minFractionDigits="2" /> &#183; <spring:message code="voucher.records" />: ${totals.count}</p><sec:authorize access="@access.has(principal,'LOAN_RECORDING_EXPORT')"><c:forEach items="${['pdf','print']}" var="format"><c:url value="${base}/report/${format}" var="reportUrl"><c:param name="search" value="${filter.search}" /><c:param name="from" value="${filter.from}" /><c:param name="through" value="${filter.through}" /><c:param name="state" value="${filter.status}" /><c:param name="sort" value="${filter.sort}" /></c:url><a class="app-btn btn-neutral" href="<c:out value='${reportUrl}' />"><spring:message code="recording.report.${format}" /></a></c:forEach></sec:authorize></div></c:if>
<p class="sr-only" role="status" aria-live="polite" data-selection-status data-empty="<spring:message code='voucher.selectHelp' />" data-selected="<spring:message code='voucher.selected' />"></p>
<div class="erp-table-scroll"><table class="erp-table"><thead><tr><th><spring:message code="voucher.select" /></th><th><spring:message code="recording.loan" /></th><th><spring:message code="recording.client" /></th><th><spring:message code="voucher.date" /></th><th><spring:message code="voucher.amount" /> (TZS)</th><th><spring:message code="${kind=='LOAN'?'recording.outstandingPrincipal':'voucher.reference'}" /></th><th><spring:message code="voucher.status" /></th></tr></thead><tbody>
<c:forEach items="${records.rows}" var="r"><tr data-voucher-id="${r.id}"><td><input type="checkbox" class="voucher-select" aria-label="<spring:message code='voucher.select' /> <c:out value='${kind=="LOAN"?r.number:r.loanNumber}' />" /></td><td><a href="<c:url value='${base}/${r.id}' />"><c:out value="${kind=='LOAN'?r.number:r.loanNumber}" /></a></td><td><c:out value="${r.client}" /></td><td><c:out value="${kind=='LOAN'?r.applicationDate:r.date}" /></td><td class="voucher-numeric"><fmt:formatNumber value="${kind=='LOAN'?r.principal:r.kind=='REVERSAL'?-r.amount:r.amount}" minFractionDigits="2" maxFractionDigits="2" /></td><td><c:out value="${kind=='LOAN'?r.outstandingPrincipal:r.reference}" /></td><td><spring:message code="${kind=='LOAN'?'recording':'voucher'}.status.${kind=='LOAN'?r.status:r.kind=='REVERSAL'?'REVERSAL':empty r.reversedBy?'POSTED':'REVERSED'}" /></td></tr></c:forEach>
<c:if test="${empty records.rows}"><tr><td colspan="7"><spring:message code="voucher.noMatches" /></td></tr></c:if></tbody></table></div>
<div class="voucher-pagination"><spring:message code="voucher.page" /> ${records.page+1}<div class="accounting-actions"><c:forEach items="${[-1,1]}" var="step"><c:url value="${base}" var="pageUrl"><c:param name="page" value="${records.page+step}" /><c:param name="search" value="${filter.search}" /><c:param name="from" value="${filter.from}" /><c:param name="through" value="${filter.through}" /><c:param name="state" value="${filter.status}" /><c:param name="sort" value="${filter.sort}" /></c:url><c:choose><c:when test="${step==-1?records.page>0:records.hasNext}"><a class="app-btn btn-neutral" href="<c:out value='${pageUrl}' />"><spring:message code="${step==-1?'common.previous':'common.next'}" /></a></c:when><c:otherwise><button class="app-btn btn-neutral" disabled><spring:message code="${step==-1?'common.previous':'common.next'}" /></button></c:otherwise></c:choose></c:forEach></div></div></section></div>
<script src="<c:url value='/js/accounting-vouchers.js' />" defer></script><%@ include file="../../fragments/footer.jspf" %>
