package com.sacco.mvp.accounting.reconciliation;

import com.sacco.mvp.accounting.reconciliation.InternalTransferReconciliationSource.*;
import com.sacco.mvp.accounting.reconciliation.ReconciliationTransferProjection.*;
import org.junit.jupiter.api.Test;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;

class ReconciliationTransferProjectionTest {
    final UUID journal=UUID.randomUUID(),document=UUID.randomUUID(),policy=UUID.randomUUID(),maker=UUID.randomUUID(),checker=UUID.randomUUID(),moneyLine=UUID.randomUUID(),cash=UUID.randomUUID(),due=UUID.randomUUID();
    final LocalDate cutover=LocalDate.of(2026,10,1),through=LocalDate.of(2026,10,31),date=cutover.plusDays(1);
    final OffsetDateTime cutoff=OffsetDateTime.parse("2026-11-01T00:00:00Z"),posted=OffsetDateTime.parse("2026-10-02T12:00:00Z");
    Journal fact(){return new Journal(journal,"EXPENSE",document.toString(),policy,1,date,posted.minusMinutes(1),posted,"TZS",maker,checker,null,List.of(new Line(moneyLine,cash,"BANK",new BigDecimal("-10.00"),false),new Line(UUID.randomUUID(),due,"OTHER",new BigDecimal("10.00"),true)));}
    Leg leg(){return new Leg(document,document,journal,"B1",Direction.OUT,"TZS",new BigDecimal("10.00"),date,posted.withOffsetSameInstant(ZoneOffset.ofHours(3)),maker,checker,"a".repeat(64),moneyLine,cash,new BigDecimal("-10.00"),due,new BigDecimal("10.00"),policy,1,"B2",null);}
    Coverage valid(){return new Coverage(List.of(leg()),List.of(),true);}
    Coverage validate(List<Journal> facts,Coverage proof){return ReconciliationTransferProjection.validate("B1",cutover,through,cutoff,facts,proof);}
    @Test void owningProofMatchesExactPostedOtherPurposePolicyControlAndNormalizesTime(){var retained=validate(List.of(fact()),valid());assertThat(retained.complete()).isTrue();assertThat(retained.legs()).singleElement().satisfies(l->{assertThat(l.postedAt().getOffset()).isEqualTo(ZoneOffset.UTC);assertThat(l.signedMoneyAmount()).isEqualByComparingTo("-10.00");});}
    @Test void missingDuplicateOrInventedSourceCannotBecomeComplete(){assertThatThrownBy(()->validate(List.of(fact()),new Coverage(List.of(),List.of(),true))).hasMessage("reconciliation.error.transferSource");assertThatThrownBy(()->validate(List.of(fact()),new Coverage(List.of(leg(),leg()),List.of(),true))).hasMessage("reconciliation.error.transferSource");assertThatThrownBy(()->validate(List.of(),valid())).hasMessage("reconciliation.error.transferSource");}
    @Test void unknownManualNetZeroJournalsRemainExplicitlyIncomplete(){var original=fact();var second=UUID.randomUUID();var a=new Journal(journal,"MANUAL","MANUAL-IN",policy,1,date,posted,posted,"TZS",maker,checker,null,original.lines());var b=new Journal(second,"MANUAL","MANUAL-OUT",policy,1,date,posted,posted,"TZS",maker,checker,null,List.of(new Line(UUID.randomUUID(),cash,"BANK",new BigDecimal("10.00"),false),new Line(UUID.randomUUID(),due,"OTHER",new BigDecimal("-10.00"),true)));assertThat(validate(List.of(a,b),new Coverage(List.of(),List.of(journal,second),false)).unknownJournalIds()).containsExactlyInAnyOrder(journal,second);assertThatThrownBy(()->validate(List.of(a,b),new Coverage(List.of(),List.of(),true))).hasMessage("reconciliation.error.transferSource");assertThatThrownBy(()->validate(List.of(a),valid())).hasMessage("reconciliation.error.transferSource");}
    @Test void wrongPolicyForeignBranchOrSelfReviewIsRejected(){var f=fact();var wrong=new Journal(f.id(),f.sourceType(),f.sourceReference(),UUID.randomUUID(),1,f.effectiveDate(),f.recordedAt(),f.postedAt(),f.currency(),f.maker(),f.checker(),f.reverses(),f.lines());assertThatThrownBy(()->validate(List.of(wrong),valid())).hasMessage("reconciliation.error.transferSource");assertThatThrownBy(()->ReconciliationTransferProjection.validate("B2",cutover,through,cutoff,List.of(f),valid())).hasMessage("reconciliation.error.transferSource");var self=new Journal(f.id(),f.sourceType(),f.sourceReference(),policy,1,date,f.recordedAt(),posted,"TZS",maker,maker,null,f.lines());assertThatThrownBy(()->validate(List.of(self),valid())).hasMessage("reconciliation.error.transferSource");}
    @Test void unknownProofCannotClaimCompleteOrRepeatAnIdentifier(){assertThatThrownBy(()->validate(List.of(fact()),new Coverage(List.of(),List.of(journal),true))).hasMessage("reconciliation.error.transferSource");assertThatThrownBy(()->validate(List.of(fact()),new Coverage(List.of(),List.of(journal,journal),false))).hasMessage("reconciliation.error.transferSource");}
    @Test void futureRecordingAndReversedOwnershipCannotPublish(){var f=fact();var future=new Journal(f.id(),f.sourceType(),f.sourceReference(),policy,1,date,cutoff.plusNanos(1),posted,"TZS",maker,checker,null,f.lines());assertThatThrownBy(()->validate(List.of(future),valid())).hasMessage("reconciliation.error.transferSource");var reversal=new Journal(f.id(),f.sourceType(),f.sourceReference(),policy,1,date,f.recordedAt(),posted,"TZS",maker,checker,UUID.randomUUID(),f.lines());assertThatThrownBy(()->validate(List.of(reversal),valid())).hasMessage("reconciliation.error.transferSource");}
    @Test void nonTzsCompoundAndWrongActualLineAmountsAreRejected(){var f=fact();var foreign=new Journal(f.id(),f.sourceType(),f.sourceReference(),policy,1,date,f.recordedAt(),posted,"USD",maker,checker,null,f.lines());assertThatThrownBy(()->validate(List.of(foreign),valid())).hasMessage("reconciliation.error.transferSource");var lines=new ArrayList<>(f.lines());lines.add(new Line(UUID.randomUUID(),UUID.randomUUID(),"EXPENSE",BigDecimal.ONE,false));var compound=new Journal(f.id(),f.sourceType(),f.sourceReference(),policy,1,date,f.recordedAt(),posted,"TZS",maker,checker,null,lines);assertThatThrownBy(()->validate(List.of(compound),valid())).hasMessage("reconciliation.error.transferSource");var altered=new Journal(f.id(),f.sourceType(),f.sourceReference(),policy,1,date,f.recordedAt(),posted,"TZS",maker,checker,null,List.of(new Line(moneyLine,cash,"BANK",new BigDecimal("-11.00"),false),f.lines().getLast()));assertThatThrownBy(()->validate(List.of(altered),valid())).hasMessage("reconciliation.error.transferSource");}
    @Test void cumulativeJournalBoundFailsBeforeAnyProofIsDropped(){assertThatThrownBy(()->validate(Collections.nCopies(1001,fact()),new Coverage(List.of(),List.of(),true))).hasMessage("reconciliation.error.transferSource");}
}
