<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ include file="../../../fragments/header.jspf" %>
<%@ include file="../../../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/accounting-business.css' />" />
<div class="business-workspace"><div class="erp-page-header" data-aws-page-header><h1 class="erp-page-title"><spring:message code="finance.business.opening.review" /></h1></div>
<p class="business-gate"><spring:message code="finance.business.opening.gate" /></p><c:if test="${not empty openingError}"><div class="business-error" role="alert"><spring:message code="${openingError}" /></div></c:if>
<dl><dt><spring:message code="finance.business.opening.accountCode" /></dt><dd><c:out value="${accountLabel}" /></dd><dt><spring:message code="finance.business.type" /></dt><dd><spring:message code="finance.business.opening.purpose.${opening.preview.command.purpose}" /></dd><dt><spring:message code="finance.business.opening.through" /></dt><dd><c:out value="${opening.preview.command.through}" /></dd><dt><spring:message code="finance.business.opening.total" /></dt><dd>TZS <c:out value="${opening.preview.signedBalance}" /></dd><dt><spring:message code="finance.business.status" /></dt><dd><c:choose><c:when test="${empty opening.decision}"><spring:message code="finance.business.opening.pending" /></c:when><c:otherwise><spring:message code="finance.business.opening.state.${opening.decision}" /></c:otherwise></c:choose></dd><dt><spring:message code="finance.business.opening.evidence" /></dt><dd><c:out value="${opening.preview.command.evidence}" /></dd>
<c:if test="${not empty opening.reviewEvidence}"><dt><spring:message code="finance.business.opening.reviewEvidence" /></dt><dd><c:out value="${opening.reviewEvidence}" /></dd></c:if></dl>
<p><c:choose><c:when test="${opening.preview.command.completeCoverage}"><spring:message code="finance.business.opening.coverageDeclared" /></c:when><c:otherwise><spring:message code="finance.business.opening.coverageIncomplete" /></c:otherwise></c:choose></p><c:if test="${empty opening.preview.command.generalLedgerOpening}"><p><spring:message code="finance.business.opening.missingGl" /></p></c:if>
<div class="business-actions"><a class="app-btn btn-neutral" href="<c:url value='/finance/business/openings/${opening.id}/file' />"><spring:message code="finance.business.opening.download" /></a></div>
<section class="erp-table-wrap" data-aws-table-region><div class="app-table-titlebar"><h2><spring:message code="finance.business.opening.registers" /></h2><span><spring:message code="finance.business.opening.rowCount" />: <c:out value="${opening.preview.rows.size()}" /></span></div><div class="erp-table-scroll" data-view-position-key="source-opening-rows"><table class="erp-table"><thead><tr><th><spring:message code="finance.business.opening.reference" /></th><th class="business-money">TZS</th><th><spring:message code="finance.business.opening.evidence" /></th></tr></thead><tbody><c:forEach items="${rows}" var="r"><tr><td><c:out value="${r.reference}" /></td><td class="business-money"><c:out value="${r.signedBalance}" /></td><td><c:out value="${r.evidence}" /></td></tr></c:forEach><c:if test="${empty opening.preview.rows}"><tr><td colspan="3"><spring:message code="finance.business.opening.explicitZero" /></td></tr></c:if></tbody></table></div><div class="business-actions"><c:if test="${rowPage>0}"><a class="app-btn btn-neutral" href="<c:url value='/finance/business/openings/${opening.id}?page=${rowPage-1}' />"><spring:message code="common.previous" /></a></c:if><span><spring:message code="repayment.page" /> <c:out value="${rowPage+1}" /></span><c:if test="${hasNext}"><a class="app-btn btn-neutral" href="<c:url value='/finance/business/openings/${opening.id}?page=${rowPage+1}' />"><spring:message code="common.next" /></a></c:if></div></section>
<c:if test="${empty opening.decision and independentReviewer}"><sec:authorize access="@access.has(principal,'ACCOUNTING_BUSINESS_APPROVE')"><form method="post" action="<c:url value='/finance/business/openings/${opening.id}/review' />" class="business-form"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
<label><spring:message code="finance.business.opening.reviewEvidence" /><input name="evidence" maxlength="500" value="<c:out value='${reviewEvidence}' />" required /></label><label class="business-confirm"><input name="confirmed" type="checkbox" value="true" required /><span><spring:message code="finance.business.opening.confirm" /></span></label><div class="business-actions"><c:if test="${opening.preview.command.completeCoverage and not empty opening.preview.command.generalLedgerOpening}"><button class="app-btn btn-primary" type="submit" name="decision" value="APPROVED"><spring:message code="finance.business.opening.approve" /></button></c:if><button class="app-btn btn-neutral" type="submit" name="decision" value="REJECTED"><spring:message code="finance.business.opening.reject" /></button></div></form></sec:authorize></c:if>
</div><%@ include file="../../../fragments/footer.jspf" %>
