package com.sacco.mvp.accounting.reports;

import com.sacco.mvp.accounting.policy.AccountingPolicyService;
import com.sacco.mvp.domain.*;
import com.sacco.mvp.security.AppUserPrincipal;
import com.sacco.mvp.service.*;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.aop.framework.ProxyFactory;
import org.springframework.jdbc.core.*;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.*;
import org.springframework.transaction.annotation.AnnotationTransactionAttributeSource;
import org.springframework.transaction.interceptor.TransactionInterceptor;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.security.access.AccessDeniedException;
import tools.jackson.databind.json.JsonMapper;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static com.sacco.mvp.accounting.reports.LedgerReportService.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@EnabledIfEnvironmentVariable(named="MICROFINANCE_ACCOUNTING_E_DATABASE_URL",matches="(?:(?:jdbc:postgresql://127\\.0\\.0\\.1:[0-9]+/microfinance_accounting_e_test_portfolio_20261003_v[12]|jdbc:postgresql://127\\.0\\.0\\.1:55439/microfinance_accounting_h_release_combined_test_20261004)|jdbc:postgresql://127\\.0\\.0\\.1:55439/microfinance_accounting_h_release_integrity_test_20261004)")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class LoanPortfolioReportPostgresTest {
    static final LocalDate DAY=LocalDate.of(2026,10,3);
    JdbcTemplate jdbc;TransactionTemplate tx;LoanPortfolioReportRepository repository;LoanPortfolioReportService service;
    MemberDirectoryService members;UserClaimService claims;SaccoRegistryService institutions;ApplicationClock clock;
    String institution;AppUserPrincipal actor;Scope branch,wide;Parameters p;int number;
    @BeforeAll void start(){var ds=new DriverManagerDataSource(System.getenv("MICROFINANCE_ACCOUNTING_E_DATABASE_URL"),"microfinance_test","");Flyway.configure().dataSource(ds).locations("classpath:db/migration").load().migrate();jdbc=new JdbcTemplate(ds);var manager=new DataSourceTransactionManager(ds);tx=new TransactionTemplate(manager);
        members=mock(MemberDirectoryService.class);claims=mock(UserClaimService.class);institutions=mock(SaccoRegistryService.class);clock=mock(ApplicationClock.class);
        var books=new LedgerReportRepository(new NamedParameterJdbcTemplate(jdbc));var access=new LedgerReportService(books,mock(AccountingPolicyService.class),members,claims,institutions,clock);repository=new LoanPortfolioReportRepository(new NamedParameterJdbcTemplate(jdbc));var proxy=new ProxyFactory(new LoanPortfolioReportService(access,books,repository));proxy.setProxyTargetClass(true);proxy.addAdvice(new TransactionInterceptor(manager,new AnnotationTransactionAttributeSource()));service=(LoanPortfolioReportService)proxy.getProxy();}
    @BeforeEach void fixture(){reset(members,claims,institutions,clock);institution="PORTFOLIO-"+UUID.randomUUID();number=1000;
        jdbc.update("insert into registered_saccos(sacco_id,sacco_name,active,created_at,updated_at) values(?,?,true,now(),now())",institution,"Synthetic portfolio tests");
        for(String b:List.of("B1","B2")){jdbc.update("insert into sacco_stations(id,sacco_id,station_id,active,created_at,updated_at,access_status) values(?,?,?,true,now(),now(),'ACTIVE')",UUID.randomUUID(),institution,b);when(institutions.findStation(institution,b)).thenReturn(Optional.of(SaccoStation.builder().saccoId(institution).stationId(b).active(true).accessStatus(SaccoAccessStatus.ACTIVE).build()));}
        UUID staff=UUID.randomUUID();jdbc.update("insert into members(id,sacco_id,station_id,member_no,full_name,status,position,created_at,is_member,password_hash) values(?,?,'B1',?,'Synthetic staff','ACTIVE','MANAGER',now(),false,'test-only')",staff,institution,staff.toString());var m=Member.builder().id(staff).saccoId(institution).stationId("B1").memberNo(staff.toString()).position(Position.MANAGER).status(MemberStatus.ACTIVE).memberAccount(false).build();actor=new AppUserPrincipal(m,EnumSet.allOf(UserClaim.class),true);when(members.find(staff)).thenReturn(Optional.of(m));when(claims.effectiveClaims(any(),anyCollection(),anyBoolean())).thenReturn(EnumSet.allOf(UserClaim.class));when(institutions.findActiveSacco(institution)).thenReturn(Optional.of(RegisteredSacco.builder().saccoId(institution).active(true).build()));when(clock.today()).thenReturn(DAY);when(clock.now()).thenAnswer(i->OffsetDateTime.now());branch=new Scope(institution,"B1",false);wide=new Scope(institution,"B1",true);p=new Parameters(DAY.minusDays(100),DAY,OffsetDateTime.now().plusSeconds(1),0);}
    record Loan(UUID id,UUID installment,BigDecimal principal,BigDecimal interest,LocalDate due) { }
    Loan loan(String b,String principal,String interest,int dpd,boolean origin){return loan(b,principal,interest,dpd,origin,new BigDecimal(principal));}
    Loan loan(String b,String principal,String interest,int dpd,boolean origin,BigDecimal duePrincipal){UUID id=UUID.randomUUID(),installment=UUID.randomUUID();BigDecimal amount=new BigDecimal(principal),i=new BigDecimal(interest);LocalDate disbursed=DAY.minusDays(100),due=DAY.minusDays(dpd);int n=number++;
        var schedule=new ArrayList<Map<String,Object>>();schedule.add(Map.of("dueDate",due.toString(),"principalComponent",duePrincipal,"interestComponent",i,"amount",duePrincipal.add(i)));if(duePrincipal.compareTo(amount)<0)schedule.add(Map.of("dueDate",DAY.plusDays(30).toString(),"principalComponent",amount.subtract(duePrincipal),"interestComponent",BigDecimal.ZERO,"amount",amount.subtract(duePrincipal)));var json=JsonMapper.builder().build().writeValueAsString(Map.of("schedule",schedule));
        tx.executeWithoutResult(s->{jdbc.update("insert into loan_applications(id,amount,applicant_member_id,created_at,updated_at,disbursement_date,form_data,loan_type,policy_snapshot,repayment_schedule_json,required_guarantors,sacco_id,station_id,status,tenor_months,version,loan_id,application_number) values(?,?,?,now(),now(),?,'{}','DEVELOPMENT_LOAN','{}',?::jsonb,0,?,?,'DISBURSED',1,0,?,?)",id,amount,actor.getMemberId(),disbursed,json,institution,b,Integer.toString(n),n);jdbc.update("insert into loan_ledgers(loan_application_id,sacco_id,station_id,loan_id,applicant_member_id,disbursement_date,principal,created_at) values(?,?,?,?,?,?,?,now())",id,institution,b,Integer.toString(n),actor.getMemberId(),disbursed,amount);jdbc.update("insert into loan_ledger_installments(id,loan_application_id,installment_number,due_date,principal,interest) values(?,?,1,?,?,?)",installment,id,due,duePrincipal,i);if(duePrincipal.compareTo(amount)<0)jdbc.update("insert into loan_ledger_installments(id,loan_application_id,installment_number,due_date,principal,interest) values(?,?,2,?,?,0)",UUID.randomUUID(),id,DAY.plusDays(30),amount.subtract(duePrincipal));if(origin){UUID voucher=UUID.randomUUID();journal(id,null,voucher,"LOAN_PRINCIPAL",amount,BigDecimal.ZERO,disbursed);journal(id,null,voucher,"DISBURSEMENT_CLEARING",BigDecimal.ZERO,amount,disbursed);}});return new Loan(id,installment,amount,i,due);}
    void journal(UUID loan,UUID transaction,UUID voucher,String code,BigDecimal debit,BigDecimal credit,LocalDate date){jdbc.update("insert into loan_journal_entries(id,loan_application_id,transaction_id,voucher_id,account_code,debit,credit,effective_date,posted_at) values(?,?,?,?,?,?,?,?,now())",UUID.randomUUID(),loan,transaction,voucher,code,debit,credit,date);}
    UUID payment(Loan loan,String b,String principal,String interest,LocalDate date,UUID reverses,boolean allocations){UUID id=UUID.randomUUID();BigDecimal a=new BigDecimal(principal),i=new BigDecimal(interest);boolean reverse=reverses!=null;
        tx.executeWithoutResult(s->{jdbc.update("insert into loan_repayment_transactions(id,loan_application_id,sacco_id,station_id,sequence,receipt_reference,request_key,kind,channel,channel_reference,payment_date,amount,principal_amount,interest_amount,actor_member_id,reverses_transaction_id,reason,loan_status_before,posted_at) values(?,?,?,?,?,?,?,?, 'CASH',?,?,?,?,?,?,?,?,'DISBURSED',now())",id,loan.id(),institution,b,reverse?2:1,id.toString(),UUID.randomUUID(),reverse?"REVERSAL":"PAYMENT",id.toString(),date,a.add(i),a,i,actor.getMemberId(),reverses,reverse?"Synthetic reversal":null);if(allocations)jdbc.update("insert into loan_repayment_allocations(id,transaction_id,installment_id,principal_amount,interest_amount) values(?,?,?,?,?)",UUID.randomUUID(),id,loan.installment(),a,i);journal(loan.id(),id,id,"CASH_CLEARING",reverse?BigDecimal.ZERO:a.add(i),reverse?a.add(i):BigDecimal.ZERO,date);if(a.signum()>0)journal(loan.id(),id,id,"LOAN_PRINCIPAL",reverse?a:BigDecimal.ZERO,reverse?BigDecimal.ZERO:a,date);if(i.signum()>0)journal(loan.id(),id,id,"INTEREST_COLLECTIONS_CLEARING",reverse?i:BigDecimal.ZERO,reverse?BigDecimal.ZERO:i,date);});return id;}
    Parameters cutoff(){return new Parameters(p.from(),p.through(),OffsetDateTime.now(),0);}
    @Test void principalWeightedParAndInterestOnlyArrearsUseWholeExposure(){var late=loan("B1","1000.01","1.00",31,true,new BigDecimal("100.01"));loan("B2","9000.00","0.00",0,true);payment(late,"B1","100.01","0.00",DAY,null,true);var summary=repository.summary(wide,cutoff());assertThat(summary.covered()).isEqualTo(2);assertThat(summary.principal()).isEqualByComparingTo("9900.00");assertThat(summary.par30()).isEqualByComparingTo("900.00");assertThat(summary.overduePrincipal()).isZero();assertThat(summary.overdueInterest()).isEqualByComparingTo("1.00");assertThat(repository.rows(branch,cutoff())).singleElement().satisfies(r->assertThat(r.oldest()).isEqualTo(DAY.minusDays(31)));}
    @Test void latePrincipalUsesEntireBalanceAndNeverAveragesBranches(){loan("B1","1000.01","1.00",31,true);loan("B2","9000.00","0.00",0,true);var s=repository.summary(wide,cutoff());assertThat(s.par30()).isEqualByComparingTo("1000.01");assertThat(LoanRiskMetrics.percentage(s.par30(),s.principal())).isEqualByComparingTo("10.000090");assertThat(repository.branches(wide,cutoff())).hasSize(2);assertThat(repository.rows(branch,cutoff())).hasSize(1);assertThatThrownBy(()->repository.rows(wide,cutoff())).isInstanceOf(IllegalArgumentException.class);}
    @Test void signedReversalAndRecordedCutoffIgnoreMutablePaidAndStatusProjections(){var l=loan("B1","100.01","5.00",31,true);var payment=payment(l,"B1","25.01","5.00",DAY.minusDays(1),null,true);var old=cutoff();jdbc.update("update loan_ledgers set principal_paid=principal,interest_paid=500 where loan_application_id=?",l.id());jdbc.update("update loan_ledger_installments set principal_paid=principal,interest_paid=interest where id=?",l.installment());jdbc.update("update loan_applications set status='PAID' where id=?",l.id());payment(l,"B1","25.01","5.00",DAY,payment,true);assertThat(repository.summary(branch,old).principal()).isEqualByComparingTo("75.00");var now=repository.summary(branch,cutoff());assertThat(now.principal()).isEqualByComparingTo("100.01");assertThat(now.collectedPrincipal()).isZero();assertThat(now.collectedInterest()).isZero();assertThat(now.overdueInterest()).isEqualByComparingTo("5.00");}
    @Test void missingOriginOrAllocationIsExcludedAndUnreviewedOpeningBlocksHeadline(){loan("B1","100.00","1.00",31,false);var l=loan("B1","100.00","1.00",31,true);payment(l,"B1","1.00","0.00",DAY,null,false);loan("B1","100.00","1.00",0,true);var result=service.report(actor,cutoff(),false);assertThat(result.summary().excluded()).isEqualTo(2);assertThat(result.summary().covered()).isEqualTo(1);assertThat(result.ratios().par1()).isNull();assertThat(result.rows().stream().filter(r->!r.complete())).allSatisfy(r->assertThat(r.principal()).isNull());}
    @Test void sourceBranchesClaimsAndCurrentMembershipAreRechecked(){loan("B2","500.00","1.00",91,true);assertThat(service.report(actor,cutoff(),false).rows()).isEmpty();var global=service.report(actor,cutoff(),true);assertThat(global.rows()).isEmpty();assertThat(global.summary().principal()).isEqualByComparingTo("500.00");when(claims.effectiveClaims(any(),anyCollection(),anyBoolean())).thenReturn(Set.of(UserClaim.FINANCIAL_REPORTS_VIEW,UserClaim.LOAN_REPORTS_VIEW));assertThatThrownBy(()->service.report(actor,cutoff(),true)).isInstanceOf(AccessDeniedException.class);when(claims.effectiveClaims(any(),anyCollection(),anyBoolean())).thenReturn(Set.of(UserClaim.FINANCIAL_REPORTS_VIEW));assertThatThrownBy(()->service.report(actor,cutoff(),false)).isInstanceOf(AccessDeniedException.class);}
    @Test void pageRowsRemainBoundedWhileTotalsCoverAllSources(){for(int i=0;i<31;i++)loan("B1","0.01","0.00",0,true);var first=service.report(actor,cutoff(),false);assertThat(first.rows()).hasSize(25);assertThat(first.hasNext()).isTrue();assertThat(first.summary().principal()).isEqualByComparingTo("0.31");var second=service.report(actor,new Parameters(p.from(),p.through(),OffsetDateTime.now(),1),false);assertThat(second.rows()).hasSize(6);assertThat(second.hasNext()).isFalse();assertThat(second.summary().principal()).isEqualByComparingTo("0.31");}
    @Test void unverifiedLegacyLoanWithoutLedgerIsMissingRatherThanZeroExposure(){var l=loan("B1","100.00","1.00",31,true);int n=number++;jdbc.update("insert into loan_applications(id,amount,applicant_member_id,created_at,updated_at,disbursement_date,form_data,loan_type,policy_snapshot,repayment_schedule_json,required_guarantors,sacco_id,station_id,status,tenor_months,version,loan_id,application_number) select ?,amount,applicant_member_id,created_at,updated_at,disbursement_date,form_data,loan_type,policy_snapshot,repayment_schedule_json,required_guarantors,sacco_id,station_id,status,tenor_months,version,?,? from loan_applications where id=?",UUID.randomUUID(),Integer.toString(n),n,l.id());var result=service.report(actor,cutoff(),false);assertThat(result.summary().covered()).isEqualTo(1);assertThat(result.summary().excluded()).isEqualTo(1);assertThat(result.ratios().par30()).isNull();}
    @Test void extraOrMalformedContractTermsAreUnavailableRatherThanCleanRisk(){var l=loan("B1","100.00","1.00",31,true);jdbc.update("insert into loan_ledger_installments(id,loan_application_id,installment_number,due_date,principal,interest) values(?,?,2,?,0,1)",UUID.randomUUID(),l.id(),DAY.minusDays(20));var bad=loan("B1","100.00","1.00",0,true);jdbc.update("update loan_applications set repayment_schedule_json='{\"schedule\":[{\"dueDate\":\"2026-10-03\",\"principalComponent\":\"bad\",\"interestComponent\":0}]}' where id=?",bad.id());assertThat(repository.summary(branch,cutoff()).excluded()).isEqualTo(2);}
    @Test void managementAndOrdinaryReferenceBandsHaveDistinctFiveSixAndThirtyBoundaries(){loan("B1","10.00","1.00",5,true);loan("B1","20.00","1.00",6,true);loan("B1","40.00","1.00",30,true);loan("B1","80.00","1.00",31,true);assertThat(repository.buckets(branch,cutoff(),false)).anySatisfy(b->{assertThat(b.band()).isEqualTo(1);assertThat(b.principal()).isEqualByComparingTo("70.00");});assertThat(repository.buckets(branch,cutoff(),true)).anySatisfy(b->{assertThat(b.band()).isEqualTo(0);assertThat(b.principal()).isEqualByComparingTo("10.00");});assertThat(repository.summary(branch,cutoff()).par30()).isEqualByComparingTo("80.00");}
}
