package com.sacco.mvp.domain;

public enum EmailOtpPurpose {
    LOGIN,
    STAFF_LOGIN,
    STAFF_LOGIN_MFA,
    REGISTRATION,
    PASSWORD_RESET,
    APPLICANT_SIGNATURE,
    LOAN_APPLICATION_FORFEIT,
    PAYMENT_DETAILS_CHANGE,
    GUARANTOR_SIGNATURE,
    BOARD_SIGNATURE,
    CLAIM_ACCOUNT,
    CLAIM_PHONE
}
