package com.sacco.mvp.domain;

public enum EmailOtpPurpose {
    LOGIN,
    STAFF_LOGIN,
    STAFF_LOGIN_MFA,
    REGISTRATION,
    APPLICANT_SIGNATURE,
    LOAN_APPLICATION_FORFEIT,
    GUARANTOR_SIGNATURE,
    BOARD_SIGNATURE,
    CLAIM_ACCOUNT
}
