package com.sacco.mvp.domain;

public enum UserClaim {
    APPLY_LOANS,
    APPROVE_GUARANTOR_REQUESTS,
    REVIEW_MANAGER_QUEUE,
    REVIEW_ACCOUNTANT_QUEUE,
    ACCESS_DISBURSEMENT_QUEUE,
    DISBURSE_LOAN,
    REVIEW_BOARD_QUEUE,
    REVIEW_LOAN_OFFICER_QUEUE,
    ACCESS_ADMIN_SETTINGS,
    ACCESS_OUTBOX_MONITOR
}
