package com.sacco.mvp.domain;

public enum UserClaim {
    APPLY_LOANS,
    APPROVE_GUARANTOR_REQUESTS,
    REVIEW_MANAGER_QUEUE,
    REVIEW_BOARD_QUEUE,
    VIEW_CHAIRPERSON_PANEL,
    ACCESS_ADMIN_SETTINGS,
    ACCESS_OUTBOX_MONITOR
}
