ALTER TABLE IF EXISTS loan_applications
    DROP CONSTRAINT IF EXISTS loan_applications_status_check;

ALTER TABLE IF EXISTS loan_applications
    ADD CONSTRAINT loan_applications_status_check
    CHECK (status IN (
        'DRAFT','SUBMITTED','AWAITING_GUARANTORS','ALL_GUARANTORS_APPROVED','READY_FOR_MANAGER',
        'MANAGER_REJECTED','MANAGER_ACCEPTED','AWAITING_BOARD','BOARD_REJECTED','BOARD_APPROVED',
        'FINAL_REJECTED','FINAL_APPROVED','DEFAULTED','PAID'
    ));
