CREATE TABLE IF NOT EXISTS public.member_access_claims (
    member_id uuid NOT NULL,
    claim_name varchar(120) NOT NULL,
    CONSTRAINT member_access_claims_pkey PRIMARY KEY (member_id, claim_name),
    CONSTRAINT member_access_claims_member_fk FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_member_access_claims_claim_name
    ON public.member_access_claims (claim_name);

WITH valid_claims(claim_name) AS (
    VALUES
        ('ACCESS_MATRIX_VIEW'), ('ACCESS_MATRIX_UPDATE'),
        ('USER_ACCESS_VIEW'), ('USER_ACCESS_CREATE'), ('USER_ACCESS_UPDATE'), ('USER_ACCESS_DELETE'),
        ('ADMIN_DASHBOARD_VIEW'),
        ('SACCO_REGISTRY_VIEW'), ('SACCO_REGISTRY_CREATE'), ('SACCO_REGISTRY_UPDATE'), ('SACCO_REGISTRY_DELETE'),
        ('PLATFORM_SETTINGS_VIEW'), ('PLATFORM_SETTINGS_UPDATE'),
        ('WORKSPACE_SETTINGS_VIEW'), ('WORKSPACE_SETTINGS_UPDATE'), ('WORKSPACE_SETTINGS_CONFIGURE'),
        ('LOAN_PRODUCTS_VIEW'), ('LOAN_PRODUCTS_CREATE'), ('LOAN_PRODUCTS_UPDATE'), ('LOAN_PRODUCTS_CONFIGURE'), ('LOAN_PRODUCTS_DELETE'),
        ('APPROVAL_FLOW_VIEW'), ('APPROVAL_FLOW_CONFIGURE'),
        ('SMS_USAGE_VIEW'), ('SMS_USAGE_ADD'), ('SMS_USAGE_CONFIGURE'),
        ('OUTBOX_VIEW'), ('OUTBOX_UPDATE'),
        ('MEMBER_SETTINGS_VIEW'), ('MEMBER_SETTINGS_UPDATE'),
        ('PAYMENT_DETAILS_VIEW'), ('PAYMENT_DETAILS_UPDATE'),
        ('MEMBER_LOANS_VIEW'), ('MEMBER_LOANS_CREATE'), ('MEMBER_LOANS_UPDATE'), ('MEMBER_LOANS_ASSIGN'), ('MEMBER_LOANS_DELETE'),
        ('GUARANTOR_REQUESTS_VIEW'), ('GUARANTOR_REQUESTS_UPDATE'), ('GUARANTOR_REQUESTS_APPROVE'), ('GUARANTOR_REQUESTS_REJECT'),
        ('LOAN_DOCUMENTS_VIEW'), ('LOAN_DOCUMENTS_CREATE'), ('LOAN_DOCUMENTS_EXPORT'),
        ('STAFF_ANALYTICS_VIEW'), ('STAFF_ANALYTICS_EXPORT'),
        ('LOAN_OFFICER_QUEUE_VIEW'), ('LOAN_OFFICER_QUEUE_ASSIGN'), ('LOAN_OFFICER_QUEUE_APPROVE'),
        ('LOAN_OFFICER_QUEUE_REJECT'), ('LOAN_OFFICER_QUEUE_UPDATE'), ('LOAN_OFFICER_QUEUE_EXPORT'),
        ('MANAGER_QUEUE_VIEW'), ('MANAGER_QUEUE_ASSIGN'), ('MANAGER_QUEUE_APPROVE'), ('MANAGER_QUEUE_REJECT'),
        ('MANAGER_QUEUE_UPDATE'), ('MANAGER_QUEUE_EXPORT'),
        ('ACCOUNTANT_QUEUE_VIEW'), ('ACCOUNTANT_QUEUE_ASSIGN'), ('ACCOUNTANT_QUEUE_APPROVE'),
        ('ACCOUNTANT_QUEUE_REJECT'), ('ACCOUNTANT_QUEUE_UPDATE'), ('ACCOUNTANT_QUEUE_EXPORT'),
        ('BOARD_QUEUE_VIEW'), ('BOARD_QUEUE_ASSIGN'), ('BOARD_QUEUE_APPROVE'), ('BOARD_QUEUE_REJECT'),
        ('BOARD_QUEUE_UPDATE'), ('BOARD_QUEUE_EXPORT'),
        ('CHAIRPERSON_QUEUE_VIEW'), ('CHAIRPERSON_QUEUE_ASSIGN'), ('CHAIRPERSON_QUEUE_APPROVE'),
        ('CHAIRPERSON_QUEUE_REJECT'), ('CHAIRPERSON_QUEUE_UPDATE'), ('CHAIRPERSON_QUEUE_EXPORT'),
        ('CREDIT_COMMITTEE_QUEUE_VIEW'), ('CREDIT_COMMITTEE_QUEUE_ASSIGN'), ('CREDIT_COMMITTEE_QUEUE_APPROVE'),
        ('CREDIT_COMMITTEE_QUEUE_REJECT'), ('CREDIT_COMMITTEE_QUEUE_UPDATE'), ('CREDIT_COMMITTEE_QUEUE_EXPORT'),
        ('DISBURSEMENT_QUEUE_VIEW'), ('DISBURSEMENT_QUEUE_UPDATE'), ('DISBURSEMENT_QUEUE_EXPORT'), ('DISBURSEMENT_QUEUE_DISBURSE'),
        ('LOAN_REPORTS_VIEW'), ('LOAN_REPORTS_EXPORT'),
        ('NOTIFICATIONS_VIEW'), ('NOTIFICATIONS_UPDATE'),
        ('SUPPORT_VIEW'), ('SUPPORT_CREATE'), ('SUPPORT_UPDATE')
),
legacy_claim_map(legacy_claim, claim_name) AS (
    VALUES
        ('APPLY_LOANS', 'MEMBER_LOANS_VIEW'), ('APPLY_LOANS', 'MEMBER_LOANS_CREATE'), ('APPLY_LOANS', 'MEMBER_LOANS_UPDATE'),
        ('APPLY_LOANS', 'MEMBER_SETTINGS_VIEW'), ('APPLY_LOANS', 'MEMBER_SETTINGS_UPDATE'),
        ('APPLY_LOANS', 'PAYMENT_DETAILS_VIEW'), ('APPLY_LOANS', 'PAYMENT_DETAILS_UPDATE'),
        ('APPLY_LOANS', 'MEMBER_LOANS_ASSIGN'), ('APPLY_LOANS', 'MEMBER_LOANS_DELETE'),
        ('APPLY_LOANS', 'LOAN_DOCUMENTS_VIEW'), ('APPLY_LOANS', 'LOAN_DOCUMENTS_CREATE'), ('APPLY_LOANS', 'LOAN_DOCUMENTS_EXPORT'),
        ('APPLY_LOANS', 'LOAN_REPORTS_VIEW'), ('APPLY_LOANS', 'LOAN_REPORTS_EXPORT'),
        ('APPLY_LOANS', 'NOTIFICATIONS_VIEW'), ('APPLY_LOANS', 'NOTIFICATIONS_UPDATE'), ('APPLY_LOANS', 'SUPPORT_VIEW'), ('APPLY_LOANS', 'SUPPORT_CREATE'),
        ('APPROVE_GUARANTOR_REQUESTS', 'GUARANTOR_REQUESTS_VIEW'), ('APPROVE_GUARANTOR_REQUESTS', 'GUARANTOR_REQUESTS_UPDATE'),
        ('APPROVE_GUARANTOR_REQUESTS', 'GUARANTOR_REQUESTS_APPROVE'),
        ('APPROVE_GUARANTOR_REQUESTS', 'GUARANTOR_REQUESTS_REJECT'), ('APPROVE_GUARANTOR_REQUESTS', 'NOTIFICATIONS_VIEW'),
        ('APPROVE_GUARANTOR_REQUESTS', 'NOTIFICATIONS_UPDATE'), ('APPROVE_GUARANTOR_REQUESTS', 'SUPPORT_VIEW'), ('APPROVE_GUARANTOR_REQUESTS', 'SUPPORT_CREATE'),
        ('REVIEW_MANAGER_QUEUE', 'MANAGER_QUEUE_VIEW'), ('REVIEW_MANAGER_QUEUE', 'MANAGER_QUEUE_APPROVE'), ('REVIEW_MANAGER_QUEUE', 'MANAGER_QUEUE_REJECT'),
        ('REVIEW_MANAGER_QUEUE', 'MANAGER_QUEUE_UPDATE'), ('REVIEW_MANAGER_QUEUE', 'MANAGER_QUEUE_EXPORT'),
        ('REVIEW_ACCOUNTANT_QUEUE', 'ACCOUNTANT_QUEUE_VIEW'), ('REVIEW_ACCOUNTANT_QUEUE', 'ACCOUNTANT_QUEUE_APPROVE'), ('REVIEW_ACCOUNTANT_QUEUE', 'ACCOUNTANT_QUEUE_REJECT'),
        ('REVIEW_ACCOUNTANT_QUEUE', 'ACCOUNTANT_QUEUE_UPDATE'), ('REVIEW_ACCOUNTANT_QUEUE', 'ACCOUNTANT_QUEUE_EXPORT'),
        ('ACCESS_DISBURSEMENT_QUEUE', 'DISBURSEMENT_QUEUE_VIEW'), ('ACCESS_DISBURSEMENT_QUEUE', 'DISBURSEMENT_QUEUE_UPDATE'), ('ACCESS_DISBURSEMENT_QUEUE', 'DISBURSEMENT_QUEUE_EXPORT'),
        ('DISBURSE_LOAN', 'DISBURSEMENT_QUEUE_VIEW'), ('DISBURSE_LOAN', 'DISBURSEMENT_QUEUE_DISBURSE'), ('DISBURSE_LOAN', 'DISBURSEMENT_QUEUE_UPDATE'),
        ('REVIEW_CHAIRPERSON_QUEUE', 'CHAIRPERSON_QUEUE_VIEW'), ('REVIEW_CHAIRPERSON_QUEUE', 'CHAIRPERSON_QUEUE_APPROVE'), ('REVIEW_CHAIRPERSON_QUEUE', 'CHAIRPERSON_QUEUE_REJECT'),
        ('REVIEW_CHAIRPERSON_QUEUE', 'CHAIRPERSON_QUEUE_UPDATE'), ('REVIEW_CHAIRPERSON_QUEUE', 'CHAIRPERSON_QUEUE_EXPORT'),
        ('REVIEW_BOARD_QUEUE', 'BOARD_QUEUE_VIEW'), ('REVIEW_BOARD_QUEUE', 'BOARD_QUEUE_APPROVE'), ('REVIEW_BOARD_QUEUE', 'BOARD_QUEUE_REJECT'),
        ('REVIEW_BOARD_QUEUE', 'BOARD_QUEUE_UPDATE'), ('REVIEW_BOARD_QUEUE', 'BOARD_QUEUE_EXPORT'),
        ('REVIEW_CREDIT_COMMITTEE_QUEUE', 'CREDIT_COMMITTEE_QUEUE_VIEW'), ('REVIEW_CREDIT_COMMITTEE_QUEUE', 'CREDIT_COMMITTEE_QUEUE_APPROVE'),
        ('REVIEW_CREDIT_COMMITTEE_QUEUE', 'CREDIT_COMMITTEE_QUEUE_REJECT'), ('REVIEW_CREDIT_COMMITTEE_QUEUE', 'CREDIT_COMMITTEE_QUEUE_UPDATE'),
        ('REVIEW_CREDIT_COMMITTEE_QUEUE', 'CREDIT_COMMITTEE_QUEUE_EXPORT'),
        ('REVIEW_LOAN_OFFICER_QUEUE', 'LOAN_OFFICER_QUEUE_VIEW'), ('REVIEW_LOAN_OFFICER_QUEUE', 'LOAN_OFFICER_QUEUE_ASSIGN'),
        ('REVIEW_LOAN_OFFICER_QUEUE', 'LOAN_OFFICER_QUEUE_APPROVE'), ('REVIEW_LOAN_OFFICER_QUEUE', 'LOAN_OFFICER_QUEUE_REJECT'),
        ('REVIEW_LOAN_OFFICER_QUEUE', 'LOAN_OFFICER_QUEUE_UPDATE'), ('REVIEW_LOAN_OFFICER_QUEUE', 'LOAN_OFFICER_QUEUE_EXPORT'),
        ('ACCESS_ADMIN_SETTINGS', 'ACCESS_MATRIX_VIEW'), ('ACCESS_ADMIN_SETTINGS', 'ACCESS_MATRIX_UPDATE'),
        ('ACCESS_ADMIN_SETTINGS', 'USER_ACCESS_VIEW'), ('ACCESS_ADMIN_SETTINGS', 'USER_ACCESS_CREATE'), ('ACCESS_ADMIN_SETTINGS', 'USER_ACCESS_UPDATE'), ('ACCESS_ADMIN_SETTINGS', 'USER_ACCESS_DELETE'),
        ('ACCESS_ADMIN_SETTINGS', 'ADMIN_DASHBOARD_VIEW'),
        ('ACCESS_ADMIN_SETTINGS', 'WORKSPACE_SETTINGS_VIEW'), ('ACCESS_ADMIN_SETTINGS', 'WORKSPACE_SETTINGS_UPDATE'), ('ACCESS_ADMIN_SETTINGS', 'WORKSPACE_SETTINGS_CONFIGURE'),
        ('ACCESS_ADMIN_SETTINGS', 'LOAN_PRODUCTS_VIEW'), ('ACCESS_ADMIN_SETTINGS', 'LOAN_PRODUCTS_CREATE'),
        ('ACCESS_ADMIN_SETTINGS', 'LOAN_PRODUCTS_UPDATE'), ('ACCESS_ADMIN_SETTINGS', 'LOAN_PRODUCTS_CONFIGURE'), ('ACCESS_ADMIN_SETTINGS', 'LOAN_PRODUCTS_DELETE'),
        ('ACCESS_ADMIN_SETTINGS', 'APPROVAL_FLOW_VIEW'), ('ACCESS_ADMIN_SETTINGS', 'APPROVAL_FLOW_CONFIGURE'),
        ('ACCESS_ADMIN_SETTINGS', 'SMS_USAGE_VIEW'), ('ACCESS_ADMIN_SETTINGS', 'SMS_USAGE_CONFIGURE'),
        ('ACCESS_ADMIN_SETTINGS', 'NOTIFICATIONS_VIEW'), ('ACCESS_ADMIN_SETTINGS', 'NOTIFICATIONS_UPDATE'),
        ('ACCESS_ADMIN_SETTINGS', 'SUPPORT_VIEW'), ('ACCESS_ADMIN_SETTINGS', 'SUPPORT_CREATE'), ('ACCESS_ADMIN_SETTINGS', 'SUPPORT_UPDATE'),
        ('ACCESS_OUTBOX_MONITOR', 'OUTBOX_VIEW'), ('ACCESS_OUTBOX_MONITOR', 'OUTBOX_UPDATE')
),
role_legacy_map(role_name, legacy_claim) AS (
    VALUES
        ('LOAN_OFFICER', 'REVIEW_LOAN_OFFICER_QUEUE'),
        ('MANAGER', 'REVIEW_MANAGER_QUEUE'),
        ('ACCOUNTANT', 'REVIEW_ACCOUNTANT_QUEUE'),
        ('DISBURSEMENT_OFFICER', 'ACCESS_DISBURSEMENT_QUEUE'),
        ('DISBURSEMENT_OFFICER', 'DISBURSE_LOAN'),
        ('CHAIRPERSON', 'REVIEW_CHAIRPERSON_QUEUE'),
        ('BOARD', 'REVIEW_BOARD_QUEUE'),
        ('CREDIT_COMMITTEE', 'REVIEW_CREDIT_COMMITTEE_QUEUE'),
        ('MINOR_ADMIN', 'ACCESS_ADMIN_SETTINGS'),
        ('MINOR_ADMIN', 'ACCESS_OUTBOX_MONITOR'),
        ('ADMIN', 'ACCESS_ADMIN_SETTINGS'),
        ('ADMIN', 'ACCESS_OUTBOX_MONITOR')
),
role_claims AS (
    SELECT DISTINCT m.id AS member_id, lcm.claim_name
    FROM public.members m
    LEFT JOIN public.member_staff_roles msr ON msr.member_id = m.id
    JOIN role_legacy_map rlm ON rlm.role_name = msr.role_name OR rlm.role_name = m.position
    JOIN legacy_claim_map lcm ON lcm.legacy_claim = rlm.legacy_claim
),
member_claims AS (
    SELECT DISTINCT m.id AS member_id, lcm.claim_name
    FROM public.members m
    JOIN legacy_claim_map lcm ON lcm.legacy_claim IN ('APPLY_LOANS', 'APPROVE_GUARANTOR_REQUESTS')
    WHERE coalesce(m.is_member, m.position = 'MEMBER')
),
platform_admin_claims AS (
    SELECT DISTINCT m.id AS member_id, vc.claim_name
    FROM public.members m
    LEFT JOIN public.member_staff_roles msr ON msr.member_id = m.id
    JOIN valid_claims vc ON vc.claim_name IN (
        'SACCO_REGISTRY_VIEW', 'SACCO_REGISTRY_CREATE', 'SACCO_REGISTRY_UPDATE', 'SACCO_REGISTRY_DELETE',
        'PLATFORM_SETTINGS_VIEW', 'PLATFORM_SETTINGS_UPDATE', 'SMS_USAGE_ADD'
    )
    WHERE m.position = 'ADMIN' OR msr.role_name = 'ADMIN'
),
json_claims AS (
    SELECT DISTINCT us.member_id,
           coalesce(v.claim_name, lcm.claim_name) AS claim_name
    FROM public.user_settings us
    JOIN public.members m ON m.id = us.member_id
    CROSS JOIN LATERAL jsonb_array_elements_text(coalesce(us.notification_prefs -> 'claims', '[]'::jsonb)) stored_claim
    LEFT JOIN valid_claims v ON v.claim_name = stored_claim
    LEFT JOIN legacy_claim_map lcm ON lcm.legacy_claim = stored_claim
    WHERE v.claim_name IS NOT NULL OR lcm.claim_name IS NOT NULL
),
seed_claims AS (
    SELECT * FROM role_claims
    UNION
    SELECT * FROM member_claims
    UNION
    SELECT * FROM platform_admin_claims
    UNION
    SELECT * FROM json_claims
)
INSERT INTO public.member_access_claims (member_id, claim_name)
SELECT member_id, claim_name
FROM seed_claims
ON CONFLICT DO NOTHING;
