-- Backfill explicit default access claims for users that still have no matrix rows.
-- Existing customized users are preserved because members with any claim row are skipped.

WITH missing_claim_members AS (
    SELECT m.id, m.position, m.is_member
    FROM public.members m
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.member_access_claims mac
        WHERE mac.member_id = m.id
    )
),
member_default_claims(claim_name) AS (
    VALUES
        ('MEMBER_SETTINGS_VIEW'), ('MEMBER_SETTINGS_UPDATE'),
        ('PAYMENT_DETAILS_VIEW'), ('PAYMENT_DETAILS_UPDATE'),
        ('MEMBER_LOANS_VIEW'), ('MEMBER_LOANS_CREATE'), ('MEMBER_LOANS_UPDATE'), ('MEMBER_LOANS_ASSIGN'), ('MEMBER_LOANS_DELETE'),
        ('GUARANTOR_REQUESTS_VIEW'), ('GUARANTOR_REQUESTS_UPDATE'), ('GUARANTOR_REQUESTS_APPROVE'), ('GUARANTOR_REQUESTS_REJECT'),
        ('LOAN_DOCUMENTS_VIEW'), ('LOAN_DOCUMENTS_CREATE'), ('LOAN_DOCUMENTS_EXPORT'),
        ('LOAN_REPORTS_VIEW'), ('LOAN_REPORTS_EXPORT'),
        ('NOTIFICATIONS_VIEW'), ('NOTIFICATIONS_UPDATE'),
        ('SUPPORT_VIEW'), ('SUPPORT_CREATE')
),
role_default_claims(role_name, claim_name) AS (
    VALUES
        ('LOAN_OFFICER', 'LOAN_OFFICER_QUEUE_VIEW'),
        ('LOAN_OFFICER', 'LOAN_OFFICER_QUEUE_ASSIGN'),
        ('LOAN_OFFICER', 'LOAN_OFFICER_QUEUE_APPROVE'),
        ('LOAN_OFFICER', 'LOAN_OFFICER_QUEUE_REJECT'),
        ('LOAN_OFFICER', 'LOAN_OFFICER_QUEUE_UPDATE'),
        ('LOAN_OFFICER', 'LOAN_OFFICER_QUEUE_EXPORT'),
        ('LOAN_OFFICER', 'LOAN_DOCUMENTS_VIEW'),
        ('LOAN_OFFICER', 'STAFF_ANALYTICS_VIEW'),
        ('LOAN_OFFICER', 'STAFF_ANALYTICS_EXPORT'),
        ('LOAN_OFFICER', 'LOAN_REPORTS_VIEW'),
        ('LOAN_OFFICER', 'LOAN_REPORTS_EXPORT'),
        ('LOAN_OFFICER', 'NOTIFICATIONS_VIEW'),
        ('LOAN_OFFICER', 'NOTIFICATIONS_UPDATE'),
        ('LOAN_OFFICER', 'SUPPORT_VIEW'),
        ('LOAN_OFFICER', 'SUPPORT_CREATE'),

        ('MANAGER', 'MANAGER_QUEUE_VIEW'),
        ('MANAGER', 'MANAGER_QUEUE_APPROVE'),
        ('MANAGER', 'MANAGER_QUEUE_REJECT'),
        ('MANAGER', 'MANAGER_QUEUE_UPDATE'),
        ('MANAGER', 'MANAGER_QUEUE_EXPORT'),
        ('MANAGER', 'LOAN_DOCUMENTS_VIEW'),
        ('MANAGER', 'STAFF_ANALYTICS_VIEW'),
        ('MANAGER', 'STAFF_ANALYTICS_EXPORT'),
        ('MANAGER', 'LOAN_REPORTS_VIEW'),
        ('MANAGER', 'LOAN_REPORTS_EXPORT'),
        ('MANAGER', 'NOTIFICATIONS_VIEW'),
        ('MANAGER', 'NOTIFICATIONS_UPDATE'),
        ('MANAGER', 'SUPPORT_VIEW'),
        ('MANAGER', 'SUPPORT_CREATE'),

        ('ACCOUNTANT', 'ACCOUNTANT_QUEUE_VIEW'),
        ('ACCOUNTANT', 'ACCOUNTANT_QUEUE_APPROVE'),
        ('ACCOUNTANT', 'ACCOUNTANT_QUEUE_REJECT'),
        ('ACCOUNTANT', 'ACCOUNTANT_QUEUE_UPDATE'),
        ('ACCOUNTANT', 'ACCOUNTANT_QUEUE_EXPORT'),
        ('ACCOUNTANT', 'LOAN_DOCUMENTS_VIEW'),
        ('ACCOUNTANT', 'STAFF_ANALYTICS_VIEW'),
        ('ACCOUNTANT', 'STAFF_ANALYTICS_EXPORT'),
        ('ACCOUNTANT', 'LOAN_REPORTS_VIEW'),
        ('ACCOUNTANT', 'LOAN_REPORTS_EXPORT'),
        ('ACCOUNTANT', 'NOTIFICATIONS_VIEW'),
        ('ACCOUNTANT', 'NOTIFICATIONS_UPDATE'),
        ('ACCOUNTANT', 'SUPPORT_VIEW'),
        ('ACCOUNTANT', 'SUPPORT_CREATE'),

        ('DISBURSEMENT_OFFICER', 'DISBURSEMENT_QUEUE_VIEW'),
        ('DISBURSEMENT_OFFICER', 'DISBURSEMENT_QUEUE_UPDATE'),
        ('DISBURSEMENT_OFFICER', 'DISBURSEMENT_QUEUE_EXPORT'),
        ('DISBURSEMENT_OFFICER', 'DISBURSEMENT_QUEUE_DISBURSE'),
        ('DISBURSEMENT_OFFICER', 'LOAN_DOCUMENTS_VIEW'),
        ('DISBURSEMENT_OFFICER', 'STAFF_ANALYTICS_VIEW'),
        ('DISBURSEMENT_OFFICER', 'LOAN_REPORTS_VIEW'),
        ('DISBURSEMENT_OFFICER', 'LOAN_REPORTS_EXPORT'),
        ('DISBURSEMENT_OFFICER', 'NOTIFICATIONS_VIEW'),
        ('DISBURSEMENT_OFFICER', 'NOTIFICATIONS_UPDATE'),

        ('CHAIRPERSON', 'CHAIRPERSON_QUEUE_VIEW'),
        ('CHAIRPERSON', 'CHAIRPERSON_QUEUE_APPROVE'),
        ('CHAIRPERSON', 'CHAIRPERSON_QUEUE_REJECT'),
        ('CHAIRPERSON', 'CHAIRPERSON_QUEUE_UPDATE'),
        ('CHAIRPERSON', 'CHAIRPERSON_QUEUE_EXPORT'),
        ('CHAIRPERSON', 'LOAN_DOCUMENTS_VIEW'),
        ('CHAIRPERSON', 'STAFF_ANALYTICS_VIEW'),
        ('CHAIRPERSON', 'STAFF_ANALYTICS_EXPORT'),
        ('CHAIRPERSON', 'LOAN_REPORTS_VIEW'),
        ('CHAIRPERSON', 'LOAN_REPORTS_EXPORT'),
        ('CHAIRPERSON', 'NOTIFICATIONS_VIEW'),
        ('CHAIRPERSON', 'NOTIFICATIONS_UPDATE'),
        ('CHAIRPERSON', 'SUPPORT_VIEW'),
        ('CHAIRPERSON', 'SUPPORT_CREATE'),

        ('BOARD', 'BOARD_QUEUE_VIEW'),
        ('BOARD', 'BOARD_QUEUE_APPROVE'),
        ('BOARD', 'BOARD_QUEUE_REJECT'),
        ('BOARD', 'BOARD_QUEUE_UPDATE'),
        ('BOARD', 'BOARD_QUEUE_EXPORT'),
        ('BOARD', 'LOAN_DOCUMENTS_VIEW'),
        ('BOARD', 'STAFF_ANALYTICS_VIEW'),
        ('BOARD', 'STAFF_ANALYTICS_EXPORT'),
        ('BOARD', 'LOAN_REPORTS_VIEW'),
        ('BOARD', 'LOAN_REPORTS_EXPORT'),
        ('BOARD', 'NOTIFICATIONS_VIEW'),
        ('BOARD', 'NOTIFICATIONS_UPDATE'),
        ('BOARD', 'SUPPORT_VIEW'),
        ('BOARD', 'SUPPORT_CREATE'),

        ('CREDIT_COMMITTEE', 'CREDIT_COMMITTEE_QUEUE_VIEW'),
        ('CREDIT_COMMITTEE', 'CREDIT_COMMITTEE_QUEUE_APPROVE'),
        ('CREDIT_COMMITTEE', 'CREDIT_COMMITTEE_QUEUE_REJECT'),
        ('CREDIT_COMMITTEE', 'CREDIT_COMMITTEE_QUEUE_UPDATE'),
        ('CREDIT_COMMITTEE', 'CREDIT_COMMITTEE_QUEUE_EXPORT'),
        ('CREDIT_COMMITTEE', 'LOAN_DOCUMENTS_VIEW'),
        ('CREDIT_COMMITTEE', 'STAFF_ANALYTICS_VIEW'),
        ('CREDIT_COMMITTEE', 'STAFF_ANALYTICS_EXPORT'),
        ('CREDIT_COMMITTEE', 'LOAN_REPORTS_VIEW'),
        ('CREDIT_COMMITTEE', 'LOAN_REPORTS_EXPORT'),
        ('CREDIT_COMMITTEE', 'NOTIFICATIONS_VIEW'),
        ('CREDIT_COMMITTEE', 'NOTIFICATIONS_UPDATE'),
        ('CREDIT_COMMITTEE', 'SUPPORT_VIEW'),
        ('CREDIT_COMMITTEE', 'SUPPORT_CREATE'),

        ('MINOR_ADMIN', 'ACCESS_MATRIX_VIEW'),
        ('MINOR_ADMIN', 'ACCESS_MATRIX_UPDATE'),
        ('MINOR_ADMIN', 'USER_ACCESS_VIEW'),
        ('MINOR_ADMIN', 'USER_ACCESS_CREATE'),
        ('MINOR_ADMIN', 'USER_ACCESS_UPDATE'),
        ('MINOR_ADMIN', 'USER_ACCESS_DELETE'),
        ('MINOR_ADMIN', 'ADMIN_DASHBOARD_VIEW'),
        ('MINOR_ADMIN', 'WORKSPACE_SETTINGS_VIEW'),
        ('MINOR_ADMIN', 'WORKSPACE_SETTINGS_UPDATE'),
        ('MINOR_ADMIN', 'WORKSPACE_SETTINGS_CONFIGURE'),
        ('MINOR_ADMIN', 'LOAN_PRODUCTS_VIEW'),
        ('MINOR_ADMIN', 'LOAN_PRODUCTS_CREATE'),
        ('MINOR_ADMIN', 'LOAN_PRODUCTS_UPDATE'),
        ('MINOR_ADMIN', 'LOAN_PRODUCTS_CONFIGURE'),
        ('MINOR_ADMIN', 'LOAN_PRODUCTS_DELETE'),
        ('MINOR_ADMIN', 'APPROVAL_FLOW_VIEW'),
        ('MINOR_ADMIN', 'APPROVAL_FLOW_CONFIGURE'),
        ('MINOR_ADMIN', 'SMS_USAGE_VIEW'),
        ('MINOR_ADMIN', 'SMS_USAGE_CONFIGURE'),
        ('MINOR_ADMIN', 'OUTBOX_VIEW'),
        ('MINOR_ADMIN', 'OUTBOX_UPDATE'),
        ('MINOR_ADMIN', 'NOTIFICATIONS_VIEW'),
        ('MINOR_ADMIN', 'NOTIFICATIONS_UPDATE'),
        ('MINOR_ADMIN', 'SUPPORT_VIEW'),
        ('MINOR_ADMIN', 'SUPPORT_CREATE'),
        ('MINOR_ADMIN', 'SUPPORT_UPDATE'),

        ('ADMIN', 'ACCESS_MATRIX_VIEW'),
        ('ADMIN', 'ACCESS_MATRIX_UPDATE'),
        ('ADMIN', 'USER_ACCESS_VIEW'),
        ('ADMIN', 'USER_ACCESS_CREATE'),
        ('ADMIN', 'USER_ACCESS_UPDATE'),
        ('ADMIN', 'USER_ACCESS_DELETE'),
        ('ADMIN', 'ADMIN_DASHBOARD_VIEW'),
        ('ADMIN', 'SACCO_REGISTRY_VIEW'),
        ('ADMIN', 'SACCO_REGISTRY_CREATE'),
        ('ADMIN', 'SACCO_REGISTRY_UPDATE'),
        ('ADMIN', 'SACCO_REGISTRY_DELETE'),
        ('ADMIN', 'PLATFORM_SETTINGS_VIEW'),
        ('ADMIN', 'PLATFORM_SETTINGS_UPDATE'),
        ('ADMIN', 'WORKSPACE_SETTINGS_VIEW'),
        ('ADMIN', 'WORKSPACE_SETTINGS_UPDATE'),
        ('ADMIN', 'WORKSPACE_SETTINGS_CONFIGURE'),
        ('ADMIN', 'LOAN_PRODUCTS_VIEW'),
        ('ADMIN', 'LOAN_PRODUCTS_CREATE'),
        ('ADMIN', 'LOAN_PRODUCTS_UPDATE'),
        ('ADMIN', 'LOAN_PRODUCTS_CONFIGURE'),
        ('ADMIN', 'LOAN_PRODUCTS_DELETE'),
        ('ADMIN', 'APPROVAL_FLOW_VIEW'),
        ('ADMIN', 'APPROVAL_FLOW_CONFIGURE'),
        ('ADMIN', 'SMS_USAGE_VIEW'),
        ('ADMIN', 'SMS_USAGE_ADD'),
        ('ADMIN', 'SMS_USAGE_CONFIGURE'),
        ('ADMIN', 'OUTBOX_VIEW'),
        ('ADMIN', 'OUTBOX_UPDATE'),
        ('ADMIN', 'NOTIFICATIONS_VIEW'),
        ('ADMIN', 'NOTIFICATIONS_UPDATE'),
        ('ADMIN', 'SUPPORT_VIEW'),
        ('ADMIN', 'SUPPORT_CREATE'),
        ('ADMIN', 'SUPPORT_UPDATE')
),
member_claims AS (
    SELECT m.id AS member_id, mdc.claim_name
    FROM missing_claim_members m
    CROSS JOIN member_default_claims mdc
    WHERE coalesce(m.is_member, m.position = 'MEMBER')
),
staff_claims AS (
    SELECT DISTINCT m.id AS member_id, rdc.claim_name
    FROM missing_claim_members m
    LEFT JOIN public.member_staff_roles msr ON msr.member_id = m.id
    JOIN role_default_claims rdc ON rdc.role_name = msr.role_name OR rdc.role_name = m.position
),
seed_claims AS (
    SELECT * FROM member_claims
    UNION
    SELECT * FROM staff_claims
)
INSERT INTO public.member_access_claims (member_id, claim_name)
SELECT member_id, claim_name
FROM seed_claims
ON CONFLICT DO NOTHING;
