DELETE FROM public.member_access_claims
WHERE claim_name IN (
    'LOAN_OFFICER_QUEUE_UPDATE',
    'MANAGER_QUEUE_ASSIGN',
    'MANAGER_QUEUE_UPDATE',
    'ACCOUNTANT_QUEUE_ASSIGN',
    'ACCOUNTANT_QUEUE_UPDATE',
    'BOARD_QUEUE_ASSIGN',
    'BOARD_QUEUE_UPDATE',
    'CHAIRPERSON_QUEUE_ASSIGN',
    'CHAIRPERSON_QUEUE_UPDATE',
    'CREDIT_COMMITTEE_QUEUE_ASSIGN',
    'CREDIT_COMMITTEE_QUEUE_UPDATE',
    'DISBURSEMENT_QUEUE_UPDATE'
);
