<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/report-runs.css' />" />
<main class="report-runs-workspace"><div class="erp-page-header"><h1 class="erp-page-title"><spring:message code="accounting.release.title" /></h1></div>
<p><spring:message code="accounting.release.notice" /></p>
<c:if test="${not empty releaseError}"><p role="alert"><spring:message code="${releaseError}" /></p></c:if><c:if test="${not empty releaseSuccess}"><p role="status"><spring:message code="${releaseSuccess}" /></p></c:if>
<c:choose><c:when test="${not empty release}">
<section class="report-run-detail"><dl class="report-run-facts"><div><dt><spring:message code="report.run.state" /></dt><dd><spring:message code="accounting.release.state.${release.getState()}" /></dd></div><div><dt><spring:message code="accounting.release.policy" /></dt><dd><c:out value="${release.policyVersion}" /></dd></div><div><dt><spring:message code="report.run.requested" /></dt><dd><c:out value="${release.requestedAt}" /></dd></div><div><dt><spring:message code="accounting.release.checksum" /></dt><dd class="report-run-checksum"><c:out value="${release.checksum}" /></dd></div></dl><p><spring:message code="report.run.evidence" />: <c:out value="${release.evidence}" /></p></section>
<section class="report-run-detail">
<h2><spring:message code="accounting.release.dependencies" /></h2>
<dl class="report-run-facts">
<div><dt><spring:message code="report.scope" /></dt><dd><c:out value="${release.institution}" /> / <c:out value="${release.branch}" /></dd></div>
<div><dt><spring:message code="accounting.release.policy" /></dt><dd><c:out value="${dependencies.policy.version}" /> / <c:out value="${dependencies.policy.effectiveFrom}" /><br /><c:out value="${dependencies.policy.evidenceReference}" /><br /><c:out value="${dependencies.policy.approvalEvidence}" /></dd></div>
<div><dt><spring:message code="accounting.release.opening" /></dt><dd><c:out value="${dependencies.opening.through}" /><br /><c:out value="${dependencies.opening.sourceEvidence}" /><br /><c:out value="${dependencies.opening.reviewEvidence}" /><br /><span class="report-run-checksum"><c:out value="${dependencies.opening.payloadChecksum}" /></span></dd></div>
<div><dt><spring:message code="accounting.release.close" /></dt><dd><c:out value="${dependencies.closeVersion}" /><br /><span class="report-run-checksum"><c:out value="${dependencies.closeChecksum}" /></span><sec:authorize access="@access.has(principal,'ACCOUNTING_CLOSING_VIEW')"><br /><a href="<c:url value='/finance/closing/reviews/${dependencies.closeId}' />"><spring:message code="common.view" /></a></sec:authorize></dd></div>
<div><dt><spring:message code="accounting.release.mapping" /></dt><dd><c:out value="${dependencies.mapping.version}" /><br /><c:out value="${dependencies.mapping.evidence}" /><br /><span class="report-run-checksum"><c:out value="${dependencies.mapping.definitionChecksum}" /></span></dd></div>
<div><dt><spring:message code="accounting.release.statement" /></dt><dd><c:out value="${dependencies.statementOutputReviewEvidence}" /><br /><span class="report-run-checksum"><c:out value="${dependencies.statementSourceChecksum}" /></span><sec:authorize access="@access.has(principal,'STATEMENT_VIEW')"><br /><a href="<c:url value='/finance/statement-outputs/${release.statementOutput}' />"><spring:message code="common.view" /></a></sec:authorize></dd></div>
<c:forEach items="firstSample,secondSample" var="sampleKey"><div><dt><spring:message code="accounting.release.${sampleKey}" /></dt><dd><c:out value="${dependencies[sampleKey].templateVersion}" /><br /><c:out value="${dependencies[sampleKey].reviewEvidence}" /><br /><span class="report-run-checksum"><c:out value="${dependencies[sampleKey].layoutChecksum}" /></span><sec:authorize access="@access.has(principal,'REPORT_RUN')"><br /><a href="<c:url value='/reports/runs/${dependencies[sampleKey].run}' />"><spring:message code="common.view" /></a></sec:authorize></dd></div></c:forEach>
</dl>
<h3><spring:message code="statement.export.disclosures" /></h3><c:forEach items="${releaseDisclosures}" var="disclosure"><p><c:out value="${disclosure}" /></p></c:forEach>
<c:if test="${not empty dependencies.reviewedDifferences}"><h3><spring:message code="statement.export.reviewedDifference" /></h3><c:forEach items="${dependencies.reviewedDifferences}" var="difference"><p><c:if test="${not empty difference.kind}"><spring:message code="reconciliation.kind.${difference.kind}" />: </c:if><c:out value="${difference.difference}" /> <c:out value="${difference.evidence}" /><c:if test="${not empty difference.review_evidence}"><br /><c:out value="${difference.review_evidence}" /></c:if></p></c:forEach></c:if>
</section>
<section class="erp-table-wrap"><div class="erp-table-scroll"><table class="erp-table"><thead><tr><th><spring:message code="accounting.release.stage" /></th><th><spring:message code="report.run.state" /></th><th><spring:message code="report.run.evidence" /></th><th><spring:message code="accounting.release.decided" /></th></tr></thead><tbody><c:forEach items="${release.decisions}" var="decision"><tr><td><spring:message code="accounting.release.stage.${decision.stage}" /></td><td><c:choose><c:when test="${decision.approved}"><spring:message code="accounting.release.state.APPROVED" /></c:when><c:otherwise><spring:message code="accounting.release.state.REJECTED" /></c:otherwise></c:choose></td><td><c:out value="${decision.evidence}" /></td><td><c:out value="${decision.at}" /></td></tr></c:forEach><c:if test="${empty release.decisions}"><tr><td colspan="4"><spring:message code="accounting.release.pending" /></td></tr></c:if></tbody></table></div></section>
<c:if test="${release.getState() == 'PENDING' && independentReleaseActor}"><c:set var="stage" value="${release.decisions.size() == 0 ? 'ACCOUNTANT' : release.decisions.size() == 1 ? 'COMPLIANCE' : 'STAFF'}" /><c:set var="reviewClaim" value="${stage == 'ACCOUNTANT' ? 'ACCOUNTING_RELEASE_APPROVE' : stage == 'COMPLIANCE' ? 'ACCOUNTING_COMPLIANCE_RELEASE_APPROVE' : 'ACCOUNTING_RELEASE_ACCEPT'}" /><sec:authorize access="@access.has(principal,'${reviewClaim}')"><form class="report-run-approval" method="post" action="<c:url value='/finance/accounting-release/${release.id}/decide' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="stage" value="${stage}" /><h2><spring:message code="accounting.release.stage.${stage}" /></h2><label><spring:message code="report.run.evidence" /><input class="aws-control" name="evidence" maxlength="1000" required /></label><div class="report-run-actions"><button class="app-btn btn-primary" name="approved" value="true"><spring:message code="accounting.release.approve" /></button><button class="app-btn btn-neutral" name="approved" value="false"><spring:message code="accounting.release.reject" /></button></div></form></sec:authorize></c:if>
<sec:authorize access="@access.has(principal,'ACCOUNTING_RELEASE_APPROVE')"><c:if test="${release.getState() == 'APPROVED' || release.getState() == 'PENDING'}"><form class="report-run-approval" method="post" action="<c:url value='/finance/accounting-release/${release.id}/withdraw' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="report.run.reason" /><input class="aws-control" name="reason" maxlength="1000" required /></label><button class="app-btn btn-neutral"><spring:message code="accounting.release.withdraw" /></button></form></c:if></sec:authorize>
</c:when><c:otherwise>
<section class="erp-table-wrap"><div class="erp-table-scroll" data-view-position-key="accounting-releases"><table class="erp-table"><thead><tr><th><spring:message code="accounting.release.policy" /></th><th><spring:message code="report.run.state" /></th><th><spring:message code="report.run.requested" /></th><th><spring:message code="common.actions" /></th></tr></thead><tbody><c:forEach items="${releases}" var="item"><tr><td><c:out value="${item.policyVersion}" /></td><td><spring:message code="accounting.release.state.${item.getState()}" /></td><td><c:out value="${item.requestedAt}" /></td><td><a class="app-btn btn-neutral" href="<c:url value='/finance/accounting-release/${item.id}' />"><spring:message code="common.view" /></a></td></tr></c:forEach><c:if test="${empty releases}"><tr><td colspan="4"><spring:message code="report.run.empty" /></td></tr></c:if></tbody></table></div><div class="report-run-actions"><c:if test="${page > 0}"><a class="app-btn btn-neutral" href="<c:url value='/finance/accounting-release?page=${page-1}' />"><spring:message code="common.previous" /></a></c:if><c:if test="${releases.size() == 25}"><a class="app-btn btn-neutral" href="<c:url value='/finance/accounting-release?page=${page+1}' />"><spring:message code="common.next" /></a></c:if></div></section>
<sec:authorize access="@access.has(principal,'ACCOUNTING_RELEASE_REQUEST')"><form class="report-run-request" method="post" action="<c:url value='/finance/accounting-release' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="requestKey" value="${requestKey}" /><h2><spring:message code="accounting.release.propose" /></h2><div class="report-run-grid"><label><spring:message code="accounting.release.statement" /><select class="aws-control" name="statementOutput" required><c:forEach items="${outputs}" var="item"><c:if test="${not empty item.reviewer}"><option value="${item.id}" ${item.id == selectedOutput ? 'selected' : ''}><c:out value="${pageContext.response.locale.language == 'sw' ? item.titleSw : item.titleEn}" /> / <c:out value="${item.through}" /></option></c:if></c:forEach></select></label><c:forEach items="firstSample,secondSample" var="sampleName"><label><spring:message code="accounting.release.${sampleName}" /><select class="aws-control" name="${sampleName}" required><c:forEach items="${samples}" var="item"><option value="${item.id}" ${(sampleName == 'firstSample' && item.id == selectedFirst) || (sampleName == 'secondSample' && item.id == selectedSecond) ? 'selected' : ''}><c:out value="${item.definition.title}" /> / <c:out value="${item.through}" /></option></c:forEach></select></label></c:forEach><label><spring:message code="report.run.evidence" /><input class="aws-control" name="evidence" maxlength="1000" value="<c:out value='${proposalEvidence}' />" required /></label></div><button class="app-btn btn-primary"><spring:message code="accounting.release.propose" /></button></form></sec:authorize>
</c:otherwise></c:choose></main>
<%@ include file="../fragments/footer.jspf" %>
