<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/statement-designer.css' />" />
<div class="statement-designer"><div class="erp-page-header" data-aws-page-header><h1 class="erp-page-title"><spring:message code="statement.regulatory" /></h1></div><p><spring:message code="statement.regulatoryBoundary" /></p><c:if test="${not empty statementSuccess}"><p role="status"><spring:message code="${statementSuccess}" /></p></c:if>
<c:if test="${empty formats}"><p role="status"><spring:message code="statement.noOfficial" /></p></c:if>
<sec:authorize access="hasAuthority('REGULATORY_SUBMISSION_CREATE')"><c:if test="${not empty formats}"><form class="statement-panel" method="post" action="<c:url value='/reports/statements/regulatory' />" enctype="multipart/form-data"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><div class="statement-fields"><label><spring:message code="statement.officialFormat" /><select name="format" required><c:forEach items="${formats}" var="format"><option value="${format.id}"><c:out value="${format.authority}" /> · <c:out value="${format.key}" /> · <c:out value="${format.version}" /></option></c:forEach></select></label><label><spring:message code="statement.resultReference" /><input name="result" value="${selectedResult.id}" required /></label><label><spring:message code="statement.file" /><input type="file" name="file" accept=".csv,.xlsx,.pdf" required /></label><label><spring:message code="statement.corrects" /><input name="corrects" /></label><label><spring:message code="statement.validationEvidence" /><input name="evidence" maxlength="1000" required /></label><button class="app-btn btn-primary"><spring:message code="statement.prepareSubmission" /></button></div></form></c:if></sec:authorize>
<div class="erp-table-wrap" data-aws-table-region><div class="erp-table-scroll" data-view-position-key="regulatory-statement-submissions"><table class="erp-table"><thead><tr><th><spring:message code="statement.period" /></th><th><spring:message code="statement.deadline" /></th><th><spring:message code="statement.file" /></th><th><spring:message code="statement.state" /></th><th><spring:message code="statement.actions" /></th></tr></thead><tbody><c:forEach items="${submissions}" var="submission"><tr><td><c:out value="${submission.from}" /> — <c:out value="${submission.through}" /></td><td><c:out value="${submission.deadline}" /></td><td><c:out value="${submission.file}" /><sec:authorize access="hasAuthority('REGULATORY_SUBMISSION_VIEW')"><a href="<c:url value='/reports/statements/regulatory/${submission.id}/file' />"><spring:message code="statement.downloadSubmission" /></a></sec:authorize></td><td><c:choose><c:when test="${not empty submission.checker}"><spring:message code="statement.readyForSubmission" /></c:when><c:otherwise><spring:message code="statement.state.DRAFT" /></c:otherwise></c:choose></td><td><sec:authorize access="hasAuthority('REGULATORY_SUBMISSION_APPROVE')"><c:if test="${empty submission.checker}"><form method="post" action="<c:url value='/reports/statements/regulatory/${submission.id}/review' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="statement.reviewEvidence" /><input name="evidence" maxlength="1000" required /></label><button class="app-btn btn-neutral"><spring:message code="statement.reviewSubmission" /></button></form></c:if></sec:authorize></td></tr></c:forEach><c:if test="${empty submissions}"><tr><td colspan="5"><spring:message code="statement.empty" /></td></tr></c:if></tbody></table></div><div class="statement-actions"><c:if test="${page gt 0}"><a class="app-btn btn-neutral" href="?page=${page-1}"><spring:message code="statement.previous" /></a></c:if><c:if test="${hasNext}"><a class="app-btn btn-neutral" href="?page=${page+1}"><spring:message code="statement.next" /></a></c:if></div></div></div><%@ include file="../fragments/footer.jspf" %>
