<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/report-runs.css' />" />
<main class="report-runs-workspace">
<div class="erp-page-header" data-aws-page-header><h1 class="erp-page-title"><spring:message code="report.run.title" /></h1></div>
<c:if test="${not empty runSuccess}"><p role="status"><spring:message code="${runSuccess}" /></p></c:if>
<c:if test="${not empty runError}"><p role="alert"><spring:message code="${runError}" /></p></c:if>
<p><spring:message code="report.run.coverageNotice" /></p>
<c:choose><c:when test="${not empty run}">
<section class="report-run-detail"><h2><c:out value="${run.definition.title}" /></h2>
<dl class="report-run-facts"><div><dt><spring:message code="report.run.state" /></dt><dd><spring:message code="report.run.state.${run.status}" /></dd></div><div><dt><spring:message code="report.period" /></dt><dd><c:out value="${run.from}" /> / <c:out value="${run.through}" /></dd></div><div><dt><spring:message code="report.cutoff" /></dt><dd><c:out value="${run.cutoff}" /></dd></div><div><dt><spring:message code="report.rows" /></dt><dd><c:choose><c:when test="${run.status == 'READY' || run.status == 'APPROVED'}"><c:out value="${run.rows}" /></c:when><c:otherwise>—</c:otherwise></c:choose></dd></div><div><dt><spring:message code="report.untracked" /></dt><dd><c:choose><c:when test="${run.status == 'READY' || run.status == 'APPROVED'}"><c:out value="${run.untracked}" /></c:when><c:otherwise>—</c:otherwise></c:choose></dd></div><div><dt><spring:message code="report.run.generated" /></dt><dd><c:out value="${run.generatedAt}" /></dd></div></dl>
<c:if test="${not empty run.failure}"><p role="alert"><spring:message code="${run.failure}" /></p></c:if>
<c:if test="${not empty run.approvalEvidence}"><p><spring:message code="report.run.evidence" />: <c:out value="${run.approvalEvidence}" /></p></c:if>
<div class="report-run-actions">
<c:if test="${run.status == 'QUEUED' || run.status == 'RUNNING'}"><form method="post" action="<c:url value='/reports/runs/${run.id}/cancel' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><button class="app-btn btn-neutral"><spring:message code="report.run.cancel" /></button></form></c:if>
<c:if test="${run.status == 'FAILED' && run.attempts < 3 && run.requester == runActor}"><form method="post" action="<c:url value='/reports/runs/${run.id}/retry' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><button class="app-btn btn-neutral"><spring:message code="report.run.retry" /></button></form></c:if>
<sec:authorize access="@access.has(principal,'REPORT_EXPORT')"><c:forEach items="${artifacts}" var="artifact"><a class="app-btn btn-neutral" href="<c:url value='/reports/runs/${run.id}/artifacts/${artifact.id}' />"><spring:message code="report.run.download" /> <c:out value="${artifact.format}" /></a></c:forEach></sec:authorize>
</div>
<sec:authorize access="@access.has(principal,'REPORT_RUN_APPROVE')"><c:if test="${run.status == 'READY' && run.requester != runActor}"><form class="report-run-approval" method="post" action="<c:url value='/reports/runs/${run.id}/approve' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="report.run.evidence" /><input class="aws-control" name="evidence" maxlength="200" required /></label><button class="app-btn btn-primary"><spring:message code="report.run.approve" /></button></form></c:if></sec:authorize>
</section>
<c:if test="${not empty frozen}"><section class="erp-table-wrap" data-aws-table-region><div class="erp-table-scroll" data-view-position-key="report-frozen-rows"><table class="erp-table"><thead><tr><c:forEach items="${frozen.getVisibleColumns()}" var="column"><th><c:out value="${headings[column.field]}" /></th></c:forEach></tr></thead><tbody><c:forEach items="${frozen.rows}" var="row"><tr><c:forEach items="${frozen.getVisibleColumns()}" var="column"><td><c:choose><c:when test="${row[column.field.name()] == null}">—</c:when><c:otherwise><c:out value="${row[column.field.name()]}" /></c:otherwise></c:choose></td></c:forEach></tr></c:forEach><c:if test="${empty frozen.rows}"><tr><td colspan="9"><spring:message code="report.run.empty" /></td></tr></c:if></tbody></table></div><div class="report-run-actions"><c:if test="${rowPage > 0}"><a class="app-btn btn-neutral" href="<c:url value='/reports/runs/${run.id}?page=${rowPage-1}' />"><spring:message code="common.previous" /></a></c:if><c:if test="${(rowPage+1)*25 < run.rows}"><a class="app-btn btn-neutral" href="<c:url value='/reports/runs/${run.id}?page=${rowPage+1}' />"><spring:message code="common.next" /></a></c:if></div><dl class="report-run-facts"><c:forEach items="${frozen.totals}" var="total"><div><dt><c:out value="${headings[total.key]}" /></dt><dd><c:out value="${total.value}" /> TZS</dd></div></c:forEach></dl></section></c:if>
</c:when><c:otherwise>
<section class="erp-table-wrap" data-aws-table-region><div class="erp-table-scroll" data-view-position-key="report-runs"><table class="erp-table"><thead><tr><th><spring:message code="report.run.report" /></th><th><spring:message code="report.period" /></th><th><spring:message code="report.run.state" /></th><th><spring:message code="report.run.requested" /></th><th><spring:message code="common.actions" /></th></tr></thead><tbody><c:forEach items="${runs}" var="item"><tr><td><c:out value="${item.definition.title}" /></td><td><c:out value="${item.from}" /> / <c:out value="${item.through}" /></td><td><spring:message code="report.run.state.${item.status}" /></td><td><c:out value="${item.requestedAt}" /></td><td><a class="app-btn btn-neutral" href="<c:url value='/reports/runs/${item.id}' />"><spring:message code="common.view" /></a></td></tr></c:forEach><c:if test="${empty runs}"><tr><td colspan="5"><spring:message code="report.run.empty" /></td></tr></c:if></tbody></table></div><div class="report-run-actions"><c:if test="${listPage > 0}"><a class="app-btn btn-neutral" href="<c:url value='/reports/runs?page=${listPage-1}' />"><spring:message code="common.previous" /></a></c:if><c:if test="${runs.size() == 25}"><a class="app-btn btn-neutral" href="<c:url value='/reports/runs?page=${listPage+1}' />"><spring:message code="common.next" /></a></c:if></div></section>
<sec:authorize access="@access.has(principal,'REPORT_RUN') and @access.has(principal,'REPORT_EXPORT')"><form class="report-run-request" method="post" action="<c:url value='/reports/runs' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="requestKey" value="${requestKey}" /><h2><spring:message code="report.run.request" /></h2><div class="report-run-grid"><label><spring:message code="report.run.report" /><select class="aws-control" name="templateVersion" required><c:forEach items="${templates}" var="template"><c:if test="${template.state == 'PUBLISHED'}"><option value="${template.id}" ${selectedTemplate == template.id ? 'selected' : ''}><c:out value="${template.definition.title}" /> / <c:out value="${template.version}" /></option></c:if></c:forEach></select></label><label><spring:message code="report.run.from" /><input class="aws-control" type="date" name="from" value="${from}" required /></label><label><spring:message code="report.run.through" /><input class="aws-control" type="date" name="through" value="${through}" required /></label><label><spring:message code="report.cutoff" /><input class="aws-control" name="recordedCutoff" value="${cutoff}" required /></label><label><spring:message code="report.run.formats" /><select class="aws-control" name="formats" required><option value="PDF">PDF</option></select></label><label><spring:message code="report.run.restates" /><select class="aws-control" name="restates"><option value="">—</option><c:forEach items="${acceptedRuns}" var="accepted"><option value="${accepted.id}" ${restates == accepted.id ? 'selected' : ''}><c:out value="${accepted.definition.title}" /> / <c:out value="${accepted.through}" /></option></c:forEach></select></label><label><spring:message code="report.run.reason" /><input class="aws-control" name="reason" maxlength="200" value="<c:out value='${reason}' />" /></label></div><button class="app-btn btn-primary"><spring:message code="report.run.queue" /></button></form></sec:authorize>
</c:otherwise></c:choose>
</main>
<%@ include file="../fragments/footer.jspf" %>
