<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/statement-designer.css' />" />
<div class="statement-designer">
 <div class="erp-page-header"><h1 class="erp-page-title"><spring:message code="statement.title" /></h1></div><p><spring:message code="statement.boundary" /></p>
 <c:if test="${not empty statementError}"><p class="statement-error" role="alert"><spring:message code="${statementError}" /></p></c:if><c:if test="${not empty statementSuccess}"><p role="status"><spring:message code="${statementSuccess}" /></p></c:if>
 <c:if test="${emptyCatalog}"><p role="status"><spring:message code="statement.noAccounts" /></p></c:if>
 <textarea id="statement-seed" hidden><c:out value="${definitionJson}" /></textarea><textarea id="statement-catalog" hidden><c:out value="${catalogJson}" /></textarea>
 <div id="statement-words" hidden><c:forEach items="${['labelEn','labelSw','kind','section','accounts','sign','normal','reverse','lines','noteEn','noteSw','visible','collapsed','memo','exceptionEvidence','up','down','remove','account','treatmentEn','treatmentSw','evidence']}" var="key"><span data-word="${key}"><spring:message code="statement.${key}" /></span></c:forEach><c:forEach items="${['HEADING','ACCOUNT_GROUP','SUBTOTAL','RATIO','NOTE']}" var="key"><span data-word="kind_${key}"><spring:message code="statement.kind.${key}" /></span></c:forEach><c:forEach items="${['ASSETS','LIABILITIES','EQUITY','INCOME','EXPENSES','OPERATING','INVESTING','FINANCING','NOTES']}" var="key"><span data-word="section_${key}"><spring:message code="statement.section.${key}" /></span></c:forEach><c:forEach items="${['SUM','DIFFERENCE','RATIO']}" var="key"><span data-word="op_${key}"><spring:message code="statement.operation.${key}" /></span></c:forEach></div>
 <sec:authorize access="hasAuthority('STATEMENT_DESIGN')">
 <form id="statement-form" method="post" action="<c:url value='/reports/statements/versions' />" class="statement-panel"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="definition" id="statement-definition" />
 <c:if test="${not empty selected}"><input type="hidden" name="template" value="${selected.template}" /></c:if><c:if test="${empty selected and not empty draftTemplate}"><input type="hidden" name="template" value="${draftTemplate}" /></c:if>
 <div class="statement-fields"><label for="statement-title-en"><spring:message code="statement.titleEn" /><input id="statement-title-en" maxlength="100" required /></label><label for="statement-title-sw"><spring:message code="statement.titleSw" /><input id="statement-title-sw" maxlength="100" required /></label><label for="statement-kind"><spring:message code="statement.type" /><select id="statement-kind"><c:forEach items="${['BALANCE_SHEET','PROFIT_AND_LOSS','CASH_FLOW','CHANGES_IN_EQUITY','NOTES']}" var="key"><option value="${key}"><spring:message code="statement.type.${key}" /></option></c:forEach></select></label></div>
 <label><input id="statement-comparison" type="checkbox" /><spring:message code="statement.comparison" /></label>
 <div id="statement-rows"></div><div class="statement-actions"><button class="app-btn btn-neutral" id="statement-add-row" type="button"><spring:message code="statement.addRow" /></button></div>
 <h2><spring:message code="statement.exclusions" /></h2><p><spring:message code="statement.exclusionBoundary" /></p><div id="statement-exclusions"></div><button type="button" class="app-btn btn-neutral" id="statement-add-exclusion"><spring:message code="statement.addExclusion" /></button>
 <div class="statement-fields"><label for="statement-evidence"><spring:message code="statement.evidence" /><input name="evidence" id="statement-evidence" maxlength="1000" value="<c:out value='${draftEvidence}' />" required /></label></div><div class="statement-actions"><button class="app-btn btn-primary" type="submit"><spring:message code="statement.saveVersion" /></button></div></form>
 </sec:authorize>
 <c:if test="${not empty selected}"><section class="statement-panel"><h2><c:out value="${pageContext.response.locale.language eq 'sw' ? selected.definition.titleSw : selected.definition.titleEn}" /> · <spring:message code="statement.version" /> <c:out value="${selected.version}" /></h2><p><spring:message code="statement.state.${selected.state}" /></p>
 <sec:authorize access="hasAuthority('STATEMENT_VIEW')"><form method="post" action="<c:url value='/reports/statements/versions/${selected.id}/preview' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><div class="statement-fields"><label><spring:message code="statement.from" /><input type="date" name="from" max="${today}" required /></label><label><spring:message code="statement.through" /><input type="date" name="through" max="${today}" required /></label><c:if test="${selected.definition.comparison}"><label><spring:message code="statement.comparisonFrom" /><input type="date" name="comparisonFrom" max="${today}" required /></label><label><spring:message code="statement.comparisonThrough" /><input type="date" name="comparisonThrough" max="${today}" required /></label></c:if><button class="app-btn btn-neutral"><spring:message code="statement.preview" /></button></div></form></sec:authorize>
 <sec:authorize access="hasAuthority('STATEMENT_APPROVE')"><c:if test="${selected.state eq 'DRAFT'}"><form method="post" action="<c:url value='/reports/statements/versions/${selected.id}/approve' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><div class="statement-fields"><label><spring:message code="statement.reviewEvidence" /><input name="evidence" maxlength="1000" required /></label><button class="app-btn btn-primary"><spring:message code="statement.approve" /></button></div></form></c:if><c:if test="${selected.state eq 'APPROVED'}"><form method="post" action="<c:url value='/reports/statements/versions/${selected.id}/retire' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><button class="app-btn btn-neutral"><spring:message code="statement.retire" /></button></form></c:if></sec:authorize>
 <sec:authorize access="hasAuthority('STATEMENT_FINALIZE')"><c:if test="${selected.state eq 'APPROVED'}"><a class="app-btn btn-neutral" href="<c:url value='/reports/statements/versions/${selected.id}/closing' />"><spring:message code="statement.selectClose" /></a></c:if></sec:authorize>
 </section></c:if>
 <div class="erp-table-wrap"><div class="erp-table-scroll" data-view-position-key="financial-statement-versions"><table class="erp-table"><thead><tr><th><spring:message code="statement.type" /></th><th><spring:message code="statement.documentTitle" /></th><th><spring:message code="statement.version" /></th><th><spring:message code="statement.state" /></th><th><spring:message code="statement.actions" /></th></tr></thead><tbody><c:forEach items="${versions}" var="v"><tr><td><spring:message code="statement.type.${v.definition.kind}" /></td><td><c:out value="${pageContext.response.locale.language eq 'sw' ? v.definition.titleSw : v.definition.titleEn}" /></td><td><c:out value="${v.version}" /></td><td><spring:message code="statement.state.${v.state}" /></td><td><a href="<c:url value='/reports/statements?version=${v.id}&page=${page}' />"><spring:message code="statement.openVersion" /></a></td></tr></c:forEach><c:if test="${empty versions}"><tr><td colspan="5"><spring:message code="statement.empty" /></td></tr></c:if></tbody></table></div><div class="statement-actions"><c:if test="${page gt 0}"><a class="app-btn btn-neutral" href="<c:url value='/reports/statements?page=${page-1}' />"><spring:message code="statement.previous" /></a></c:if><c:if test="${hasNext}"><a class="app-btn btn-neutral" href="<c:url value='/reports/statements?page=${page+1}' />"><spring:message code="statement.next" /></a></c:if></div></div>
</div><script src="<c:url value='/js/statement-designer.js' />" defer></script><%@ include file="../fragments/footer.jspf" %>
