<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/report-runs.css' />" />
<main class="report-runs-workspace">
<div class="erp-page-header" data-aws-page-header><h1 class="erp-page-title"><spring:message code="statement.export.title" /></h1></div>
<c:if test="${not empty outputError}"><p role="alert"><spring:message code="${outputError}" /></p></c:if>
<c:if test="${not empty outputSuccess}"><p role="status"><spring:message code="${outputSuccess}" /></p></c:if>
<c:choose><c:when test="${not empty output}">
<section class="report-run-detail"><h2><c:choose><c:when test="${output.layout.language == 'sw'}"><c:out value="${output.result.definition.titleSw}" /></c:when><c:otherwise><c:out value="${output.result.definition.titleEn}" /></c:otherwise></c:choose></h2>
<dl class="report-run-facts"><div><dt><spring:message code="report.period" /></dt><dd><c:out value="${output.result.from}" /> / <c:out value="${output.result.through}" /></dd></div><div><dt><spring:message code="${output.result.dimension == 'INSTITUTION' ? 'statement.latestBranchCutoff' : 'report.cutoff'}" /></dt><dd><c:out value="${output.result.recordedCutoff}" /></dd></div><div><dt><spring:message code="statement.export.generated" /></dt><dd><c:out value="${output.generatedAt}" /></dd></div><div><dt><spring:message code="statement.export.review" /></dt><dd><c:choose><c:when test="${not empty output.reviewer}"><spring:message code="accounting.release.state.APPROVED" /></c:when><c:otherwise><spring:message code="accounting.release.state.PENDING" /></c:otherwise></c:choose></dd></div></dl>
<sec:authorize access="@access.has(principal,'STATEMENT_EXPORT')"><div class="report-run-actions"><c:forEach items="${artifacts}" var="artifact"><a class="app-btn btn-neutral" href="<c:url value='/finance/statement-outputs/${output.id}/artifacts/${artifact.id}' />"><spring:message code="report.run.download" /> <c:out value="${artifact.format}" /></a></c:forEach></div></sec:authorize>
<c:if test="${not empty output.reviewEvidence}"><p><spring:message code="report.run.evidence" />: <c:out value="${output.reviewEvidence}" /></p></c:if>
<sec:authorize access="@access.has(principal,'STATEMENT_EXPORT') and @access.has(principal,'REPORT_RUN_APPROVE')"><c:if test="${empty output.reviewer && output.generatedBy != outputActor}"><form class="report-run-approval" method="post" action="<c:url value='/finance/statement-outputs/${output.id}/review' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="report.run.evidence" /><input class="aws-control" name="evidence" maxlength="1000" required /></label><button class="app-btn btn-primary"><spring:message code="statement.export.review" /></button></form></c:if></sec:authorize>
</section>
<section class="erp-table-wrap" data-aws-table-region><div class="erp-table-scroll" data-view-position-key="statement-output"><table class="erp-table"><thead><tr><th><spring:message code="statement.export.line" /></th><th><spring:message code="statement.export.unit" /></th><th><spring:message code="statement.export.current" /></th><th><spring:message code="statement.export.status" /></th><c:if test="${output.result.definition.comparison}"><th><spring:message code="statement.export.comparison" /></th><th><spring:message code="statement.export.comparisonStatus" /></th></c:if></tr></thead><tbody><c:forEach items="${output.result.getVisibleRows()}" var="row"><tr><td><c:out value="${rowLabels[row.id]}" /><c:if test="${output.layout.language == 'sw' && not empty row.noteSw}"><br /><c:out value="${row.noteSw}" /></c:if><c:if test="${output.layout.language == 'en' && not empty row.noteEn}"><br /><c:out value="${row.noteEn}" /></c:if></td><td><c:out value="${rowUnits[row.id]}" /></td><td><c:choose><c:when test="${row.current == null}">—</c:when><c:otherwise><c:out value="${currentValues[row.id]}" /></c:otherwise></c:choose></td><td><spring:message code="statement.export.status.${row.status}" /></td><c:if test="${output.result.definition.comparison}"><td><c:choose><c:when test="${row.comparison == null}">—</c:when><c:otherwise><c:out value="${comparisonValues[row.id]}" /></c:otherwise></c:choose></td><td><spring:message code="statement.export.status.${row.comparisonStatus}" /></td></c:if></tr></c:forEach></tbody></table></div></section>
<section class="report-run-detail"><h2><spring:message code="statement.export.disclosures" /></h2><c:forEach items="${disclosures}" var="disclosure"><p><c:out value="${disclosure.value}" /></p></c:forEach></section>
</c:when><c:otherwise>
<section class="erp-table-wrap" data-aws-table-region><div class="erp-table-scroll" data-view-position-key="statement-outputs"><table class="erp-table"><thead><tr><th><spring:message code="report.run.report" /></th><th><spring:message code="report.period" /></th><th><spring:message code="statement.export.generated" /></th><th><spring:message code="common.actions" /></th></tr></thead><tbody><c:forEach items="${outputs}" var="item"><tr><td><c:out value="${pageContext.response.locale.language == 'sw' ? item.titleSw : item.titleEn}" /></td><td><c:out value="${item.from}" /> / <c:out value="${item.through}" /></td><td><c:out value="${item.generatedAt}" /></td><td><a class="app-btn btn-neutral" href="<c:url value='/finance/statement-outputs/${item.id}' />"><spring:message code="common.view" /></a></td></tr></c:forEach><c:if test="${empty outputs}"><tr><td colspan="4"><spring:message code="report.run.empty" /></td></tr></c:if></tbody></table></div><div class="report-run-actions"><c:if test="${page > 0}"><a class="app-btn btn-neutral" href="<c:url value='/finance/statement-outputs?page=${page-1}' />"><spring:message code="common.previous" /></a></c:if><c:if test="${outputs.size() == 25}"><a class="app-btn btn-neutral" href="<c:url value='/finance/statement-outputs?page=${page+1}' />"><spring:message code="common.next" /></a></c:if></div></section>
<sec:authorize access="@access.has(principal,'STATEMENT_EXPORT')"><c:if test="${not empty resultId}"><form class="report-run-request" method="post" action="<c:url value='/finance/statement-outputs' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="resultId" value="${resultId}" /><h2><spring:message code="statement.export.capture" /></h2><div class="report-run-grid"><label><spring:message code="report.language" /><select class="aws-control" name="language"><option value="en" ${outputLanguage == 'en' ? 'selected' : ''}>English</option><option value="sw" ${outputLanguage == 'sw' ? 'selected' : ''}>Kiswahili</option></select></label><label><input type="checkbox" name="landscape" value="true" ${outputLandscape ? 'checked' : ''} /><spring:message code="report.landscape" /></label><label><input type="checkbox" name="institutionLogo" value="true" ${outputLogo ? 'checked' : ''} /><spring:message code="report.logo" /></label></div><button class="app-btn btn-primary"><spring:message code="statement.export.capture" /></button></form></c:if></sec:authorize>
</c:otherwise></c:choose></main>
<%@ include file="../fragments/footer.jspf" %>
