<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/accounting-ledger.css' />" />
<link rel="stylesheet" href="<c:url value='/css/financial-report.css' />" />
<div class="accounting-workspace financial-report">
  <div class="erp-page-header" data-aws-page-header><h1 class="erp-page-title"><spring:message code="financial.cash.title" /></h1></div>
  <p><spring:message code="financial.cash.basis" /></p>
  <c:if test="${not empty cashError}"><p role="alert"><spring:message code="${cashError}" /></p></c:if>
  <c:if test="${not empty cashSuccess}"><p role="status"><spring:message code="${cashSuccess}" /></p></c:if>
  <form class="accounting-form" method="get" data-aws-filter-toolbar><label><spring:message code="financial.cash.source" /><select class="aws-control" name="journal" required><option value=""><spring:message code="financial.cash.selectSource" /></option><c:forEach items="${choices}" var="choice"><option value="${choice.id}"><c:out value="${choice.reference}" /> · <c:out value="${choice.date}" /></option></c:forEach></select></label><button class="app-btn btn-neutral"><spring:message code="financial.cash.inspect" /></button></form>
  <c:if test="${not empty source}">
    <section class="erp-panel"><div class="erp-panel-header"><h2><c:out value="${source.sourceReference}" /></h2></div><div class="erp-table-scroll" data-aws-table-region><table class="erp-table"><thead><tr><th><spring:message code="financial.cash.account" /></th><th><spring:message code="financial.cash.posted" /></th></tr></thead><tbody><c:forEach items="${source.lines}" var="line"><tr><td><c:out value="${line.code}" /></td><td class="tabular-nums"><c:out value="${line.signedAmount}" /> TZS</td></tr></c:forEach></tbody></table></div></section>
    <sec:authorize access="@access.has(principal,'ACCOUNTING_CASH_FLOW_CREATE')">
      <form class="accounting-form" method="post" action="<c:url value='/reports/financial/cash-flow/draft' />">
        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="journal" value="${source.journalId}" /><input type="hidden" name="requestKey" value="${requestKey}" />
        <p><spring:message code="financial.cash.allocateHelp" /></p>
        <div class="erp-table-scroll" data-aws-table-region><table class="erp-table"><thead><tr><th><spring:message code="financial.cash.moneyAccount" /></th><th><spring:message code="financial.cash.counterpart" /></th><th><spring:message code="financial.cash.activity" /></th><th><spring:message code="financial.cash.signedAmount" /></th></tr></thead><tbody>
          <c:forEach items="${candidates}" var="row"><tr><td><c:out value="${row.moneyCode}" /> (<c:out value="${row.postedAmount}" /> TZS)<input type="hidden" name="moneyLineId" value="${row.moneyLineId}" /></td><td><c:out value="${row.counterpartCode}" /><input type="hidden" name="counterpartAccountId" value="${row.counterpartAccountId}" /></td><td><select class="aws-control" name="activity"><c:choose><c:when test="${row.transfer}"><option value="INTERNAL_TRANSFER"><spring:message code="financial.cash.activity.INTERNAL_TRANSFER" /></option></c:when><c:otherwise><c:forEach items="${['OPERATING','INVESTING','FINANCING']}" var="activity"><option value="${activity}"><spring:message code="financial.cash.activity.${activity}" /></option></c:forEach></c:otherwise></c:choose></select></td><td><input class="aws-control" name="amount" type="text" inputmode="decimal" aria-label="<spring:message code='financial.cash.signedAmount' htmlEscape='true' />" maxlength="22" /></td></tr></c:forEach>
        </tbody></table></div>
        <label><spring:message code="financial.cash.evidence" /><textarea class="aws-control" name="evidence" required maxlength="1000"></textarea></label><label><spring:message code="financial.cash.noncashEvidence" /><textarea class="aws-control" name="noncashEvidence" maxlength="1000"></textarea></label><button class="app-btn btn-primary"><spring:message code="financial.cash.save" /></button>
      </form>
    </sec:authorize>
  </c:if>
  <section class="erp-panel"><div class="erp-panel-header"><h2><spring:message code="financial.cash.history" /></h2></div><c:if test="${empty versions}"><p><spring:message code="financial.cash.empty" /></p></c:if>
    <c:forEach items="${versions}" var="version"><div class="accounting-form"><h3><c:out value="${version.source.sourceReference}" /> · <spring:message code="financial.cash.version" /> <c:out value="${version.version}" /></h3><p><c:out value="${version.evidence}" /></p><c:if test="${not empty version.noncashEvidence}"><p><c:out value="${version.noncashEvidence}" /></p></c:if>
      <div class="erp-table-scroll" data-aws-table-region><table class="erp-table"><thead><tr><th><spring:message code="financial.cash.account" /></th><th><spring:message code="financial.cash.activity" /></th><th><spring:message code="financial.cash.signedAmount" /></th></tr></thead><tbody><c:forEach items="${version.splits}" var="split"><tr><td><c:forEach items="${version.source.lines}" var="line"><c:if test="${line.accountId == split.counterpartAccountId}"><c:out value="${line.code}" /> </c:if></c:forEach></td><td><spring:message code="financial.cash.activity.${split.activity}" /></td><td><c:out value="${split.signedAmount}" /> TZS</td></tr></c:forEach></tbody></table></div>
      <c:choose><c:when test="${version.approved()}"><p><spring:message code="financial.cash.reviewed" /> · <c:out value="${version.reviewedAt}" /></p><p><c:out value="${version.reviewEvidence}" /></p><c:if test="${supersededVersions.contains(version.id)}"><p><spring:message code="financial.cash.superseded" /></p></c:if></c:when><c:when test="${supersededVersions.contains(version.id)}"><p><spring:message code="financial.cash.superseded" /></p></c:when><c:otherwise><p><spring:message code="financial.cash.awaitingReview" /></p><sec:authorize access="@access.has(principal,'ACCOUNTING_CASH_FLOW_APPROVE')"><c:if test="${version.maker != principal.memberId}"><form method="post" action="<c:url value='/reports/financial/cash-flow/${version.id}/approve' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="financial.cash.reviewEvidence" /><textarea class="aws-control" name="evidence" required maxlength="1000"></textarea></label><button class="app-btn btn-primary"><spring:message code="financial.cash.approve" /></button></form></c:if></sec:authorize></c:otherwise></c:choose>
    </div></c:forEach>
  </section>
  <div class="accounting-actions"><c:if test="${page > 0}"><c:url value="/reports/financial/cash-flow" var="previous"><c:param name="page" value="${page-1}" /></c:url><a class="app-btn btn-neutral" href="${previous}"><spring:message code="common.previous" /></a></c:if><c:if test="${hasNext}"><c:url value="/reports/financial/cash-flow" var="next"><c:param name="page" value="${page+1}" /></c:url><a class="app-btn btn-neutral" href="${next}"><spring:message code="common.next" /></a></c:if></div>
</div>
<%@ include file="../fragments/footer.jspf" %>
