<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/accounting-ledger.css' />" />
<link rel="stylesheet" href="<c:url value='/css/financial-report.css' />" />
<div class="accounting-workspace financial-report">
  <div class="erp-page-header"><h1 class="erp-page-title"><spring:message code="financial.portfolio.menu" /></h1></div>
  <form class="accounting-form financial-filters" method="get" action="<c:url value='/reports/financial/portfolio' />">
    <div class="accounting-grid">
      <label><spring:message code="financial.report.from" /><input class="aws-control" type="date" name="from" value="<c:out value='${report.parameters.from}' />" required /></label>
      <label><spring:message code="financial.report.through" /><input class="aws-control" type="date" name="through" value="<c:out value='${report.parameters.through}' />" required /></label>
      <label><spring:message code="financial.report.recordedThrough" /><input class="aws-control" type="datetime-local" step="1" name="recordedThrough" value="<c:out value='${cutoffInput}' />" required /><span><c:out value="${reportZone}" /></span></label>
      <sec:authorize access="@access.has(principal, 'FINANCIAL_REPORTS_INSTITUTION')"><label><spring:message code="financial.report.scope" /><select class="aws-control" name="institutionWide"><option value="false" ${not report.scope.institutionWide ? 'selected' : ''}><spring:message code="financial.report.branch" /></option><option value="true" ${report.scope.institutionWide ? 'selected' : ''}><spring:message code="financial.report.institution" /></option></select></label></sec:authorize>
    </div>
    <button class="app-btn btn-primary" type="submit"><spring:message code="financial.report.run" /></button>
  </form>
  <div class="financial-context"><span><spring:message code="financial.report.draft" /></span><span>TZS</span><span><spring:message code="${report.scope.institutionWide ? 'financial.report.institution' : 'financial.report.branch'}" /></span></div>
  <p><spring:message code="financial.portfolio.basis" /></p>
  <p role="status"><spring:message code="financial.portfolio.coveredSubset" /> <spring:message code="financial.portfolio.covered" />: <c:out value="${report.summary.covered}" />; <spring:message code="financial.portfolio.excluded" />: <c:out value="${report.summary.excluded}" />.</p>
  <p><spring:message code="financial.report.missingOpenings" />: <c:out value="${report.bookCoverage.missingOpenings}" />; <spring:message code="financial.report.unbridged" />: <c:out value="${report.bookCoverage.unbridgedVouchers}" />; <spring:message code="financial.report.uncovered" />: <c:out value="${report.bookCoverage.uncoveredLoans}" />.</p>
  <section class="erp-table-wrap"><div class="erp-table-scroll erp-table-scroll-sm"><table class="erp-table"><thead><tr><th><spring:message code="financial.portfolio.measure" /></th><th class="financial-number">TZS</th></tr></thead><tbody>
    <c:forEach items="${['principal','overduePrincipal','overdueInterest','disbursed','collectedPrincipal','collectedInterest']}" var="field"><tr><td><spring:message code="financial.portfolio.${field}" /></td><td class="financial-number"><fmt:formatNumber value="${report.summary[field]}" minFractionDigits="2" maxFractionDigits="2" /></td></tr></c:forEach>
    <c:forEach items="${['fees','allowance','writeOff','recovery']}" var="field"><tr><td><spring:message code="financial.portfolio.${field}" /></td><td><spring:message code="financial.report.unknown" /></td></tr></c:forEach>
  </tbody></table></div></section>
  <p><spring:message code="financial.portfolio.advanced" /></p>
  <section class="erp-table-wrap"><div class="erp-table-scroll erp-table-scroll-sm"><table class="erp-table"><thead><tr><th><spring:message code="financial.portfolio.par" /></th><th class="financial-number"><spring:message code="financial.portfolio.exposed" /> (TZS)</th><th class="financial-number"><spring:message code="financial.portfolio.percentage" /></th></tr></thead><tbody>
    <c:forEach items="${['par1','par30','par90']}" var="field"><tr><td><spring:message code="financial.portfolio.${field}" /></td><td class="financial-number"><fmt:formatNumber value="${report.summary[field]}" minFractionDigits="2" maxFractionDigits="2" /></td><td class="financial-number"><c:choose><c:when test="${report.ratios[field] == null}"><spring:message code="financial.report.unknown" /></c:when><c:otherwise><fmt:formatNumber value="${report.ratios[field]}" minFractionDigits="6" maxFractionDigits="6" />%</c:otherwise></c:choose></td></tr></c:forEach>
  </tbody></table></div></section>
  <p><spring:message code="financial.portfolio.parDefinition" /></p>
  <h2><spring:message code="financial.portfolio.ageing" /></h2>
  <section class="erp-table-wrap"><div class="erp-table-scroll erp-table-scroll-sm"><table class="erp-table"><thead><tr><th><spring:message code="financial.portfolio.band" /></th><th><spring:message code="financial.portfolio.covered" /></th><th class="financial-number"><spring:message code="financial.portfolio.principal" /> (TZS)</th></tr></thead><tbody><c:forEach items="${report.ageing}" var="b"><tr><td><spring:message code="financial.portfolio.age.${b.band}" /></td><td><c:out value="${b.loans}" /></td><td class="financial-number"><fmt:formatNumber value="${b.principal}" minFractionDigits="2" maxFractionDigits="2" /></td></tr></c:forEach><c:if test="${empty report.ageing}"><tr><td colspan="3"><spring:message code="financial.report.empty" /></td></tr></c:if></tbody></table></div></section>
  <h2><spring:message code="financial.portfolio.classification" /></h2>
  <p><spring:message code="financial.portfolio.regulatoryNote" /></p>
  <section class="erp-table-wrap"><div class="erp-table-scroll erp-table-scroll-sm"><table class="erp-table"><thead><tr><th><spring:message code="financial.portfolio.band" /></th><th><spring:message code="financial.portfolio.covered" /></th><th class="financial-number"><spring:message code="financial.portfolio.principal" /> (TZS)</th></tr></thead><tbody><c:forEach items="${report.classificationReference}" var="b"><tr><td><spring:message code="financial.portfolio.reg.${b.band}" /></td><td><c:out value="${b.loans}" /></td><td class="financial-number"><fmt:formatNumber value="${b.principal}" minFractionDigits="2" maxFractionDigits="2" /></td></tr></c:forEach><c:if test="${empty report.classificationReference}"><tr><td colspan="3"><spring:message code="financial.report.empty" /></td></tr></c:if></tbody></table></div></section>
  <c:if test="${report.scope.institutionWide}"><h2><spring:message code="financial.portfolio.branches" /></h2><section class="erp-table-wrap"><div class="erp-table-scroll" data-view-position-key="financial-portfolio-branches"><table class="erp-table"><thead><tr><th><spring:message code="financial.report.branch" /></th><th><spring:message code="financial.portfolio.covered" /></th><th><spring:message code="financial.portfolio.excluded" /></th><th class="financial-number"><spring:message code="financial.portfolio.principal" /> (TZS)</th><th class="financial-number"><spring:message code="financial.portfolio.par30" /> (TZS)</th><th class="financial-number"><spring:message code="financial.portfolio.disbursed" /> (TZS)</th></tr></thead><tbody><c:forEach items="${report.branches}" var="b"><tr><td><c:out value="${b.branch}" /></td><td><c:out value="${b.summary.covered}" /></td><td><c:out value="${b.summary.excluded}" /></td><c:forEach items="${['principal','par30','disbursed']}" var="field"><td class="financial-number"><fmt:formatNumber value="${b.summary[field]}" minFractionDigits="2" maxFractionDigits="2" /></td></c:forEach></tr></c:forEach></tbody></table></div></section></c:if>
  <c:if test="${not report.scope.institutionWide}"><h2><spring:message code="financial.portfolio.loans" /></h2><section class="erp-table-wrap"><div class="erp-table-scroll" data-view-position-key="financial-portfolio-loans"><table class="erp-table"><thead><tr><th><spring:message code="financial.portfolio.loan" /></th><th class="financial-number"><spring:message code="financial.portfolio.principal" /> (TZS)</th><th class="financial-number"><spring:message code="financial.portfolio.overduePrincipal" /> (TZS)</th><th class="financial-number"><spring:message code="financial.portfolio.overdueInterest" /> (TZS)</th><th><spring:message code="financial.portfolio.oldest" /></th><th><spring:message code="financial.portfolio.coverage" /></th></tr></thead><tbody><c:forEach items="${report.rows}" var="r"><tr><td><c:out value="${r.number}" /></td><c:forEach items="${['principal','overduePrincipal','overdueInterest']}" var="field"><td class="financial-number"><c:choose><c:when test="${r[field] == null}"><spring:message code="financial.report.unknown" /></c:when><c:otherwise><fmt:formatNumber value="${r[field]}" minFractionDigits="2" maxFractionDigits="2" /></c:otherwise></c:choose></td></c:forEach><td><c:out value="${r.oldest}" /></td><td><spring:message code="${r.complete ? 'financial.portfolio.verified' : 'financial.portfolio.unverified'}" /></td></tr></c:forEach><c:if test="${empty report.rows}"><tr><td colspan="6"><spring:message code="financial.report.empty" /></td></tr></c:if></tbody></table></div></section>
    <div class="accounting-actions"><c:if test="${report.parameters.page > 0}"><c:url value="/reports/financial/portfolio" var="previousUrl"><c:param name="from" value="${report.parameters.from}" /><c:param name="through" value="${report.parameters.through}" /><c:param name="recordedThrough" value="${cutoffInput}" /><c:param name="page" value="${report.parameters.page-1}" /></c:url><a class="app-btn btn-neutral" href="<c:out value='${previousUrl}' />"><spring:message code="common.previous" /></a></c:if><c:if test="${report.hasNext}"><c:url value="/reports/financial/portfolio" var="nextUrl"><c:param name="from" value="${report.parameters.from}" /><c:param name="through" value="${report.parameters.through}" /><c:param name="recordedThrough" value="${cutoffInput}" /><c:param name="page" value="${report.parameters.page+1}" /></c:url><a class="app-btn btn-neutral" href="<c:out value='${nextUrl}' />"><spring:message code="common.next" /></a></c:if></div>
  </c:if>
  <p><spring:message code="financial.portfolio.definitions" />: <c:out value="${report.definitionsVersion}" /> / <c:out value="${report.regulatoryReference}" />.</p>
</div>
<%@ include file="../fragments/footer.jspf" %>
