<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/accounting-ledger.css' />" />
<div class="ledger-workspace">
 <div class="erp-page-header"><h1 class="erp-page-title"><spring:message code="accounting.ledger.journal" /></h1></div>
 <dl class="ledger-facts"><div><dt><spring:message code="accounting.ledger.description" /></dt><dd><c:out value="${journal.description}" /></dd></div><div><dt><spring:message code="accounting.ledger.effectiveDate" /></dt><dd><c:out value="${journal.effectiveDate}" /></dd></div><div><dt><spring:message code="common.status" /></dt><dd><spring:message code="accounting.ledger.state.${journal.state}" /></dd></div><div><dt><spring:message code="accounting.ledger.evidence" /></dt><dd><c:out value="${journal.evidenceReference}" /></dd></div><div><dt><spring:message code="accounting.ledger.policyVersion" /></dt><dd><c:out value="${journal.policyVersion}" /></dd></div><div><dt><spring:message code="accounting.ledger.currency" /></dt><dd>TZS</dd></div></dl>
 <c:if test="${not empty journal.reversesJournalId}"><p class="ledger-notice"><spring:message code="accounting.ledger.linkedReversal" /> <a href="<c:url value='/accounting/journals/${journal.reversesJournalId}' />"><spring:message code="accounting.ledger.original" /></a>: <c:out value="${journal.reversalReason}" /></p></c:if>
 <section class="erp-table-wrap"><div class="erp-table-scroll erp-table-scroll-sm"><table class="erp-table"><thead><tr><th><spring:message code="accounting.ledger.code" /></th><th><spring:message code="accounting.ledger.name" /></th><th class="money"><spring:message code="accounting.ledger.debit" /> (TZS)</th><th class="money"><spring:message code="accounting.ledger.credit" /> (TZS)</th><th><spring:message code="accounting.ledger.memo" /></th></tr></thead><tbody><c:forEach items="${journal.lines}" var="line"><tr><td><c:out value="${line.accountCode}" /></td><td><c:out value="${line.accountName}" /></td><td class="money"><fmt:formatNumber value="${line.debit}" minFractionDigits="2" maxFractionDigits="2" /></td><td class="money"><fmt:formatNumber value="${line.credit}" minFractionDigits="2" maxFractionDigits="2" /></td><td><c:out value="${line.memo}" /></td></tr></c:forEach></tbody></table></div></section>
 <c:if test="${journal.state=='DRAFT' and journal.sourceKind!='OPENING'}"><sec:authorize access="@access.has(principal, 'ACCOUNTING_JOURNAL_APPROVE')"><section><h2><spring:message code="accounting.ledger.approve" /></h2><form method="post" action="<c:url value='/accounting/journals/${journal.id}/approve' />" class="ledger-form"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="accounting.ledger.reviewEvidence" /><input class="aws-control" name="evidenceReference" maxlength="500" required /></label><button type="submit" class="app-btn btn-primary"><spring:message code="accounting.ledger.approve" /></button></form></section></sec:authorize></c:if>
 <c:if test="${journal.state=='APPROVED'}"><sec:authorize access="@access.has(principal, 'ACCOUNTING_JOURNAL_POST')"><section><form method="post" action="<c:url value='/accounting/journals/${journal.id}/post' />" class="ledger-form"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label class="ledger-confirm ledger-wide"><input type="checkbox" required /><span><spring:message code="accounting.ledger.confirmPost" /></span></label><button type="submit" class="app-btn btn-primary"><spring:message code="accounting.ledger.post" /></button></form></section></sec:authorize></c:if>
 <c:if test="${journal.state=='POSTED' and (journal.sourceKind=='MANUAL' or journal.sourceKind=='OPENING')}"><sec:authorize access="@access.has(principal, 'ACCOUNTING_JOURNAL_REVERSE')"><section><h2><spring:message code="accounting.ledger.reverse" /></h2><form method="post" action="<c:url value='/accounting/journals/${journal.id}/reverse' />" class="ledger-form"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="requestKey" value="${requestKey}" /><label><spring:message code="accounting.ledger.effectiveDate" /><input class="aws-control" name="effectiveDate" type="date" required /></label><label><spring:message code="accounting.ledger.reason" /><input class="aws-control" name="reason" maxlength="500" required /></label><label><spring:message code="accounting.ledger.evidence" /><input class="aws-control" name="evidenceReference" maxlength="500" required /></label><button type="submit" class="app-btn btn-neutral"><spring:message code="accounting.ledger.reverse" /></button></form></section></sec:authorize></c:if>
</div>
<%@ include file="../fragments/footer.jspf" %>
