<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/accounting-ledger.css' />" />
<div class="accounting-workspace">
<c:if test="${not empty accountingError}"><p role="alert"><spring:message code="${accountingError}" /></p></c:if>
<c:if test="${not empty accountingSuccess}"><p role="status"><spring:message code="${accountingSuccess}" /></p></c:if>
<div class="erp-page-header"><h1 class="erp-page-title"><c:out value="${journal.sourceReference}" /></h1></div>
<p><spring:message code="accounting.state.${journal.state}" /> <c:if test="${journal.reversed}"><spring:message code="accounting.reversed" /></c:if> · <c:out value="${journal.effectiveDate}" /> · TZS</p>
<p><spring:message code="accounting.evidence" />: <c:out value="${journal.evidenceReference}" /></p><p><c:out value="${journal.reason}" /></p>
<section class="erp-table-wrap"><div class="erp-table-scroll" data-view-position-key="gl-journal-lines"><table class="erp-table"><thead><tr><th><spring:message code="accounting.code" /></th><th><spring:message code="accounting.name" /></th><th><spring:message code="accounting.debit" /> TZS</th><th><spring:message code="accounting.credit" /> TZS</th></tr></thead><tbody><c:forEach items="${lines}" var="l"><tr><td><c:out value="${l.code}" /></td><td><c:out value="${l.name}" /></td><td class="accounting-money"><c:out value="${l.debit}" /></td><td class="accounting-money"><c:out value="${l.credit}" /></td></tr></c:forEach></tbody></table></div></section>
<sec:authorize access="@access.hasAny(principal, 'ACCOUNTING_JOURNALS_APPROVE', 'ACCOUNTING_OPENINGS_APPROVE')"><c:if test="${journal.state=='DRAFT' and journal.makerId ne pageContext.request.userPrincipal.principal.memberId}"><section class="accounting-form"><h2><spring:message code="accounting.approve" /></h2><form method="post" action="<c:url value='/finance/journals/${journal.id}/approve' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="accounting.reviewEvidence" /><input class="aws-control" name="evidence" maxlength="500" required /></label><button class="app-btn btn-primary"><spring:message code="accounting.approve" /></button></form></section></c:if>
<c:if test="${journal.state=='APPROVED' and journal.checkerId eq pageContext.request.userPrincipal.principal.memberId}"><section class="accounting-form"><form method="post" action="<c:url value='/finance/journals/${journal.id}/post' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><c:if test="${journal.sourceType=='OPENING'}"><label><input type="checkbox" name="openingReconciled" value="true" required /><spring:message code="accounting.openingAttestation" /></label></c:if><label><input type="checkbox" name="confirmed" value="true" required /><spring:message code="accounting.postAttestation" /></label><button class="app-btn btn-primary"><spring:message code="accounting.post" /></button></form></section></c:if></sec:authorize>
<sec:authorize access="@access.has(principal, 'ACCOUNTING_JOURNALS_REVERSE')"><c:if test="${journal.state=='POSTED' and journal.sourceType=='MANUAL' and not journal.reversed and journal.makerId ne pageContext.request.userPrincipal.principal.memberId and journal.checkerId ne pageContext.request.userPrincipal.principal.memberId}"><section class="accounting-form"><h2><spring:message code="accounting.reverse" /></h2><form method="post" action="<c:url value='/finance/journals/${journal.id}/reverse' />"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="requestKey" value="${requestKey}" /><div class="accounting-grid"><label><spring:message code="accounting.date" /><input class="aws-control" name="effectiveDate" type="date" required /></label><label><spring:message code="accounting.reason" /><input class="aws-control" name="reason" maxlength="500" required /></label><label><spring:message code="accounting.evidence" /><input class="aws-control" name="evidence" maxlength="500" required /></label></div><label><input type="checkbox" name="confirmed" value="true" required /><spring:message code="accounting.reversalAttestation" /></label><button class="app-btn btn-neutral"><spring:message code="accounting.reverse" /></button></form></section></c:if></sec:authorize>
</div>
<%@ include file="../fragments/footer.jspf" %>
