<%@ include file="../fragments/header.jspf" %>
<%@ include file="../fragments/sidebar.jspf" %>
<link rel="stylesheet" href="<c:url value='/css/accounting-ledger.css' />" />
<div class="ledger-workspace">
 <div class="erp-page-header"><h1 class="erp-page-title"><spring:message code="accounting.ledger.openings" /></h1></div>
 <p class="ledger-notice"><spring:message code="accounting.ledger.coverage.${coverage.status}" /> <spring:message code="accounting.ledger.unknownLoans" />: <c:out value="${coverage.unknownLoans}" />; <spring:message code="accounting.ledger.unbridged" />: <c:out value="${coverage.unbridgedVouchers}" /></p>
 <section class="erp-table-wrap"><div class="erp-table-scroll"><table class="erp-table"><thead><tr><th><spring:message code="accounting.ledger.cutoff" /></th><th><spring:message code="accounting.ledger.evidence" /></th><th><spring:message code="common.status" /></th><th><spring:message code="common.actions" /></th></tr></thead><tbody><c:forEach items="${rows.content}" var="row"><tr><td><c:out value="${row.cutoff}" /></td><td><c:out value="${row.sourceEvidence}" /></td><td><c:choose><c:when test="${row.kind=='ZERO_CERTIFICATE' and row.state=='APPROVED'}"><spring:message code="accounting.ledger.zeroApproved" /></c:when><c:otherwise><spring:message code="accounting.ledger.state.${row.state}" /></c:otherwise></c:choose></td><td><c:if test="${not empty row.journalId}"><a class="app-btn btn-neutral" href="<c:url value='/accounting/journals/${row.journalId}' />"><spring:message code="common.view" /></a></c:if>
  <c:if test="${row.state=='PREVIEW'}"><sec:authorize access="@access.has(principal, 'ACCOUNTING_OPENING_APPROVE')"><form method="post" action="<c:url value='/accounting/openings/${row.id}/approve' />" class="ledger-actions"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><label><spring:message code="accounting.ledger.reviewEvidence" /><input class="aws-control" name="evidenceReference" maxlength="500" required /></label><button type="submit" class="app-btn btn-neutral"><spring:message code="accounting.ledger.approve" /></button></form></sec:authorize></c:if>
  <c:if test="${(row.state=='POSTED' or (row.kind=='ZERO_CERTIFICATE' and row.state=='APPROVED')) and not coverage.reviewedOpening}"><sec:authorize access="@access.has(principal, 'ACCOUNTING_CUTOVER_APPROVE')"><form method="post" action="<c:url value='/accounting/cutover' />" class="ledger-actions"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="batchId" value="${row.id}" /><label><spring:message code="accounting.ledger.reviewEvidence" /><input class="aws-control" name="evidenceReference" maxlength="500" required /></label><button type="submit" class="app-btn btn-neutral"><spring:message code="accounting.ledger.reviewCutover" /></button></form></sec:authorize></c:if>
 </td></tr></c:forEach><c:if test="${empty rows.content}"><tr><td colspan="4" class="erp-table-empty"><spring:message code="accounting.ledger.empty" /></td></tr></c:if></tbody></table></div><c:set var="ledgerPagePath" value="/accounting/openings" /><%@ include file="pagination.jspf" %></section>
 <sec:authorize access="@access.has(principal, 'ACCOUNTING_OPENING_MANAGE')"><section><h2><spring:message code="accounting.ledger.previewOpening" /></h2><form method="post" action="<c:url value='/accounting/openings' />" class="ledger-form"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="requestKey" value="${requestKey}" /><label><spring:message code="accounting.ledger.cutoff" /><input class="aws-control" name="cutoff" type="date" required /></label><label><spring:message code="accounting.ledger.evidence" /><input class="aws-control" name="evidenceReference" maxlength="500" required /></label><label class="ledger-wide"><spring:message code="accounting.ledger.lines" /><small><spring:message code="accounting.ledger.linesHelp" /></small><textarea class="aws-control" name="lines" rows="5" maxlength="64000" required></textarea></label><button type="submit" class="app-btn btn-primary"><spring:message code="accounting.ledger.previewOpening" /></button></form></section></sec:authorize>
 <sec:authorize access="@access.has(principal, 'ACCOUNTING_OPENING_MANAGE')"><section><h2><spring:message code="accounting.ledger.zeroCertificate" /></h2><form method="post" action="<c:url value='/accounting/openings/zero' />" class="ledger-form"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="requestKey" value="${zeroRequestKey}" /><label><spring:message code="accounting.ledger.cutoff" /><input class="aws-control" name="cutoff" type="date" required /></label><label><spring:message code="accounting.ledger.evidence" /><input class="aws-control" name="evidenceReference" maxlength="500" required /></label><label class="ledger-confirm ledger-wide"><input type="checkbox" required /><span><spring:message code="accounting.ledger.confirmZero" /></span></label><button type="submit" class="app-btn btn-neutral"><spring:message code="accounting.ledger.zeroCertificate" /></button></form></section></sec:authorize>
 <sec:authorize access="@access.has(principal, 'ACCOUNTING_JOURNAL_DRAFT')"><section><h2><spring:message code="accounting.ledger.bridge" /></h2><form method="post" action="<c:url value='/accounting/bridge' />" class="ledger-form"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" /><input type="hidden" name="requestKey" value="${bridgeRequestKey}" /><label><spring:message code="accounting.ledger.voucher" /><input class="aws-control" name="voucher" required /></label><label><spring:message code="accounting.ledger.evidence" /><input class="aws-control" name="evidenceReference" maxlength="500" required /></label><label class="ledger-wide"><spring:message code="accounting.ledger.mapping" /><small><spring:message code="accounting.ledger.mappingHelp" /></small><textarea class="aws-control" name="mapping" maxlength="2000" required></textarea></label><button type="submit" class="app-btn btn-neutral"><spring:message code="accounting.ledger.saveDraft" /></button></form></section></sec:authorize>
</div>
<%@ include file="../fragments/footer.jspf" %>
