package com.sacco.mvp.reporting.execution.repository;

import com.sacco.mvp.reporting.execution.dto.AccountingReleaseDtos.*;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import tools.jackson.databind.ObjectMapper;
import java.sql.*;
import java.time.OffsetDateTime;
import java.util.*;

@Repository @RequiredArgsConstructor
public class AccountingReleaseRepository {
 private final JdbcTemplate jdbc;
 private final ObjectMapper mapper;
 private static final String SELECT="SELECT r.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('stage',d.stage,'approved',d.approved,'reviewer',d.reviewer,'evidence',d.evidence,'at',d.decided_at) ORDER BY CASE d.stage WHEN 'ACCOUNTANT' THEN 1 WHEN 'COMPLIANCE' THEN 2 ELSE 3 END) FROM accounting_release_decisions d WHERE d.release_id=r.id),'[]'::jsonb)::text decisions_json,EXISTS(SELECT 1 FROM accounting_release_invalidations i WHERE i.release_id=r.id) invalidated FROM accounting_release_requests r ";
 public Optional<Release> get(UUID id,String institution,String branch,boolean lock){if(lock)jdbc.queryForList("SELECT id FROM accounting_release_requests WHERE id=? AND sacco_id=? AND station_id=? FOR UPDATE",UUID.class,id,institution,branch);return jdbc.query(SELECT+"WHERE id=? AND sacco_id=? AND station_id=?",(rs,n)->read(rs),id,institution,branch).stream().findFirst();}
 public List<Release> list(String institution,String branch,int page){return jdbc.query(SELECT+"WHERE sacco_id=? AND station_id=? ORDER BY requested_at DESC,id LIMIT 25 OFFSET ?",(rs,n)->read(rs),institution,branch,page*25);}
 public Optional<UUID> duplicate(String institution,String branch,UUID requester,UUID key){return jdbc.queryForList("SELECT id FROM accounting_release_requests WHERE sacco_id=? AND station_id=? AND requested_by=? AND request_key=?",UUID.class,institution,branch,requester,key).stream().findFirst();}
 public void requestLock(String institution,String branch){jdbc.execute("SELECT pg_advisory_xact_lock(hashtextextended(?,49101))",(org.springframework.jdbc.core.PreparedStatementCallback<Void>)ps->{ps.setString(1,institution+"/"+branch);ps.execute();return null;});}
 public void create(Release r,UUID requestKey){jdbc.update("INSERT INTO accounting_release_requests(id,sacco_id,station_id,request_key,requested_by,requested_at,policy_id,policy_version,period_id,mapping_id,template_id,statement_output_id,first_sample,second_sample,dependency_json,dependency_checksum,proposal_evidence) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",r.id(),r.institution(),r.branch(),requestKey,r.requester(),r.requestedAt(),r.policy(),r.policyVersion(),r.period(),r.mapping(),r.template(),r.statementOutput(),r.firstSample(),r.secondSample(),r.dependencyJson(),r.checksum(),r.evidence());}
 public void decide(UUID id,Stage stage,boolean approved,UUID reviewer,String evidence,OffsetDateTime now){jdbc.update("INSERT INTO accounting_release_decisions(release_id,stage,approved,reviewer,evidence,decided_at) VALUES(?,?,?,?,?,?)",id,stage.name(),approved,reviewer,evidence,now);}
 public boolean live(String institution,String branch,UUID policy,int version){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM accounting_release_requests r WHERE r.sacco_id=? AND r.station_id=? AND r.policy_id=? AND r.policy_version=? AND NOT EXISTS(SELECT 1 FROM accounting_release_invalidations i WHERE i.release_id=r.id) AND (SELECT count(*) FROM accounting_release_decisions d WHERE d.release_id=r.id AND d.approved)=3)",Boolean.class,institution,branch,policy,version));}
 public Optional<UUID> lockLiveCandidate(String institution,String branch,UUID policy,int version){return jdbc.queryForList("SELECT id FROM accounting_release_requests r WHERE sacco_id=? AND station_id=? AND policy_id=? AND policy_version=? AND NOT EXISTS(SELECT 1 FROM accounting_release_invalidations i WHERE i.release_id=r.id) AND (SELECT count(*) FROM accounting_release_decisions d WHERE d.release_id=r.id AND d.approved)=3 ORDER BY requested_at DESC,id LIMIT 1 FOR SHARE",UUID.class,institution,branch,policy,version).stream().findFirst();}
 public boolean liveId(UUID id){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT NOT EXISTS(SELECT 1 FROM accounting_release_invalidations WHERE release_id=?) AND (SELECT count(*) FROM accounting_release_decisions WHERE release_id=? AND approved)=3",Boolean.class,id,id));}
 public int invalidatePeriod(String institution,UUID period,UUID actor,String reason,OffsetDateTime now){return jdbc.update("WITH locked AS MATERIALIZED(SELECT id FROM accounting_release_requests WHERE sacco_id=? AND period_id=? ORDER BY id FOR UPDATE) INSERT INTO accounting_release_invalidations(id,release_id,kind,actor_id,reason,recorded_at) SELECT gen_random_uuid(),id,'PERIOD_REOPENED',?,?,? FROM locked",institution,period,actor,reason,now);}
 public int invalidateFrom(String institution,UUID period,java.time.LocalDate affectedFrom,UUID actor,String reason,OffsetDateTime now){return jdbc.update("WITH locked AS MATERIALIZED(SELECT r.id FROM accounting_release_requests r JOIN statement_output_sets s ON s.id=r.statement_output_id AND s.sacco_id=r.sacco_id WHERE r.sacco_id=? AND (r.period_id=? OR s.result_json::jsonb->>'through'>=?) AND NOT EXISTS(SELECT 1 FROM accounting_release_invalidations i WHERE i.release_id=r.id) ORDER BY r.id FOR UPDATE OF r) INSERT INTO accounting_release_invalidations(id,release_id,kind,actor_id,reason,recorded_at) SELECT gen_random_uuid(),id,'PERIOD_REOPENED',?,?,? FROM locked",institution,period,affectedFrom.toString(),actor,reason,now);}
 public int invalidateMapping(String institution,UUID template,UUID mapping,String kind,UUID actor,String reason,OffsetDateTime now){return jdbc.update("WITH locked AS MATERIALIZED(SELECT id FROM accounting_release_requests WHERE sacco_id=? AND template_id=? AND (?='MAPPING_APPROVED' OR mapping_id=?) ORDER BY id FOR UPDATE) INSERT INTO accounting_release_invalidations(id,release_id,kind,actor_id,reason,recorded_at) SELECT gen_random_uuid(),id,?,?,?,? FROM locked",institution,template,kind,mapping,kind,actor,reason,now);}
 public void withdraw(UUID id,UUID actor,String reason,OffsetDateTime now){jdbc.update("INSERT INTO accounting_release_invalidations(id,release_id,kind,actor_id,reason,recorded_at) VALUES(?,?,'WITHDRAWN',?,?,?)",UUID.randomUUID(),id,actor,reason,now);}
 public boolean hasInstitutionHistory(String institution){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM accounting_release_requests WHERE sacco_id=?) OR EXISTS(SELECT 1 FROM statement_output_sets WHERE sacco_id=?)",Boolean.class,institution,institution));}
 public boolean hasMemberHistory(UUID member){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM accounting_release_requests WHERE requested_by=?) OR EXISTS(SELECT 1 FROM accounting_release_decisions WHERE reviewer=?) OR EXISTS(SELECT 1 FROM accounting_release_invalidations WHERE actor_id=?) OR EXISTS(SELECT 1 FROM statement_output_sets WHERE generated_by=?) OR EXISTS(SELECT 1 FROM statement_output_reviews WHERE reviewer=?)",Boolean.class,member,member,member,member,member));}
 private Release read(ResultSet rs)throws SQLException {UUID id=rs.getObject("id",UUID.class);var decisions=List.of(mapper.readValue(rs.getString("decisions_json"),Decision[].class));return new Release(id,rs.getString("sacco_id"),rs.getString("station_id"),rs.getObject("requested_by",UUID.class),rs.getObject("requested_at",OffsetDateTime.class),rs.getObject("policy_id",UUID.class),rs.getInt("policy_version"),rs.getObject("period_id",UUID.class),rs.getObject("mapping_id",UUID.class),rs.getObject("template_id",UUID.class),rs.getObject("statement_output_id",UUID.class),rs.getObject("first_sample",UUID.class),rs.getObject("second_sample",UUID.class),rs.getString("dependency_json"),rs.getString("dependency_checksum"),rs.getString("proposal_evidence"),decisions,rs.getBoolean("invalidated"));}
}
