package com.sacco.mvp.reporting.execution.repository;

import com.sacco.mvp.reporting.execution.dto.AccountingReleaseDtos.*;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import tools.jackson.databind.ObjectMapper;
import java.sql.*;
import java.time.OffsetDateTime;
import java.util.*;

@Repository @RequiredArgsConstructor
public class AccountingReleaseRepository {
 private final JdbcTemplate jdbc;
 private final ObjectMapper mapper;
 private static final String SELECT="SELECT r.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('stage',d.stage,'approved',d.approved,'reviewer',d.reviewer,'evidence',d.evidence,'at',d.decided_at) ORDER BY CASE d.stage WHEN 'ACCOUNTANT' THEN 1 WHEN 'COMPLIANCE' THEN 2 ELSE 3 END) FROM accounting_release_decisions d WHERE d.release_id=r.id),'[]'::jsonb)::text decisions_json,EXISTS(SELECT 1 FROM accounting_release_invalidations i WHERE i.release_id=r.id) invalidated FROM accounting_release_requests r ";
 public Optional<Release> get(UUID id,String institution,String branch,boolean lock){if(lock)jdbc.queryForList("SELECT id FROM accounting_release_requests WHERE id=? AND sacco_id=? AND station_id=? FOR UPDATE",UUID.class,id,institution,branch);return jdbc.query(SELECT+"WHERE id=? AND sacco_id=? AND station_id=?",(rs,n)->read(rs),id,institution,branch).stream().findFirst();}
 public List<ReleaseSummary> list(String institution,String branch,int page){return list(institution,branch,page,false);}
 public List<ReleaseSummary> list(String institution,String branch,int page,boolean institutionAllowed){return jdbc.query("SELECT r.id,r.policy_version,r.requested_at,CASE WHEN EXISTS(SELECT 1 FROM accounting_release_invalidations i WHERE i.release_id=r.id) THEN 'INVALIDATED' WHEN r.source_guard_version<2 THEN 'REVALIDATION_REQUIRED' WHEN EXISTS(SELECT 1 FROM accounting_release_decisions d WHERE d.release_id=r.id AND NOT d.approved) THEN 'REJECTED' WHEN (SELECT count(*) FROM accounting_release_decisions d WHERE d.release_id=r.id AND d.approved)=3 THEN 'APPROVED' ELSE 'PENDING' END release_state FROM accounting_release_requests r JOIN statement_output_sets s ON s.id=r.statement_output_id AND s.sacco_id=r.sacco_id AND s.station_id=r.station_id WHERE r.sacco_id=? AND r.station_id=? AND (? OR s.result_dimension='BRANCH') ORDER BY r.requested_at DESC,r.id LIMIT 25 OFFSET ?",(rs,n)->new ReleaseSummary(rs.getObject(1,UUID.class),rs.getInt(2),rs.getObject(3,OffsetDateTime.class),rs.getString(4)),institution,branch,institutionAllowed,page*25);}
 public Optional<UUID> duplicate(String institution,String branch,UUID requester,UUID key){return jdbc.queryForList("SELECT id FROM accounting_release_requests WHERE sacco_id=? AND station_id=? AND requested_by=? AND request_key=?",UUID.class,institution,branch,requester,key).stream().findFirst();}
 public void requestLock(String institution,String branch){jdbc.execute("SELECT pg_advisory_xact_lock(hashtextextended(?,49101))",(org.springframework.jdbc.core.PreparedStatementCallback<Void>)ps->{ps.setString(1,institution+"/"+branch);ps.execute();return null;});}
 public void create(Release r,UUID requestKey){jdbc.update("INSERT INTO accounting_release_requests(id,sacco_id,station_id,request_key,requested_by,requested_at,policy_id,policy_version,period_id,mapping_id,template_id,statement_output_id,first_sample,second_sample,dependency_json,dependency_checksum,proposal_evidence,source_guard_version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",r.id(),r.institution(),r.branch(),requestKey,r.requester(),r.requestedAt(),r.policy(),r.policyVersion(),r.period(),r.mapping(),r.template(),r.statementOutput(),r.firstSample(),r.secondSample(),r.dependencyJson(),r.checksum(),r.evidence(),r.sourceGuardVersion());}
 public void createSources(UUID release,String institution,List<com.sacco.mvp.reporting.execution.dto.AccountingReleaseSourceProof.Proof> sources){
  var branches=new ArrayList<Object[]>();var cash=new ArrayList<com.sacco.mvp.reporting.execution.dto.AccountingReleaseSourceProof.CashPin>();
  for(var source:sources){for(var b:source.branches())branches.add(new Object[]{release,b.role(),institution,b.branch(),b.reviewId(),b.version(),b.recordedCutoff(),b.checksum(),b.reviewer(),b.openingId(),b.openingChecksum(),b.openingMaker(),b.openingReviewer()});cash.addAll(source.cashVersions());}
  if(branches.isEmpty()||branches.size()>2000||cash.size()>2000)throw new IllegalArgumentException("accounting.release.error.source");
  jdbc.batchUpdate("INSERT INTO accounting_release_branch_sources(release_id,role,sacco_id,station_id,close_review_id,close_version,recorded_cutoff,close_checksum,close_reviewer,opening_id,opening_checksum,opening_maker,opening_reviewer) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",branches);
  if(cash.isEmpty())return;var ids=cash.stream().map(com.sacco.mvp.reporting.execution.dto.AccountingReleaseSourceProof.CashPin::journalId).distinct().toList();
  var rows=new org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate(jdbc).query("SELECT id,station_id FROM gl_journal WHERE sacco_id=:institution AND id IN(:ids)",Map.of("institution",institution,"ids",ids),(rs,n)->Map.entry(rs.getObject(1,UUID.class),rs.getString(2)));var stations=new HashMap<UUID,String>();for(var row:rows)stations.put(row.getKey(),row.getValue());if(stations.size()!=ids.size())throw new IllegalArgumentException("accounting.release.error.source");
  var values=new ArrayList<Object[]>();for(var p:cash)values.add(new Object[]{release,p.role(),institution,stations.get(p.journalId()),p.journalId(),p.allocationId(),p.version(),p.sourceChecksum(),p.definitionChecksum(),p.reviewer(),p.reviewedAt()});
  jdbc.batchUpdate("INSERT INTO accounting_release_cash_sources(release_id,role,sacco_id,station_id,journal_id,allocation_id,allocation_version,source_checksum,definition_checksum,reviewer,reviewed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",values);
 }
 public int invalidateCashFlow(String institution,UUID journal,int approvedVersion,UUID actor,String reason,OffsetDateTime now){return jdbc.update("WITH locked AS MATERIALIZED(SELECT r.id FROM accounting_release_requests r WHERE r.sacco_id=? AND NOT EXISTS(SELECT 1 FROM accounting_release_invalidations i WHERE i.release_id=r.id) AND EXISTS(SELECT 1 FROM accounting_release_cash_sources c WHERE c.release_id=r.id AND c.sacco_id=r.sacco_id AND c.journal_id=? AND c.allocation_version<?) ORDER BY r.id FOR UPDATE OF r) INSERT INTO accounting_release_invalidations(id,release_id,kind,actor_id,reason,recorded_at) SELECT gen_random_uuid(),id,'CASH_FLOW_APPROVED',?,?,? FROM locked",institution,journal,approvedVersion,actor,reason,now);}
 public void decide(UUID id,Stage stage,boolean approved,UUID reviewer,String evidence,OffsetDateTime now){jdbc.update("INSERT INTO accounting_release_decisions(release_id,stage,approved,reviewer,evidence,decided_at) VALUES(?,?,?,?,?,?)",id,stage.name(),approved,reviewer,evidence,now);}
 /** The latest fully accepted release governs a branch even after withdrawal or source invalidation.
  * Filtering invalidations before selecting would silently revive an older acceptance. */
 private static final String LATEST_ACCEPTED="SELECT r.id FROM accounting_release_requests r JOIN accounting_release_decisions staff ON staff.release_id=r.id AND staff.stage='STAFF' AND staff.approved WHERE r.sacco_id=? AND EXISTS(SELECT 1 FROM accounting_release_branch_sources b WHERE b.release_id=r.id AND b.sacco_id=r.sacco_id AND b.station_id=? AND b.role='CURRENT') AND r.policy_id=? AND r.policy_version=? AND (SELECT count(*) FROM accounting_release_decisions d WHERE d.release_id=r.id AND d.approved)=3 ORDER BY staff.decided_at DESC,r.requested_at DESC,r.id DESC LIMIT 1";
 public boolean live(String institution,String branch,UUID policy,int version){return latestAccepted(institution,branch,policy,version).map(this::liveId).orElse(false);}
 private Optional<UUID> latestAccepted(String institution,String branch,UUID policy,int version){return jdbc.queryForList(LATEST_ACCEPTED,UUID.class,institution,branch,policy,version).stream().findFirst();}
 public Optional<UUID> lockLiveCandidate(String institution,String branch,UUID policy,int version){return jdbc.queryForList(LATEST_ACCEPTED+" FOR SHARE OF r",UUID.class,institution,branch,policy,version).stream().findFirst();}
 public boolean liveId(UUID id,String institution,String branch,UUID policy,int version){return liveId(id)&&latestAccepted(institution,branch,policy,version).filter(id::equals).isPresent();}
 public boolean liveId(UUID id){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM accounting_release_requests r WHERE r.id=? AND r.source_guard_version=2 AND NOT EXISTS(SELECT 1 FROM accounting_release_invalidations WHERE release_id=r.id) AND (SELECT count(*) FROM accounting_release_decisions WHERE release_id=r.id AND approved)=3 AND EXISTS(SELECT 1 FROM accounting_release_branch_sources b WHERE b.release_id=r.id AND b.role='CURRENT'))",Boolean.class,id));}
 public int invalidatePeriod(String institution,UUID period,UUID actor,String reason,OffsetDateTime now){return jdbc.update("WITH locked AS MATERIALIZED(SELECT id FROM accounting_release_requests WHERE sacco_id=? AND period_id=? ORDER BY id FOR UPDATE) INSERT INTO accounting_release_invalidations(id,release_id,kind,actor_id,reason,recorded_at) SELECT gen_random_uuid(),id,'PERIOD_REOPENED',?,?,? FROM locked",institution,period,actor,reason,now);}
 public int invalidateFrom(String institution,UUID period,java.time.LocalDate affectedFrom,UUID actor,String reason,OffsetDateTime now){return jdbc.update("WITH locked AS MATERIALIZED(SELECT r.id FROM accounting_release_requests r JOIN statement_output_sets s ON s.id=r.statement_output_id AND s.sacco_id=r.sacco_id WHERE r.sacco_id=? AND (r.period_id=? OR s.ends_on_iso>=?) AND NOT EXISTS(SELECT 1 FROM accounting_release_invalidations i WHERE i.release_id=r.id) ORDER BY r.id FOR UPDATE OF r) INSERT INTO accounting_release_invalidations(id,release_id,kind,actor_id,reason,recorded_at) SELECT gen_random_uuid(),id,'PERIOD_REOPENED',?,?,? FROM locked",institution,period,affectedFrom.toString(),actor,reason,now);}
 public int invalidateMapping(String institution,UUID template,UUID mapping,String kind,UUID actor,String reason,OffsetDateTime now){return jdbc.update("WITH locked AS MATERIALIZED(SELECT id FROM accounting_release_requests WHERE sacco_id=? AND template_id=? AND (?='MAPPING_APPROVED' OR mapping_id=?) ORDER BY id FOR UPDATE) INSERT INTO accounting_release_invalidations(id,release_id,kind,actor_id,reason,recorded_at) SELECT gen_random_uuid(),id,?,?,?,? FROM locked",institution,template,kind,mapping,kind,actor,reason,now);}
 public void withdraw(UUID id,UUID actor,String reason,OffsetDateTime now){jdbc.update("INSERT INTO accounting_release_invalidations(id,release_id,kind,actor_id,reason,recorded_at) VALUES(?,?,'WITHDRAWN',?,?,?)",UUID.randomUUID(),id,actor,reason,now);}
 public boolean hasInstitutionHistory(String institution){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM accounting_release_requests WHERE sacco_id=?) OR EXISTS(SELECT 1 FROM statement_output_sets WHERE sacco_id=?)",Boolean.class,institution,institution));}
 public boolean hasMemberHistory(UUID member){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM accounting_release_requests WHERE requested_by=?) OR EXISTS(SELECT 1 FROM accounting_release_decisions WHERE reviewer=?) OR EXISTS(SELECT 1 FROM accounting_release_invalidations WHERE actor_id=?) OR EXISTS(SELECT 1 FROM statement_output_sets WHERE generated_by=?) OR EXISTS(SELECT 1 FROM statement_output_reviews WHERE reviewer=?)",Boolean.class,member,member,member,member,member));}
 private Release read(ResultSet rs)throws SQLException {UUID id=rs.getObject("id",UUID.class);var decisions=List.of(mapper.readValue(rs.getString("decisions_json"),Decision[].class));return new Release(id,rs.getString("sacco_id"),rs.getString("station_id"),rs.getObject("requested_by",UUID.class),rs.getObject("requested_at",OffsetDateTime.class),rs.getObject("policy_id",UUID.class),rs.getInt("policy_version"),rs.getObject("period_id",UUID.class),rs.getObject("mapping_id",UUID.class),rs.getObject("template_id",UUID.class),rs.getObject("statement_output_id",UUID.class),rs.getObject("first_sample",UUID.class),rs.getObject("second_sample",UUID.class),rs.getString("dependency_json"),rs.getString("dependency_checksum"),rs.getString("proposal_evidence"),decisions,rs.getBoolean("invalidated"),rs.getInt("source_guard_version"));}
}
